/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ;
typedef struct tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ;
typedef struct tySequence__Ih0V9cYug0VPJyBBGvgEH7Q tySequence__Ih0V9cYug0VPJyBBGvgEH7Q;
typedef struct tyObject_JsonParsingError__XTejXaID1NT7KS9byQm3Jxg tyObject_JsonParsingError__XTejXaID1NT7KS9byQm3Jxg;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg {
  RootObj Sup;
NI bufpos;
NimStringDesc* buf;
tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
NI offsetBase;
tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw;
typedef NU8 tyEnum_JsonEventKind__0zjE9c54eTrq224F5wMcaFA;
typedef NU8 tyEnum_JsonError__G9cw5MrJXJrcpID5JXaplew;
struct tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ {
  tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg Sup;
NimStringDesc* a;
tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw tok;
tyEnum_JsonEventKind__0zjE9c54eTrq224F5wMcaFA kind;
tyEnum_JsonError__G9cw5MrJXJrcpID5JXaplew err;
tySequence__Ih0V9cYug0VPJyBBGvgEH7Q* state;
NimStringDesc* filename;
NIM_BOOL rawStringLiterals;
};
typedef NU8 tyEnum_ParserState__Na0rM2Zdr3RpxeNeXbvLrQ;
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_JsonParsingError__XTejXaID1NT7KS9byQm3Jxg {
  tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw Sup;
};
typedef NimStringDesc* tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NimStringDesc* tyArray__FkG8aLMyiZfDjueUwWl3WA[14];
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__Ih0V9cYug0VPJyBBGvgEH7Q {
  TGenericSeq Sup;
  tyEnum_ParserState__Na0rM2Zdr3RpxeNeXbvLrQ data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tySequence__Ih0V9cYug0VPJyBBGvgEH7Q)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, open__pureZlexbase_136)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input, NI bufLen, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, skip__pureZparsejson_341)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NI, handleCR__pureZlexbase_87)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(NI, handleLF__pureZlexbase_100)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(void, parseNumber__pureZparsejson_372)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_1692)(NimStringDesc* s, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw, parseString__pureZparsejson_250)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my);
N_LIB_PRIVATE N_NIMCALL(NI, parseEscapedUTF16__pureZparsejson_237)(NCSTRING buf, NI* pos);
static N_INLINE(NIM_BOOL, handleHexChar__stdZprivateZdecode95helpers_1)(NIM_CHAR c, NI* x);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nuctoUTF8)(NI32 c);
N_LIB_PRIVATE N_NIMCALL(void, parseName__pureZparsejson_427)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef__PyuSdojUZWOAnzN7dInq1Q)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsgExpected__pureZparsejson_233)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my, NimStringDesc* e);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_3)(NI x);
static N_INLINE(NI, getLine__pureZparsejson_206)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my);
static N_INLINE(NI, getColumn__pureZparsejson_194)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my);
N_LIB_PRIVATE N_NIMCALL(NI, getColNumber__pureZlexbase_155)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5311)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5305)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw, getTok__pureZparsejson_442)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my);
N_LIB_PRIVATE N_NOINLINE(void, raiseParseErr__pureZparsejson_597)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* p, NimStringDesc* msg) __attribute__((noreturn));
extern TNimType NTIbaselexer__MAw8rJZtJ279bVV3TWMtXSg_;
N_LIB_PRIVATE TNimType NTIjsonparser__KWIQnzXEOUqdWsnCUL9atyQ_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTItokkind__Q9c4KaNqJU4PbXaGht0C7iw_;
N_LIB_PRIVATE TNimType NTIjsoneventkind__0zjE9c54eTrq224F5wMcaFA_;
N_LIB_PRIVATE TNimType NTIjsonerror__G9cw5MrJXJrcpID5JXaplew_;
N_LIB_PRIVATE TNimType NTIparserstate__Na0rM2Zdr3RpxeNeXbvLrQ_;
N_LIB_PRIVATE TNimType NTIseqLparserstateT__Ih0V9cYug0VPJyBBGvgEH7Q_;
extern TNimType NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_;
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__nIinruGrC8EPIfjL3PuTvA_15 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_26, "0.", 2);
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__nIinruGrC8EPIfjL3PuTvA_34 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00,
0x20, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_71, "null", 4);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_72, "true", 4);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_73, "false", 5);
extern TNimType NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_;
N_LIB_PRIVATE TNimType NTIjsonparsingerror__XTejXaID1NT7KS9byQm3Jxg_;
N_LIB_PRIVATE TNimType NTIrefjsonparsingerror__PyuSdojUZWOAnzN7dInq1Q_;
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_75, "$1($2, $3) Error: $4", 20);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_76, " expected", 9);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_77, "invalid token", 13);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_78, "EOF", 3);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_79, "string literal", 14);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_80, "int literal", 11);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_81, "float literal", 13);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_82, "{", 1);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_83, "}", 1);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_84, "[", 1);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_85, "]", 1);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_86, ":", 1);
STRING_LITERAL(TM__nIinruGrC8EPIfjL3PuTvA_87, ",", 1);
N_LIB_PRIVATE NIM_CONST tyArray__FkG8aLMyiZfDjueUwWl3WA tokToStr__pureZparsejson_78 = {((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_77),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_78),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_79),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_80),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_81),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_72),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_73),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_71),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_82),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_83),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_84),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_85),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_86),
((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_87)}
;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5258;
static N_NIMCALL(void, Marker_tySequence__Ih0V9cYug0VPJyBBGvgEH7Q)(void* p, NI op) {
	tySequence__Ih0V9cYug0VPJyBBGvgEH7Q* a;
	NI T1_;
	a = (tySequence__Ih0V9cYug0VPJyBBGvgEH7Q*)p;
	T1_ = (NI)0;
}
N_LIB_PRIVATE N_NIMCALL(void, open__pureZparsejson_97)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input, NimStringDesc* filename, NIM_BOOL rawStringLiterals) {
	open__pureZlexbase_136(&my->Sup, input, ((NI) 8192), TM__nIinruGrC8EPIfjL3PuTvA_15);
	unsureAsgnRef((void**) (&(*my).filename), copyString(filename));
	unsureAsgnRef((void**) (&(*my).state), (tySequence__Ih0V9cYug0VPJyBBGvgEH7Q*) newSeq((&NTIseqLparserstateT__Ih0V9cYug0VPJyBBGvgEH7Q_), 1));
	(*my).state->data[0] = ((tyEnum_ParserState__Na0rM2Zdr3RpxeNeXbvLrQ) 1);
	(*my).kind = ((tyEnum_JsonEventKind__0zjE9c54eTrq224F5wMcaFA) 0);
	unsureAsgnRef((void**) (&(*my).a), ((NimStringDesc*) NIM_NIL));
	(*my).rawStringLiterals = rawStringLiterals;
}
N_LIB_PRIVATE N_NIMCALL(void, skip__pureZparsejson_341)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my) {
	NI pos;
	pos = (*my).Sup.bufpos;
	{
		while (1) {
			if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
			switch (((NU8)((*my).Sup.buf->data[pos]))) {
			case 47:
			{
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_16;
					NI TM__nIinruGrC8EPIfjL3PuTvA_17;
					if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_16)) { raiseOverflow(); };
					if ((NI)(TM__nIinruGrC8EPIfjL3PuTvA_16) < 0 || (NI)(TM__nIinruGrC8EPIfjL3PuTvA_16) >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2((NI)(TM__nIinruGrC8EPIfjL3PuTvA_16),((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
					if (!((NU8)((*my).Sup.buf->data[(NI)(TM__nIinruGrC8EPIfjL3PuTvA_16)]) == (NU8)(47))) goto LA6_;
					if (nimAddInt(pos, ((NI) 2), &TM__nIinruGrC8EPIfjL3PuTvA_17)) { raiseOverflow(); };
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_17);
					{
						while (1) {
							if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
							switch (((NU8)((*my).Sup.buf->data[pos]))) {
							case 0:
							{
								goto LA8;
							}
							break;
							case 13:
							{
								pos = handleCR__pureZlexbase_87(&my->Sup, pos);
								goto LA8;
							}
							break;
							case 10:
							{
								pos = handleLF__pureZlexbase_100(&my->Sup, pos);
								goto LA8;
							}
							break;
							default:
							{
								NI TM__nIinruGrC8EPIfjL3PuTvA_18;
								if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_18)) { raiseOverflow(); };
								pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_18);
							}
							break;
							}
						}
					} LA8: ;
				}
				goto LA4_;
				LA6_: ;
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_19;
					NI TM__nIinruGrC8EPIfjL3PuTvA_20;
					if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_19)) { raiseOverflow(); };
					if ((NI)(TM__nIinruGrC8EPIfjL3PuTvA_19) < 0 || (NI)(TM__nIinruGrC8EPIfjL3PuTvA_19) >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2((NI)(TM__nIinruGrC8EPIfjL3PuTvA_19),((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
					if (!((NU8)((*my).Sup.buf->data[(NI)(TM__nIinruGrC8EPIfjL3PuTvA_19)]) == (NU8)(42))) goto LA15_;
					if (nimAddInt(pos, ((NI) 2), &TM__nIinruGrC8EPIfjL3PuTvA_20)) { raiseOverflow(); };
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_20);
					{
						while (1) {
							if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
							switch (((NU8)((*my).Sup.buf->data[pos]))) {
							case 0:
							{
								(*my).err = ((tyEnum_JsonError__G9cw5MrJXJrcpID5JXaplew) 8);
								goto LA17;
							}
							break;
							case 13:
							{
								pos = handleCR__pureZlexbase_87(&my->Sup, pos);
							}
							break;
							case 10:
							{
								pos = handleLF__pureZlexbase_100(&my->Sup, pos);
							}
							break;
							case 42:
							{
								NI TM__nIinruGrC8EPIfjL3PuTvA_21;
								if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_21)) { raiseOverflow(); };
								pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_21);
								{
									NI TM__nIinruGrC8EPIfjL3PuTvA_22;
									if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
									if (!((NU8)((*my).Sup.buf->data[pos]) == (NU8)(47))) goto LA25_;
									if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_22)) { raiseOverflow(); };
									pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_22);
									goto LA17;
								}
								LA25_: ;
							}
							break;
							default:
							{
								NI TM__nIinruGrC8EPIfjL3PuTvA_23;
								if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_23)) { raiseOverflow(); };
								pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_23);
							}
							break;
							}
						}
					} LA17: ;
				}
				goto LA4_;
				LA15_: ;
				{
					goto LA1;
				}
				LA4_: ;
			}
			break;
			case 32:
			case 9:
			{
				NI TM__nIinruGrC8EPIfjL3PuTvA_24;
				if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_24)) { raiseOverflow(); };
				pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_24);
			}
			break;
			case 13:
			{
				pos = handleCR__pureZlexbase_87(&my->Sup, pos);
			}
			break;
			case 10:
			{
				pos = handleLF__pureZlexbase_100(&my->Sup, pos);
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	(*my).Sup.bufpos = pos;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, parseNumber__pureZparsejson_372)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my) {
	NI pos;
	pos = (*my).Sup.bufpos;
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_25;
		if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
		if (!((NU8)((*my).Sup.buf->data[pos]) == (NU8)(45))) goto LA3_;
		unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 45));
		if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_25)) { raiseOverflow(); };
		pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_25);
	}
	LA3_: ;
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_27;
		if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
		if (!((NU8)((*my).Sup.buf->data[pos]) == (NU8)(46))) goto LA7_;
		unsureAsgnRef((void**) (&(*my).a), resizeString((*my).a, 2));
appendString((*my).a, ((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_26));
		if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_27)) { raiseOverflow(); };
		pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_27);
	}
	goto LA5_;
	LA7_: ;
	{
		{
			while (1) {
				NI TM__nIinruGrC8EPIfjL3PuTvA_28;
				if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
				if (!(((NU8)((*my).Sup.buf->data[pos])) >= ((NU8)(48)) && ((NU8)((*my).Sup.buf->data[pos])) <= ((NU8)(57)))) goto LA11;
				if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
				unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, (*my).Sup.buf->data[pos]));
				if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_28)) { raiseOverflow(); };
				pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_28);
			} LA11: ;
		}
		{
			NI TM__nIinruGrC8EPIfjL3PuTvA_29;
			if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
			if (!((NU8)((*my).Sup.buf->data[pos]) == (NU8)(46))) goto LA14_;
			unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 46));
			if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_29)) { raiseOverflow(); };
			pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_29);
		}
		LA14_: ;
	}
	LA5_: ;
	{
		while (1) {
			NI TM__nIinruGrC8EPIfjL3PuTvA_30;
			if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
			if (!(((NU8)((*my).Sup.buf->data[pos])) >= ((NU8)(48)) && ((NU8)((*my).Sup.buf->data[pos])) <= ((NU8)(57)))) goto LA17;
			if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
			unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, (*my).Sup.buf->data[pos]));
			if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_30)) { raiseOverflow(); };
			pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_30);
		} LA17: ;
	}
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_31;
		if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
		if (!(((NU8)((*my).Sup.buf->data[pos])) == ((NU8)(69)) || ((NU8)((*my).Sup.buf->data[pos])) == ((NU8)(101)))) goto LA20_;
		if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
		unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, (*my).Sup.buf->data[pos]));
		if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_31)) { raiseOverflow(); };
		pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_31);
		{
			NI TM__nIinruGrC8EPIfjL3PuTvA_32;
			if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
			if (!(((NU8)((*my).Sup.buf->data[pos])) == ((NU8)(43)) || ((NU8)((*my).Sup.buf->data[pos])) == ((NU8)(45)))) goto LA24_;
			if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
			unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, (*my).Sup.buf->data[pos]));
			if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_32)) { raiseOverflow(); };
			pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_32);
		}
		LA24_: ;
		{
			while (1) {
				NI TM__nIinruGrC8EPIfjL3PuTvA_33;
				if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
				if (!(((NU8)((*my).Sup.buf->data[pos])) >= ((NU8)(48)) && ((NU8)((*my).Sup.buf->data[pos])) <= ((NU8)(57)))) goto LA27;
				if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
				unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, (*my).Sup.buf->data[pos]));
				if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_33)) { raiseOverflow(); };
				pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_33);
			} LA27: ;
		}
	}
	LA20_: ;
	(*my).Sup.bufpos = pos;
}
static N_INLINE(NIM_BOOL, handleHexChar__stdZprivateZdecode95helpers_1)(NIM_CHAR c, NI* x) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = NIM_TRUE;
	switch (((NU8)(c))) {
	case 48 ... 57:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_47;
		if (nimSubInt(((NU8)(c)), ((NI) 48), &TM__nIinruGrC8EPIfjL3PuTvA_47)) { raiseOverflow(); };
		(*x) = (NI)((NI)((NU32)((*x)) << (NU32)(((NI) 4))) | (NI)(TM__nIinruGrC8EPIfjL3PuTvA_47));
	}
	break;
	case 97 ... 102:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_48;
		NI TM__nIinruGrC8EPIfjL3PuTvA_49;
		if (nimSubInt(((NU8)(c)), ((NI) 97), &TM__nIinruGrC8EPIfjL3PuTvA_48)) { raiseOverflow(); };
		if (nimAddInt((NI)(TM__nIinruGrC8EPIfjL3PuTvA_48), ((NI) 10), &TM__nIinruGrC8EPIfjL3PuTvA_49)) { raiseOverflow(); };
		(*x) = (NI)((NI)((NU32)((*x)) << (NU32)(((NI) 4))) | (NI)(TM__nIinruGrC8EPIfjL3PuTvA_49));
	}
	break;
	case 65 ... 70:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_50;
		NI TM__nIinruGrC8EPIfjL3PuTvA_51;
		if (nimSubInt(((NU8)(c)), ((NI) 65), &TM__nIinruGrC8EPIfjL3PuTvA_50)) { raiseOverflow(); };
		if (nimAddInt((NI)(TM__nIinruGrC8EPIfjL3PuTvA_50), ((NI) 10), &TM__nIinruGrC8EPIfjL3PuTvA_51)) { raiseOverflow(); };
		(*x) = (NI)((NI)((NU32)((*x)) << (NU32)(((NI) 4))) | (NI)(TM__nIinruGrC8EPIfjL3PuTvA_51));
	}
	break;
	default:
	{
		result = NIM_FALSE;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, parseEscapedUTF16__pureZparsejson_237)(NCSTRING buf, NI* pos) {
	NI result;
{	result = (NI)0;
	result = ((NI) 0);
	{
		NI _;
		NI res;
		_ = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				NI TM__nIinruGrC8EPIfjL3PuTvA_53;
				if (!(res <= ((NI) 3))) goto LA3;
				_ = res;
				{
					NIM_BOOL T6_;
					NI TM__nIinruGrC8EPIfjL3PuTvA_52;
					T6_ = (NIM_BOOL)0;
					T6_ = handleHexChar__stdZprivateZdecode95helpers_1(buf[(*pos)], (&result));
					if (!T6_) goto LA7_;
					if (nimAddInt((*pos), ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_52)) { raiseOverflow(); };
					(*pos) = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_52);
				}
				goto LA4_;
				LA7_: ;
				{
					result = ((NI) -1);
					goto BeforeRet_;
				}
				LA4_: ;
				if (nimAddInt(res, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_53)) { raiseOverflow(); };
				res = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_53);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringDesc* s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (s == ((NimStringDesc*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((*s).Sup.len == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = "";
	}
	goto LA1_;
	LA5_: ;
	{
		result = ((NCSTRING) ((*s).data));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw, parseString__pureZparsejson_250)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my) {
	tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw result;
	NI pos;
	NI TM__nIinruGrC8EPIfjL3PuTvA_35;
	result = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
	result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 2);
	if (nimAddInt((*my).Sup.bufpos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_35)) { raiseOverflow(); };
	pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_35);
	{
		if (!(*my).rawStringLiterals) goto LA3_;
		unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 34));
	}
	LA3_: ;
	{
		while (1) {
			if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
			switch (((NU8)((*my).Sup.buf->data[pos]))) {
			case 0:
			{
				(*my).err = ((tyEnum_JsonError__G9cw5MrJXJrcpID5JXaplew) 7);
				result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 0);
				goto LA5;
			}
			break;
			case 34:
			{
				NI TM__nIinruGrC8EPIfjL3PuTvA_36;
				{
					if (!(*my).rawStringLiterals) goto LA11_;
					unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 34));
				}
				LA11_: ;
				if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_36)) { raiseOverflow(); };
				pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_36);
				goto LA5;
			}
			break;
			case 92:
			{
				NI TM__nIinruGrC8EPIfjL3PuTvA_37;
				{
					if (!(*my).rawStringLiterals) goto LA16_;
					unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 92));
				}
				LA16_: ;
				if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_37)) { raiseOverflow(); };
				if ((NI)(TM__nIinruGrC8EPIfjL3PuTvA_37) < 0 || (NI)(TM__nIinruGrC8EPIfjL3PuTvA_37) >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2((NI)(TM__nIinruGrC8EPIfjL3PuTvA_37),((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
				switch (((NU8)((*my).Sup.buf->data[(NI)(TM__nIinruGrC8EPIfjL3PuTvA_37)]))) {
				case 92:
				case 34:
				case 39:
				case 47:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_38;
					NI TM__nIinruGrC8EPIfjL3PuTvA_39;
					if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_38)) { raiseOverflow(); };
					if ((NI)(TM__nIinruGrC8EPIfjL3PuTvA_38) < 0 || (NI)(TM__nIinruGrC8EPIfjL3PuTvA_38) >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2((NI)(TM__nIinruGrC8EPIfjL3PuTvA_38),((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
					unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, (*my).Sup.buf->data[(NI)(TM__nIinruGrC8EPIfjL3PuTvA_38)]));
					if (nimAddInt(pos, ((NI) 2), &TM__nIinruGrC8EPIfjL3PuTvA_39)) { raiseOverflow(); };
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_39);
				}
				break;
				case 98:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_40;
					unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 8));
					if (nimAddInt(pos, ((NI) 2), &TM__nIinruGrC8EPIfjL3PuTvA_40)) { raiseOverflow(); };
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_40);
				}
				break;
				case 102:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_41;
					unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 12));
					if (nimAddInt(pos, ((NI) 2), &TM__nIinruGrC8EPIfjL3PuTvA_41)) { raiseOverflow(); };
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_41);
				}
				break;
				case 110:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_42;
					unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 10));
					if (nimAddInt(pos, ((NI) 2), &TM__nIinruGrC8EPIfjL3PuTvA_42)) { raiseOverflow(); };
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_42);
				}
				break;
				case 114:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_43;
					unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 13));
					if (nimAddInt(pos, ((NI) 2), &TM__nIinruGrC8EPIfjL3PuTvA_43)) { raiseOverflow(); };
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_43);
				}
				break;
				case 116:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_44;
					unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 9));
					if (nimAddInt(pos, ((NI) 2), &TM__nIinruGrC8EPIfjL3PuTvA_44)) { raiseOverflow(); };
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_44);
				}
				break;
				case 118:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_45;
					unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 11));
					if (nimAddInt(pos, ((NI) 2), &TM__nIinruGrC8EPIfjL3PuTvA_45)) { raiseOverflow(); };
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_45);
				}
				break;
				case 117:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_46;
					NI pos2;
					NI r;
					{
						if (!(*my).rawStringLiterals) goto LA28_;
						unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 117));
					}
					LA28_: ;
					if (nimAddInt(pos, ((NI) 2), &TM__nIinruGrC8EPIfjL3PuTvA_46)) { raiseOverflow(); };
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_46);
					pos2 = pos;
					r = parseEscapedUTF16__pureZparsejson_237(nimToCStringConv((*my).Sup.buf), (&pos));
					{
						if (!(r < ((NI) 0))) goto LA32_;
						(*my).err = ((tyEnum_JsonError__G9cw5MrJXJrcpID5JXaplew) 1);
						goto LA5;
					}
					LA32_: ;
					{
						NI TM__nIinruGrC8EPIfjL3PuTvA_55;
						NI s;
						if (!((NI)(r & ((NI) 64512)) == ((NI) 55296))) goto LA36_;
						{
							NIM_BOOL T40_;
							NI TM__nIinruGrC8EPIfjL3PuTvA_54;
							T40_ = (NIM_BOOL)0;
							if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
							T40_ = !(((NU8)((*my).Sup.buf->data[pos]) == (NU8)(92)));
							if (T40_) goto LA41_;
							if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_54)) { raiseOverflow(); };
							if ((NI)(TM__nIinruGrC8EPIfjL3PuTvA_54) < 0 || (NI)(TM__nIinruGrC8EPIfjL3PuTvA_54) >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2((NI)(TM__nIinruGrC8EPIfjL3PuTvA_54),((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
							T40_ = !(((NU8)((*my).Sup.buf->data[(NI)(TM__nIinruGrC8EPIfjL3PuTvA_54)]) == (NU8)(117)));
							LA41_: ;
							if (!T40_) goto LA42_;
							(*my).err = ((tyEnum_JsonError__G9cw5MrJXJrcpID5JXaplew) 1);
							goto LA5;
						}
						LA42_: ;
						if (nimAddInt(pos, ((NI) 2), &TM__nIinruGrC8EPIfjL3PuTvA_55)) { raiseOverflow(); };
						pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_55);
						s = parseEscapedUTF16__pureZparsejson_237(nimToCStringConv((*my).Sup.buf), (&pos));
						{
							NIM_BOOL T46_;
							NI TM__nIinruGrC8EPIfjL3PuTvA_56;
							NI TM__nIinruGrC8EPIfjL3PuTvA_57;
							NI TM__nIinruGrC8EPIfjL3PuTvA_58;
							T46_ = (NIM_BOOL)0;
							T46_ = ((NI)(s & ((NI) 64512)) == ((NI) 56320));
							if (!(T46_)) goto LA47_;
							T46_ = (((NI) 0) < s);
							LA47_: ;
							if (!T46_) goto LA48_;
							if (nimSubInt(r, ((NI) 55296), &TM__nIinruGrC8EPIfjL3PuTvA_56)) { raiseOverflow(); };
							if (nimSubInt(s, ((NI) 56320), &TM__nIinruGrC8EPIfjL3PuTvA_57)) { raiseOverflow(); };
							if (nimAddInt(((NI) 65536), (NI)((NI)((NU32)((NI)(TM__nIinruGrC8EPIfjL3PuTvA_56)) << (NU32)(((NI) 10))) | (NI)(TM__nIinruGrC8EPIfjL3PuTvA_57)), &TM__nIinruGrC8EPIfjL3PuTvA_58)) { raiseOverflow(); };
							r = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_58);
						}
						goto LA44_;
						LA48_: ;
						{
							(*my).err = ((tyEnum_JsonError__G9cw5MrJXJrcpID5JXaplew) 1);
							goto LA5;
						}
						LA44_: ;
					}
					LA36_: ;
					{
						NI length;
						NI TM__nIinruGrC8EPIfjL3PuTvA_59;
						if (!(*my).rawStringLiterals) goto LA53_;
						if (nimSubInt(pos, pos2, &TM__nIinruGrC8EPIfjL3PuTvA_59)) { raiseOverflow(); };
						length = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_59);
						{
							NI i;
							NI res;
							i = (NI)0;
							res = ((NI) 1);
							{
								while (1) {
									NI TM__nIinruGrC8EPIfjL3PuTvA_61;
									if (!(res <= length)) goto LA57;
									i = res;
									{
										NI TM__nIinruGrC8EPIfjL3PuTvA_60;
										if (pos2 < 0 || pos2 >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos2,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
										if (!(((NU8)((*my).Sup.buf->data[pos2])) >= ((NU8)(48)) && ((NU8)((*my).Sup.buf->data[pos2])) <= ((NU8)(57)) || ((NU8)((*my).Sup.buf->data[pos2])) >= ((NU8)(65)) && ((NU8)((*my).Sup.buf->data[pos2])) <= ((NU8)(70)) || ((NU8)((*my).Sup.buf->data[pos2])) >= ((NU8)(97)) && ((NU8)((*my).Sup.buf->data[pos2])) <= ((NU8)(102)))) goto LA60_;
										if (pos2 < 0 || pos2 >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos2,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
										unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, (*my).Sup.buf->data[pos2]));
										if (nimAddInt(pos2, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_60)) { raiseOverflow(); };
										pos2 = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_60);
									}
									goto LA58_;
									LA60_: ;
									{
										goto LA55;
									}
									LA58_: ;
									if (nimAddInt(res, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_61)) { raiseOverflow(); };
									res = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_61);
								} LA57: ;
							}
						} LA55: ;
					}
					goto LA51_;
					LA53_: ;
					{
						NimStringDesc* T64_;
						T64_ = NIM_NIL;
						T64_ = nuctoUTF8(((NI32) (r)));
						unsureAsgnRef((void**) (&(*my).a), resizeString((*my).a, (T64_ ? T64_->Sup.len : 0) + 0));
appendString((*my).a, T64_);
					}
					LA51_: ;
				}
				break;
				default:
				{
					NI TM__nIinruGrC8EPIfjL3PuTvA_62;
					if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
					unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, (*my).Sup.buf->data[pos]));
					if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_62)) { raiseOverflow(); };
					pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_62);
				}
				break;
				}
			}
			break;
			case 13:
			{
				pos = handleCR__pureZlexbase_87(&my->Sup, pos);
				unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 13));
			}
			break;
			case 10:
			{
				pos = handleLF__pureZlexbase_100(&my->Sup, pos);
				unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, 10));
			}
			break;
			default:
			{
				NI TM__nIinruGrC8EPIfjL3PuTvA_63;
				if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
				unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, (*my).Sup.buf->data[pos]));
				if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_63)) { raiseOverflow(); };
				pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_63);
			}
			break;
			}
		}
	} LA5: ;
	(*my).Sup.bufpos = pos;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, parseName__pureZparsejson_427)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my) {
	NI pos;
	pos = (*my).Sup.bufpos;
	{
		if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
		if (!(((NU8)((*my).Sup.buf->data[pos])) >= ((NU8)(97)) && ((NU8)((*my).Sup.buf->data[pos])) <= ((NU8)(122)) || ((NU8)((*my).Sup.buf->data[pos])) >= ((NU8)(65)) && ((NU8)((*my).Sup.buf->data[pos])) <= ((NU8)(90)) || ((NU8)((*my).Sup.buf->data[pos])) == ((NU8)(95)))) goto LA3_;
		{
			while (1) {
				NI TM__nIinruGrC8EPIfjL3PuTvA_70;
				if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
				if (!(((NU8)((*my).Sup.buf->data[pos])) >= ((NU8)(97)) && ((NU8)((*my).Sup.buf->data[pos])) <= ((NU8)(122)) || ((NU8)((*my).Sup.buf->data[pos])) >= ((NU8)(65)) && ((NU8)((*my).Sup.buf->data[pos])) <= ((NU8)(90)) || ((NU8)((*my).Sup.buf->data[pos])) >= ((NU8)(48)) && ((NU8)((*my).Sup.buf->data[pos])) <= ((NU8)(57)) || ((NU8)((*my).Sup.buf->data[pos])) == ((NU8)(95)))) goto LA6;
				if (pos < 0 || pos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2(pos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
				unsureAsgnRef((void**) (&(*my).a), addChar((*my).a, (*my).Sup.buf->data[pos]));
				if (nimAddInt(pos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_70)) { raiseOverflow(); };
				pos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_70);
			} LA6: ;
		}
	}
	LA3_: ;
	(*my).Sup.bufpos = pos;
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	alen = (a ? a->Sup.len : 0);
	blen = (b ? b->Sup.len : 0);
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		result = equalMem__system_1735(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw, getTok__pureZparsejson_442)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my) {
	tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw result;
	result = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
	unsureAsgnRef((void**) (&(*my).a), setLengthStr((*my).a, ((NI) 0)));
	skip__pureZparsejson_341(my);
	if ((*my).Sup.bufpos < 0 || (*my).Sup.bufpos >= ((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)){ raiseIndexError2((*my).Sup.bufpos,((*my).Sup.buf ? (*my).Sup.buf->Sup.len : 0)-1); }
	switch (((NU8)((*my).Sup.buf->data[(*my).Sup.bufpos]))) {
	case 45:
	case 46:
	case 48 ... 57:
	{
		parseNumber__pureZparsejson_372(my);
		{
			NIM_BOOL T4_;
			T4_ = (NIM_BOOL)0;
			T4_ = contains__pureZstrutils_1692((*my).a, TM__nIinruGrC8EPIfjL3PuTvA_34);
			if (!T4_) goto LA5_;
			result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 4);
		}
		goto LA2_;
		LA5_: ;
		{
			result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 3);
		}
		LA2_: ;
	}
	break;
	case 34:
	{
		result = parseString__pureZparsejson_250(my);
	}
	break;
	case 91:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_64;
		if (nimAddInt((*my).Sup.bufpos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_64)) { raiseOverflow(); };
		(*my).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_64);
		result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 10);
	}
	break;
	case 123:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_65;
		if (nimAddInt((*my).Sup.bufpos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_65)) { raiseOverflow(); };
		(*my).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_65);
		result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 8);
	}
	break;
	case 93:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_66;
		if (nimAddInt((*my).Sup.bufpos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_66)) { raiseOverflow(); };
		(*my).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_66);
		result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 11);
	}
	break;
	case 125:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_67;
		if (nimAddInt((*my).Sup.bufpos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_67)) { raiseOverflow(); };
		(*my).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_67);
		result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 9);
	}
	break;
	case 44:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_68;
		if (nimAddInt((*my).Sup.bufpos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_68)) { raiseOverflow(); };
		(*my).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_68);
		result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 13);
	}
	break;
	case 58:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_69;
		if (nimAddInt((*my).Sup.bufpos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_69)) { raiseOverflow(); };
		(*my).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_69);
		result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 12);
	}
	break;
	case 0:
	{
		result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 1);
	}
	break;
	case 97 ... 122:
	case 65 ... 90:
	case 95:
	{
		parseName__pureZparsejson_427(my);
		if (eqStrings((*my).a, ((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_71))) goto LA17_;
		if (eqStrings((*my).a, ((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_72))) goto LA18_;
		if (eqStrings((*my).a, ((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_73))) goto LA19_;
		goto LA20_;
		LA17_: ;
		{
			result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 7);
		}
		goto LA21_;
		LA18_: ;
		{
			result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 5);
		}
		goto LA21_;
		LA19_: ;
		{
			result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 6);
		}
		goto LA21_;
		LA20_: ;
		{
			result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 0);
		}
		LA21_: ;
	}
	break;
	default:
	{
		NI TM__nIinruGrC8EPIfjL3PuTvA_74;
		if (nimAddInt((*my).Sup.bufpos, ((NI) 1), &TM__nIinruGrC8EPIfjL3PuTvA_74)) { raiseOverflow(); };
		(*my).Sup.bufpos = (NI)(TM__nIinruGrC8EPIfjL3PuTvA_74);
		result = ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 0);
	}
	break;
	}
	(*my).tok = result;
	return result;
}
static N_NIMCALL(void, Marker_tyRef__PyuSdojUZWOAnzN7dInq1Q)(void* p, NI op) {
	tyObject_JsonParsingError__XTejXaID1NT7KS9byQm3Jxg* a;
	a = (tyObject_JsonParsingError__XTejXaID1NT7KS9byQm3Jxg*)p;
	nimGCvisit((void*)(*a).Sup.Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.Sup.up, op);
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(NI, getLine__pureZparsejson_206)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my) {
	NI result;
	result = (NI)0;
	result = (*my).Sup.lineNumber;
	return result;
}
static N_INLINE(NI, getColumn__pureZparsejson_194)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my) {
	NI result;
	result = (NI)0;
	result = getColNumber__pureZlexbase_155((&(*my).Sup), (*my).Sup.bufpos);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsgExpected__pureZparsejson_233)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my, NimStringDesc* e) {
	NimStringDesc* result;
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ T1_;
	NI T2_;
	NI T3_;
	NimStringDesc* T4_;
	result = NIM_NIL;
	nimZeroMem((void*)T1_, sizeof(tyArray__sMpvt1sOxOJ3LFGulnbeMQ));
	T1_[0] = copyString((*my).filename);
	T2_ = (NI)0;
	T2_ = getLine__pureZparsejson_206(my);
	T1_[1] = dollar___systemZdollars_3(T2_);
	T3_ = (NI)0;
	T3_ = getColumn__pureZparsejson_194(my);
	T1_[2] = dollar___systemZdollars_3(T3_);
	T4_ = NIM_NIL;
	T4_ = rawNewString((e ? e->Sup.len : 0) + 9);
appendString(T4_, e);
appendString(T4_, ((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_76));
	T1_[3] = T4_;
	result = nsuFormatOpenArray(((NimStringDesc*) &TM__nIinruGrC8EPIfjL3PuTvA_75), T1_, 4);
	return result;
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5311)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 8));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU32)(((NU) (x))) < (NU32)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5305((&gch__system_5258.zct), c);
}
static N_INLINE(void, decRef__system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5354(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5311(src);
		incRef__system_5349(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5311((*dest));
		decRef__system_5356(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseParseErr__pureZparsejson_597)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* p, NimStringDesc* msg) {
	tyObject_JsonParsingError__XTejXaID1NT7KS9byQm3Jxg* T1_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonParsingError__XTejXaID1NT7KS9byQm3Jxg*) newObj((&NTIrefjsonparsingerror__PyuSdojUZWOAnzN7dInq1Q_), sizeof(tyObject_JsonParsingError__XTejXaID1NT7KS9byQm3Jxg));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIjsonparsingerror__XTejXaID1NT7KS9byQm3Jxg_);
	(*T1_).Sup.Sup.Sup.name = "JsonParsingError";
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.message), errorMsgExpected__pureZparsejson_233(p, msg));
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "JsonParsingError", "raiseParseErr", "parsejson.nim", 515);
}
N_LIB_PRIVATE N_NIMCALL(void, eat__pureZparsejson_619)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* p, tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw tok) {
	{
		tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T5_;
		if (!((*p).tok == tok)) goto LA3_;
		T5_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
		T5_ = getTok__pureZparsejson_442(p);
		(void)(T5_);
	}
	goto LA1_;
	LA3_: ;
	{
		raiseParseErr__pureZparsejson_597((&(*p)), tokToStr__pureZparsejson_78[(tok)- 0]);
	}
	LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsNimminusREatsnimminus1dot6dot10atslibatspureatsparsejsondotnim_DatInit000)(void) {
static TNimNode* TM__nIinruGrC8EPIfjL3PuTvA_2_7[7];
static TNimNode* TM__nIinruGrC8EPIfjL3PuTvA_3_14[14];
NI TM__nIinruGrC8EPIfjL3PuTvA_5;
static char* NIM_CONST TM__nIinruGrC8EPIfjL3PuTvA_4[14] = {
"tkError", 
"tkEof", 
"tkString", 
"tkInt", 
"tkFloat", 
"tkTrue", 
"tkFalse", 
"tkNull", 
"tkCurlyLe", 
"tkCurlyRi", 
"tkBracketLe", 
"tkBracketRi", 
"tkColon", 
"tkComma"};
static TNimNode* TM__nIinruGrC8EPIfjL3PuTvA_6_12[12];
NI TM__nIinruGrC8EPIfjL3PuTvA_8;
static char* NIM_CONST TM__nIinruGrC8EPIfjL3PuTvA_7[12] = {
"jsonError", 
"jsonEof", 
"jsonString", 
"jsonInt", 
"jsonFloat", 
"jsonTrue", 
"jsonFalse", 
"jsonNull", 
"jsonObjectStart", 
"jsonObjectEnd", 
"jsonArrayStart", 
"jsonArrayEnd"};
static TNimNode* TM__nIinruGrC8EPIfjL3PuTvA_9_11[11];
NI TM__nIinruGrC8EPIfjL3PuTvA_11;
static char* NIM_CONST TM__nIinruGrC8EPIfjL3PuTvA_10[11] = {
"errNone", 
"errInvalidToken", 
"errStringExpected", 
"errColonExpected", 
"errCommaExpected", 
"errBracketRiExpected", 
"errCurlyRiExpected", 
"errQuoteExpected", 
"errEOC_Expected", 
"errEofExpected", 
"errExprExpected"};
static TNimNode* TM__nIinruGrC8EPIfjL3PuTvA_12_8[8];
NI TM__nIinruGrC8EPIfjL3PuTvA_14;
static char* NIM_CONST TM__nIinruGrC8EPIfjL3PuTvA_13[8] = {
"stateEof", 
"stateStart", 
"stateObject", 
"stateArray", 
"stateExpectArrayComma", 
"stateExpectObjectComma", 
"stateExpectColon", 
"stateExpectValue"};
static TNimNode TM__nIinruGrC8EPIfjL3PuTvA_0[58];
NTIjsonparser__KWIQnzXEOUqdWsnCUL9atyQ_.size = sizeof(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ);
NTIjsonparser__KWIQnzXEOUqdWsnCUL9atyQ_.align = NIM_ALIGNOF(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ);
NTIjsonparser__KWIQnzXEOUqdWsnCUL9atyQ_.kind = 17;
NTIjsonparser__KWIQnzXEOUqdWsnCUL9atyQ_.base = (&NTIbaselexer__MAw8rJZtJ279bVV3TWMtXSg_);
TM__nIinruGrC8EPIfjL3PuTvA_2_7[0] = &TM__nIinruGrC8EPIfjL3PuTvA_0[1];
TM__nIinruGrC8EPIfjL3PuTvA_0[1].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[1].offset = offsetof(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ, a);
TM__nIinruGrC8EPIfjL3PuTvA_0[1].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__nIinruGrC8EPIfjL3PuTvA_0[1].name = "a";
TM__nIinruGrC8EPIfjL3PuTvA_2_7[1] = &TM__nIinruGrC8EPIfjL3PuTvA_0[2];
NTItokkind__Q9c4KaNqJU4PbXaGht0C7iw_.size = sizeof(tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw);
NTItokkind__Q9c4KaNqJU4PbXaGht0C7iw_.align = NIM_ALIGNOF(tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw);
NTItokkind__Q9c4KaNqJU4PbXaGht0C7iw_.kind = 14;
NTItokkind__Q9c4KaNqJU4PbXaGht0C7iw_.base = 0;
NTItokkind__Q9c4KaNqJU4PbXaGht0C7iw_.flags = 3;
for (TM__nIinruGrC8EPIfjL3PuTvA_5 = 0; TM__nIinruGrC8EPIfjL3PuTvA_5 < 14; TM__nIinruGrC8EPIfjL3PuTvA_5++) {
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_5+3].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_5+3].offset = TM__nIinruGrC8EPIfjL3PuTvA_5;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_5+3].name = TM__nIinruGrC8EPIfjL3PuTvA_4[TM__nIinruGrC8EPIfjL3PuTvA_5];
TM__nIinruGrC8EPIfjL3PuTvA_3_14[TM__nIinruGrC8EPIfjL3PuTvA_5] = &TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_5+3];
}
TM__nIinruGrC8EPIfjL3PuTvA_0[17].len = 14; TM__nIinruGrC8EPIfjL3PuTvA_0[17].kind = 2; TM__nIinruGrC8EPIfjL3PuTvA_0[17].sons = &TM__nIinruGrC8EPIfjL3PuTvA_3_14[0];
NTItokkind__Q9c4KaNqJU4PbXaGht0C7iw_.node = &TM__nIinruGrC8EPIfjL3PuTvA_0[17];
TM__nIinruGrC8EPIfjL3PuTvA_0[2].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[2].offset = offsetof(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ, tok);
TM__nIinruGrC8EPIfjL3PuTvA_0[2].typ = (&NTItokkind__Q9c4KaNqJU4PbXaGht0C7iw_);
TM__nIinruGrC8EPIfjL3PuTvA_0[2].name = "tok";
TM__nIinruGrC8EPIfjL3PuTvA_2_7[2] = &TM__nIinruGrC8EPIfjL3PuTvA_0[18];
NTIjsoneventkind__0zjE9c54eTrq224F5wMcaFA_.size = sizeof(tyEnum_JsonEventKind__0zjE9c54eTrq224F5wMcaFA);
NTIjsoneventkind__0zjE9c54eTrq224F5wMcaFA_.align = NIM_ALIGNOF(tyEnum_JsonEventKind__0zjE9c54eTrq224F5wMcaFA);
NTIjsoneventkind__0zjE9c54eTrq224F5wMcaFA_.kind = 14;
NTIjsoneventkind__0zjE9c54eTrq224F5wMcaFA_.base = 0;
NTIjsoneventkind__0zjE9c54eTrq224F5wMcaFA_.flags = 3;
for (TM__nIinruGrC8EPIfjL3PuTvA_8 = 0; TM__nIinruGrC8EPIfjL3PuTvA_8 < 12; TM__nIinruGrC8EPIfjL3PuTvA_8++) {
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_8+19].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_8+19].offset = TM__nIinruGrC8EPIfjL3PuTvA_8;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_8+19].name = TM__nIinruGrC8EPIfjL3PuTvA_7[TM__nIinruGrC8EPIfjL3PuTvA_8];
TM__nIinruGrC8EPIfjL3PuTvA_6_12[TM__nIinruGrC8EPIfjL3PuTvA_8] = &TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_8+19];
}
TM__nIinruGrC8EPIfjL3PuTvA_0[31].len = 12; TM__nIinruGrC8EPIfjL3PuTvA_0[31].kind = 2; TM__nIinruGrC8EPIfjL3PuTvA_0[31].sons = &TM__nIinruGrC8EPIfjL3PuTvA_6_12[0];
NTIjsoneventkind__0zjE9c54eTrq224F5wMcaFA_.node = &TM__nIinruGrC8EPIfjL3PuTvA_0[31];
TM__nIinruGrC8EPIfjL3PuTvA_0[18].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[18].offset = offsetof(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ, kind);
TM__nIinruGrC8EPIfjL3PuTvA_0[18].typ = (&NTIjsoneventkind__0zjE9c54eTrq224F5wMcaFA_);
TM__nIinruGrC8EPIfjL3PuTvA_0[18].name = "kind";
TM__nIinruGrC8EPIfjL3PuTvA_2_7[3] = &TM__nIinruGrC8EPIfjL3PuTvA_0[32];
NTIjsonerror__G9cw5MrJXJrcpID5JXaplew_.size = sizeof(tyEnum_JsonError__G9cw5MrJXJrcpID5JXaplew);
NTIjsonerror__G9cw5MrJXJrcpID5JXaplew_.align = NIM_ALIGNOF(tyEnum_JsonError__G9cw5MrJXJrcpID5JXaplew);
NTIjsonerror__G9cw5MrJXJrcpID5JXaplew_.kind = 14;
NTIjsonerror__G9cw5MrJXJrcpID5JXaplew_.base = 0;
NTIjsonerror__G9cw5MrJXJrcpID5JXaplew_.flags = 3;
for (TM__nIinruGrC8EPIfjL3PuTvA_11 = 0; TM__nIinruGrC8EPIfjL3PuTvA_11 < 11; TM__nIinruGrC8EPIfjL3PuTvA_11++) {
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_11+33].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_11+33].offset = TM__nIinruGrC8EPIfjL3PuTvA_11;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_11+33].name = TM__nIinruGrC8EPIfjL3PuTvA_10[TM__nIinruGrC8EPIfjL3PuTvA_11];
TM__nIinruGrC8EPIfjL3PuTvA_9_11[TM__nIinruGrC8EPIfjL3PuTvA_11] = &TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_11+33];
}
TM__nIinruGrC8EPIfjL3PuTvA_0[44].len = 11; TM__nIinruGrC8EPIfjL3PuTvA_0[44].kind = 2; TM__nIinruGrC8EPIfjL3PuTvA_0[44].sons = &TM__nIinruGrC8EPIfjL3PuTvA_9_11[0];
NTIjsonerror__G9cw5MrJXJrcpID5JXaplew_.node = &TM__nIinruGrC8EPIfjL3PuTvA_0[44];
TM__nIinruGrC8EPIfjL3PuTvA_0[32].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[32].offset = offsetof(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ, err);
TM__nIinruGrC8EPIfjL3PuTvA_0[32].typ = (&NTIjsonerror__G9cw5MrJXJrcpID5JXaplew_);
TM__nIinruGrC8EPIfjL3PuTvA_0[32].name = "err";
TM__nIinruGrC8EPIfjL3PuTvA_2_7[4] = &TM__nIinruGrC8EPIfjL3PuTvA_0[45];
NTIparserstate__Na0rM2Zdr3RpxeNeXbvLrQ_.size = sizeof(tyEnum_ParserState__Na0rM2Zdr3RpxeNeXbvLrQ);
NTIparserstate__Na0rM2Zdr3RpxeNeXbvLrQ_.align = NIM_ALIGNOF(tyEnum_ParserState__Na0rM2Zdr3RpxeNeXbvLrQ);
NTIparserstate__Na0rM2Zdr3RpxeNeXbvLrQ_.kind = 14;
NTIparserstate__Na0rM2Zdr3RpxeNeXbvLrQ_.base = 0;
NTIparserstate__Na0rM2Zdr3RpxeNeXbvLrQ_.flags = 3;
for (TM__nIinruGrC8EPIfjL3PuTvA_14 = 0; TM__nIinruGrC8EPIfjL3PuTvA_14 < 8; TM__nIinruGrC8EPIfjL3PuTvA_14++) {
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_14+46].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_14+46].offset = TM__nIinruGrC8EPIfjL3PuTvA_14;
TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_14+46].name = TM__nIinruGrC8EPIfjL3PuTvA_13[TM__nIinruGrC8EPIfjL3PuTvA_14];
TM__nIinruGrC8EPIfjL3PuTvA_12_8[TM__nIinruGrC8EPIfjL3PuTvA_14] = &TM__nIinruGrC8EPIfjL3PuTvA_0[TM__nIinruGrC8EPIfjL3PuTvA_14+46];
}
TM__nIinruGrC8EPIfjL3PuTvA_0[54].len = 8; TM__nIinruGrC8EPIfjL3PuTvA_0[54].kind = 2; TM__nIinruGrC8EPIfjL3PuTvA_0[54].sons = &TM__nIinruGrC8EPIfjL3PuTvA_12_8[0];
NTIparserstate__Na0rM2Zdr3RpxeNeXbvLrQ_.node = &TM__nIinruGrC8EPIfjL3PuTvA_0[54];
NTIseqLparserstateT__Ih0V9cYug0VPJyBBGvgEH7Q_.size = sizeof(tySequence__Ih0V9cYug0VPJyBBGvgEH7Q*);
NTIseqLparserstateT__Ih0V9cYug0VPJyBBGvgEH7Q_.align = NIM_ALIGNOF(tySequence__Ih0V9cYug0VPJyBBGvgEH7Q*);
NTIseqLparserstateT__Ih0V9cYug0VPJyBBGvgEH7Q_.kind = 24;
NTIseqLparserstateT__Ih0V9cYug0VPJyBBGvgEH7Q_.base = (&NTIparserstate__Na0rM2Zdr3RpxeNeXbvLrQ_);
NTIseqLparserstateT__Ih0V9cYug0VPJyBBGvgEH7Q_.marker = Marker_tySequence__Ih0V9cYug0VPJyBBGvgEH7Q;
TM__nIinruGrC8EPIfjL3PuTvA_0[45].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[45].offset = offsetof(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ, state);
TM__nIinruGrC8EPIfjL3PuTvA_0[45].typ = (&NTIseqLparserstateT__Ih0V9cYug0VPJyBBGvgEH7Q_);
TM__nIinruGrC8EPIfjL3PuTvA_0[45].name = "state";
TM__nIinruGrC8EPIfjL3PuTvA_2_7[5] = &TM__nIinruGrC8EPIfjL3PuTvA_0[55];
TM__nIinruGrC8EPIfjL3PuTvA_0[55].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[55].offset = offsetof(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ, filename);
TM__nIinruGrC8EPIfjL3PuTvA_0[55].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__nIinruGrC8EPIfjL3PuTvA_0[55].name = "filename";
TM__nIinruGrC8EPIfjL3PuTvA_2_7[6] = &TM__nIinruGrC8EPIfjL3PuTvA_0[56];
TM__nIinruGrC8EPIfjL3PuTvA_0[56].kind = 1;
TM__nIinruGrC8EPIfjL3PuTvA_0[56].offset = offsetof(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ, rawStringLiterals);
TM__nIinruGrC8EPIfjL3PuTvA_0[56].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__nIinruGrC8EPIfjL3PuTvA_0[56].name = "rawStringLiterals";
TM__nIinruGrC8EPIfjL3PuTvA_0[0].len = 7; TM__nIinruGrC8EPIfjL3PuTvA_0[0].kind = 2; TM__nIinruGrC8EPIfjL3PuTvA_0[0].sons = &TM__nIinruGrC8EPIfjL3PuTvA_2_7[0];
NTIjsonparser__KWIQnzXEOUqdWsnCUL9atyQ_.node = &TM__nIinruGrC8EPIfjL3PuTvA_0[0];
NTIjsonparsingerror__XTejXaID1NT7KS9byQm3Jxg_.size = sizeof(tyObject_JsonParsingError__XTejXaID1NT7KS9byQm3Jxg);
NTIjsonparsingerror__XTejXaID1NT7KS9byQm3Jxg_.align = NIM_ALIGNOF(tyObject_JsonParsingError__XTejXaID1NT7KS9byQm3Jxg);
NTIjsonparsingerror__XTejXaID1NT7KS9byQm3Jxg_.kind = 17;
NTIjsonparsingerror__XTejXaID1NT7KS9byQm3Jxg_.base = (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_);
TM__nIinruGrC8EPIfjL3PuTvA_0[57].len = 0; TM__nIinruGrC8EPIfjL3PuTvA_0[57].kind = 2;
NTIjsonparsingerror__XTejXaID1NT7KS9byQm3Jxg_.node = &TM__nIinruGrC8EPIfjL3PuTvA_0[57];
NTIrefjsonparsingerror__PyuSdojUZWOAnzN7dInq1Q_.size = sizeof(tyObject_JsonParsingError__XTejXaID1NT7KS9byQm3Jxg*);
NTIrefjsonparsingerror__PyuSdojUZWOAnzN7dInq1Q_.align = NIM_ALIGNOF(tyObject_JsonParsingError__XTejXaID1NT7KS9byQm3Jxg*);
NTIrefjsonparsingerror__PyuSdojUZWOAnzN7dInq1Q_.kind = 22;
NTIrefjsonparsingerror__PyuSdojUZWOAnzN7dInq1Q_.base = (&NTIjsonparsingerror__XTejXaID1NT7KS9byQm3Jxg_);
NTIrefjsonparsingerror__PyuSdojUZWOAnzN7dInq1Q_.marker = Marker_tyRef__PyuSdojUZWOAnzN7dInq1Q;
}

