/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA;
typedef struct tyObject_Table__XXJncbsdsiyd9bMMxnjd9bLQ tyObject_Table__XXJncbsdsiyd9bMMxnjd9bLQ;
typedef struct tySequence__V8S0OuZvBGWe7eu6xfSNnA tySequence__V8S0OuZvBGWe7eu6xfSNnA;
typedef struct tyObject_Table__ZCml3pTinBhuzdz9cpDAlEQ tyObject_Table__ZCml3pTinBhuzdz9cpDAlEQ;
typedef struct tySequence__F5atQpvvwSviKdnmy3vGJQ tySequence__F5atQpvvwSviKdnmy3vGJQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple__FPQKOEgl1j9bR6yoK9cLiDOg tyTuple__FPQKOEgl1j9bR6yoK9cLiDOg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_MathCustomFun__w1UOSBcoG3QYUCc0FBDjjA tyObject_MathCustomFun__w1UOSBcoG3QYUCc0FBDjjA;
typedef struct tySequence__Zj5xKXgsXnI4n4hPS6nACA tySequence__Zj5xKXgsXnI4n4hPS6nACA;
typedef struct tyTuple__JfHvHzMrhKkWAUvQKe0i1A tyTuple__JfHvHzMrhKkWAUvQKe0i1A;
typedef struct tyObject_Env_mathexprdotnim_mathexpr___diB2NTuAIWY0FO9c5IUJRGg tyObject_Env_mathexprdotnim_mathexpr___diB2NTuAIWY0FO9c5IUJRGg;
typedef struct tyTuple__wytEHNBmW9b2ZZbxWUcxlyQ tyTuple__wytEHNBmW9b2ZZbxWUcxlyQ;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct tyObject_Table__XXJncbsdsiyd9bMMxnjd9bLQ {
tySequence__V8S0OuZvBGWe7eu6xfSNnA* data;
NI counter;
};
struct tyObject_Table__ZCml3pTinBhuzdz9cpDAlEQ {
tySequence__F5atQpvvwSviKdnmy3vGJQ* data;
NI counter;
};
struct tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA {
tyObject_Table__XXJncbsdsiyd9bMMxnjd9bLQ funcs;
tyObject_Table__ZCml3pTinBhuzdz9cpDAlEQ vars;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(NF, ClP_0) (tySequence__Zj5xKXgsXnI4n4hPS6nACA* args, void* ClE_0);
void* ClE_0;
} tyProc__MUgIlUB9cCKG2vJ1LwWGGzg;
struct tyObject_MathCustomFun__w1UOSBcoG3QYUCc0FBDjjA {
NI argCount;
tyProc__MUgIlUB9cCKG2vJ1LwWGGzg fun;
};
struct tyTuple__FPQKOEgl1j9bR6yoK9cLiDOg {
NI Field0;
NimStringDesc* Field1;
tyObject_MathCustomFun__w1UOSBcoG3QYUCc0FBDjjA Field2;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyTuple__JfHvHzMrhKkWAUvQKe0i1A {
void* Field0;
tyObject_Env_mathexprdotnim_mathexpr___diB2NTuAIWY0FO9c5IUJRGg* Field1;
};
struct tyTuple__wytEHNBmW9b2ZZbxWUcxlyQ {
NI Field0;
NimStringDesc* Field1;
NF Field2;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg {
tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA* eval;
NimStringDesc* input;
NI len;
NIM_CHAR ch;
NI pos;
};
typedef N_CLOSURE_PTR(NF, TM__Am39cESEeY2Yo6CaAQQLJXg_24) (tySequence__Zj5xKXgsXnI4n4hPS6nACA* args);
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__V8S0OuZvBGWe7eu6xfSNnA {
  TGenericSeq Sup;
  tyTuple__FPQKOEgl1j9bR6yoK9cLiDOg data[SEQ_DECL_SIZE];
};
struct tySequence__F5atQpvvwSviKdnmy3vGJQ {
  TGenericSeq Sup;
  tyTuple__wytEHNBmW9b2ZZbxWUcxlyQ data[SEQ_DECL_SIZE];
};
struct tySequence__Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence__V8S0OuZvBGWe7eu6xfSNnA)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__F5atQpvvwSviKdnmy3vGJQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__asXiMHDDHRpDV2IgI9c6obg)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, decRef__system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5305)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5311)(void* usr);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NF, parse__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1032)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr);
N_LIB_PRIVATE N_NIMCALL(NF, parseExpression__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_63)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr);
N_LIB_PRIVATE N_NIMCALL(NF, parseRelative__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1017)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr);
N_LIB_PRIVATE N_NIMCALL(NF, parseAddition__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1006)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr);
N_LIB_PRIVATE N_NIMCALL(NF, parseTerm__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_999)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr);
N_LIB_PRIVATE N_NIMCALL(NF, parsePow__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_167)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr);
N_LIB_PRIVATE N_NIMCALL(NF, parseFactor__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_65)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eat__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_56)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr, NIM_CHAR toEat);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, incPos__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_40)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr, NI addPos);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, atEnd__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_37)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr);
static N_INLINE(NI, skipWhitespace__pureZparseutils_105)(NimStringDesc* s, NI start);
N_LIB_PRIVATE N_NIMCALL(void, expectedParen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_67)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NI, parseIdent__pureZparseutils_57)(NimStringDesc* s, NimStringDesc** ident, NI start);
static N_INLINE(NI, rawGet__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_183)(tyObject_Table__ZCml3pTinBhuzdz9cpDAlEQ t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_279)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_31)(NI hcode);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
static N_INLINE(NI, nextTry__pureZcollectionsZtables_34)(NI h, NI maxHash);
static N_INLINE(NI, rawGet__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_484)(tyObject_Table__XXJncbsdsiyd9bMMxnjd9bLQ t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(tySequence__Zj5xKXgsXnI4n4hPS6nACA*, getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr, NIM_BOOL zeroArg);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
static N_NIMCALL(void, Marker_tySequence__Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112)(NI expected, NI actual, NimStringDesc* funcName);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__pureZstrformat_162)(NimStringDesc** result, NimStringDesc* value, NimStringDesc* specifier);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_119)(NimStringDesc** result, NI value, NimStringDesc* specifier);
N_LIB_PRIVATE N_NIMCALL(NI, hashString)(NimStringDesc* s);
static N_INLINE(NF, abs__pureZmath_148)(NF x);
static N_INLINE(NF, radToDeg__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_827)(NF d);
static N_INLINE(NI, sgn__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_839)(NF x);
N_LIB_PRIVATE N_NIMCALL(NF, sum__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_857)(NF* x, NI xLen_0);
N_LIB_PRIVATE N_NIMCALL(NI, fac__pureZmath_41)(NI n);
N_LIB_PRIVATE N_NIMCALL(NF, max__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_907)(NF* x, NI xLen_0);
N_LIB_PRIVATE N_NIMCALL(NF, min__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_923)(NF* x, NI xLen_0);
N_LIB_PRIVATE N_NIMCALL(NI, binom__pureZmath_27)(NI n, NI k);
static N_INLINE(NF, degToRad__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_947)(NF d);
N_LIB_PRIVATE N_NIMCALL(void, unknownIdent__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_79)(NimStringDesc* funcName);
N_LIB_PRIVATE N_NIMCALL(NI, npuParseFloat)(NimStringDesc* s, NF* number, NI start);
N_LIB_PRIVATE N_NIMCALL(void, unexpectedChar__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_83)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nextOp__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_48)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw opList);
static N_INLINE(void, stareq___pureZstrutils_2156)(NF* x, NF y);
static N_INLINE(void, slasheq___system_7440)(NF* x, NF y);
static N_INLINE(void, pluseq___pureZstrutils_2160)(NF* x, NF y);
static N_INLINE(void, minuseq___OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1013)(NF* x, NF y);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, tildeeq___OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1021)(NF a, NF b);
N_LIB_PRIVATE TNimType NTIevaluator58objecttype__bDt7DiS4ttz1qz9cDLb2ogA_;
N_LIB_PRIVATE TNimType NTItable__XXJncbsdsiyd9bMMxnjd9bLQ_;
N_LIB_PRIVATE TNimType NTIkeyvaluepair__FPQKOEgl1j9bR6yoK9cLiDOg_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTImathcustomfun__w1UOSBcoG3QYUCc0FBDjjA_;
N_LIB_PRIVATE TNimType NTImathfunction__MUgIlUB9cCKG2vJ1LwWGGzg_;
extern TNimType NTIpointer__vr5DoT1jILTGdRlYv1OYpw_;
extern TNimType NTIrefobject__HsJiUUcO9cHBdUCi0HwkSTA_;
N_LIB_PRIVATE TNimType NTIkeyvaluepairseq__V8S0OuZvBGWe7eu6xfSNnA_;
N_LIB_PRIVATE TNimType NTItable__ZCml3pTinBhuzdz9cpDAlEQ_;
N_LIB_PRIVATE TNimType NTIkeyvaluepair__wytEHNBmW9b2ZZbxWUcxlyQ_;
extern TNimType NTIfloat__w9bl9a1ul9ctRJWiMl9cNnIMvg_;
N_LIB_PRIVATE TNimType NTIkeyvaluepairseq__F5atQpvvwSviKdnmy3vGJQ_;
N_LIB_PRIVATE TNimType NTIevaluator__asXiMHDDHRpDV2IgI9c6obg_;
extern TNimType NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_;
extern TNimType NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_;
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_9, "The line is empty!", 18);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_14, "Expected `)`, found `", 21);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_15, "`", 1);
N_LIB_PRIVATE TNimType NTIseqLfloatT__Zj5xKXgsXnI4n4hPS6nACA_;
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_19, "Expected at least one argument for \'", 36);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_20, "\', got 0", 8);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_21, "Expected ", 9);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_22, " arguments for \'", 16);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_23, "\', got ", 7);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_25, "pi", 2);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_26, "tau", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_27, "e", 1);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_28, "abs", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_29, "acos", 4);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_30, "arccos", 6);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_31, "asin", 4);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_32, "arcsin", 6);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_33, "atan", 4);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_34, "arctan", 6);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_35, "arctg", 5);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_36, "atan2", 5);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_37, "arctan2", 7);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_38, "ceil", 4);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_39, "cos", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_40, "cosh", 4);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_41, "deg", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_42, "exp", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_43, "sgn", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_44, "sqrt", 4);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_45, "sum", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_46, "fac", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_47, "floor", 5);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_48, "ln", 2);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_49, "log", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_50, "log10", 5);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_51, "log2", 4);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_52, "max", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_53, "min", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_54, "ncr", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_55, "binom", 5);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_56, "npr", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_57, "rad", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_58, "pow", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_59, "sin", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_60, "sinh", 4);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_61, "tg", 2);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_62, "tan", 3);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_63, "tanh", 4);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_65, "Ident `", 7);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_66, "` is not defined", 16);
STRING_LITERAL(TM__Am39cESEeY2Yo6CaAQQLJXg_67, "Unexpected character `", 22);
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__Am39cESEeY2Yo6CaAQQLJXg_68 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__Am39cESEeY2Yo6CaAQQLJXg_69 = {
0x00, 0x00, 0x00, 0x00, 0x20, 0x84, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__Am39cESEeY2Yo6CaAQQLJXg_70 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x28, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__Am39cESEeY2Yo6CaAQQLJXg_71 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x50,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__Am39cESEeY2Yo6CaAQQLJXg_72 = {
0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x20,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5258;
static N_NIMCALL(void, Marker_tySequence__V8S0OuZvBGWe7eu6xfSNnA)(void* p, NI op) {
	tySequence__V8S0OuZvBGWe7eu6xfSNnA* a;
	NI T1_;
	a = (tySequence__V8S0OuZvBGWe7eu6xfSNnA*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	nimGCvisit((void*)a->data[T1_].Field2.fun.ClE_0, op);
	}
}
static N_NIMCALL(void, Marker_tySequence__F5atQpvvwSviKdnmy3vGJQ)(void* p, NI op) {
	tySequence__F5atQpvvwSviKdnmy3vGJQ* a;
	NI T1_;
	a = (tySequence__F5atQpvvwSviKdnmy3vGJQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	}
}
static N_NIMCALL(void, Marker_tyRef__asXiMHDDHRpDV2IgI9c6obg)(void* p, NI op) {
	tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA* a;
	a = (tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA*)p;
	nimGCvisit((void*)(*a).funcs.data, op);
	nimGCvisit((void*)(*a).vars.data, op);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA*, newEvaluator__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1035)(void) {
	tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA* result;
	tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA*) newObj((&NTIevaluator__asXiMHDDHRpDV2IgI9c6obg_), sizeof(tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA));
	result = T1_;
	return result;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU32)(((NU) (x))) < (NU32)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5305((&gch__system_5258.zct), c);
}
static N_INLINE(void, decRef__system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5354(c);
	}
	LA4_: ;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5311)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 8));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5311(p);
	decRef__system_5356(T1_);
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5311(src);
		incRef__system_5349(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5311((*dest));
		decRef__system_5356(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, atEnd__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_37)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((*expr).len <= (*expr).pos);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, incPos__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_40)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr, NI addPos) {
	NIM_CHAR result;
	NI TM__Am39cESEeY2Yo6CaAQQLJXg_10;
	result = (NIM_CHAR)0;
	if (nimAddInt((*expr).pos, addPos, &TM__Am39cESEeY2Yo6CaAQQLJXg_10)) { raiseOverflow(); };
	(*expr).pos = (NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_10);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = atEnd__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_37(expr);
		if (!T3_) goto LA4_;
		(*expr).ch = 0;
	}
	goto LA1_;
	LA4_: ;
	{
		if ((*expr).pos < 0 || (*expr).pos >= ((*expr).input ? (*expr).input->Sup.len : 0)){ raiseIndexError2((*expr).pos,((*expr).input ? (*expr).input->Sup.len : 0)-1); }
		(*expr).ch = (*expr).input->data[(*expr).pos];
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, skipWhitespace__pureZparseutils_105)(NimStringDesc* s, NI start) {
	NI result;
	result = (NI)0;
	result = ((NI) 0);
	{
		while (1) {
			NIM_BOOL T3_;
			NI TM__Am39cESEeY2Yo6CaAQQLJXg_11;
			NI TM__Am39cESEeY2Yo6CaAQQLJXg_12;
			NI TM__Am39cESEeY2Yo6CaAQQLJXg_13;
			T3_ = (NIM_BOOL)0;
			if (nimAddInt(start, result, &TM__Am39cESEeY2Yo6CaAQQLJXg_11)) { raiseOverflow(); };
			T3_ = ((NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_11) < (s ? s->Sup.len : 0));
			if (!(T3_)) goto LA4_;
			if (nimAddInt(start, result, &TM__Am39cESEeY2Yo6CaAQQLJXg_12)) { raiseOverflow(); };
			if ((NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_12) < 0 || (NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_12) >= (s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_12),(s ? s->Sup.len : 0)-1); }
			T3_ = (((NU8)(s->data[(NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_12)])) == ((NU8)(32)) || ((NU8)(s->data[(NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_12)])) == ((NU8)(9)) || ((NU8)(s->data[(NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_12)])) == ((NU8)(11)) || ((NU8)(s->data[(NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_12)])) == ((NU8)(13)) || ((NU8)(s->data[(NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_12)])) == ((NU8)(10)) || ((NU8)(s->data[(NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_12)])) == ((NU8)(12)));
			LA4_: ;
			if (!T3_) goto LA2;
			if (nimAddInt(result, ((NI) 1), &TM__Am39cESEeY2Yo6CaAQQLJXg_13)) { raiseOverflow(); };
			result = (NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_13);
		} LA2: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eat__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_56)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr, NIM_CHAR toEat) {
	NIM_BOOL result;
	NI T1_;
	NIM_CHAR T2_;
	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = skipWhitespace__pureZparseutils_105((*expr).input, (*expr).pos);
	T2_ = (NIM_CHAR)0;
	T2_ = incPos__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_40(expr, T1_);
	{
		NIM_CHAR T7_;
		if (!((NU8)((*expr).ch) == (NU8)(toEat))) goto LA5_;
		T7_ = (NIM_CHAR)0;
		T7_ = incPos__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_40(expr, ((NI) 1));
		result = NIM_TRUE;
	}
	goto LA3_;
	LA5_: ;
	{
		result = NIM_FALSE;
	}
	LA3_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, expectedParen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_67)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr) {
	tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T1_;
	NimStringDesc* fmtRes;
	NimStringDesc* T2_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_);
	(*T1_).Sup.Sup.name = "ValueError";
	fmtRes = rawNewString(((NI) 41));
	fmtRes = resizeString(fmtRes, 21);
appendString(fmtRes, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_14));
	fmtRes = addChar(fmtRes, (*expr).ch);
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_15));
	T2_ = NIM_NIL;
	T2_ = (*T1_).Sup.Sup.message; (*T1_).Sup.Sup.message = copyStringRC1(fmtRes);
	if (T2_) nimGCunrefNoCycle(T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "ValueError", "expectedParen", "mathexpr.nim", 159);
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_31)(NI hcode) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((hcode == ((NI) 0)));
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	alen = (a ? a->Sup.len : 0);
	blen = (b ? b->Sup.len : 0);
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		result = equalMem__system_1735(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZtables_34)(NI h, NI maxHash) {
	NI result;
	NI TM__Am39cESEeY2Yo6CaAQQLJXg_16;
	result = (NI)0;
	if (nimAddInt(h, ((NI) 1), &TM__Am39cESEeY2Yo6CaAQQLJXg_16)) { raiseOverflow(); };
	result = (NI)((NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_16) & maxHash);
	return result;
}
static N_INLINE(NI, rawGet__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_183)(tyObject_Table__ZCml3pTinBhuzdz9cpDAlEQ t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T10_;
	NI TM__Am39cESEeY2Yo6CaAQQLJXg_17;
{	result = (NI)0;
	(*hc) = hash__pureZhashes_279(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	{
		NI T7_;
		T7_ = (t.data ? t.data->Sup.len : 0);
		if (!(T7_ == ((NI) 0))) goto LA8_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA8_: ;
	T10_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)((*hc) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			if (h < 0 || h >= (t.data ? t.data->Sup.len : 0)){ raiseIndexError2(h,(t.data ? t.data->Sup.len : 0)-1); }
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				if (h < 0 || h >= (t.data ? t.data->Sup.len : 0)){ raiseIndexError2(h,(t.data ? t.data->Sup.len : 0)-1); }
				T16_ = (t.data->data[h].Field0 == (*hc));
				if (!(T16_)) goto LA17_;
				if (h < 0 || h >= (t.data ? t.data->Sup.len : 0)){ raiseIndexError2(h,(t.data ? t.data->Sup.len : 0)-1); }
				T16_ = eqStrings(t.data->data[h].Field1, key);
				LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
			LA18_: ;
			T20_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T20_);
		} LA12: ;
	}
	if (nimSubInt(((NI) -1), h, &TM__Am39cESEeY2Yo6CaAQQLJXg_17)) { raiseOverflow(); };
	result = (NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_17);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, rawGet__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_484)(tyObject_Table__XXJncbsdsiyd9bMMxnjd9bLQ t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T10_;
	NI TM__Am39cESEeY2Yo6CaAQQLJXg_18;
{	result = (NI)0;
	(*hc) = hash__pureZhashes_279(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	{
		NI T7_;
		T7_ = (t.data ? t.data->Sup.len : 0);
		if (!(T7_ == ((NI) 0))) goto LA8_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA8_: ;
	T10_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)((*hc) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			if (h < 0 || h >= (t.data ? t.data->Sup.len : 0)){ raiseIndexError2(h,(t.data ? t.data->Sup.len : 0)-1); }
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				if (h < 0 || h >= (t.data ? t.data->Sup.len : 0)){ raiseIndexError2(h,(t.data ? t.data->Sup.len : 0)-1); }
				T16_ = (t.data->data[h].Field0 == (*hc));
				if (!(T16_)) goto LA17_;
				if (h < 0 || h >= (t.data ? t.data->Sup.len : 0)){ raiseIndexError2(h,(t.data ? t.data->Sup.len : 0)-1); }
				T16_ = eqStrings(t.data->data[h].Field1, key);
				LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
			LA18_: ;
			T20_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T20_);
		} LA12: ;
	}
	if (nimSubInt(((NI) -1), h, &TM__Am39cESEeY2Yo6CaAQQLJXg_18)) { raiseOverflow(); };
	result = (NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_18);
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, Marker_tySequence__Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op) {
	tySequence__Zj5xKXgsXnI4n4hPS6nACA* a;
	NI T1_;
	a = (tySequence__Zj5xKXgsXnI4n4hPS6nACA*)p;
	T1_ = (NI)0;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__Zj5xKXgsXnI4n4hPS6nACA*, getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr, NIM_BOOL zeroArg) {
	tySequence__Zj5xKXgsXnI4n4hPS6nACA* result;
{	result = NIM_NIL;
	result = NIM_NIL;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eat__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_56(expr, 40);
		if (!T3_) goto LA4_;
		{
			NIM_BOOL T8_;
			T8_ = (NIM_BOOL)0;
			T8_ = eat__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_56(expr, 41);
			if (!T8_) goto LA9_;
			goto BeforeRet_;
		}
		LA9_: ;
		{
			while (1) {
				NF T13_;
				NI T14_;
				if (!!(((NU8)((*expr).ch) == (NU8)(41)))) goto LA12;
				T13_ = (NF)0;
				T13_ = parseExpression__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_63(expr);
				result = (tySequence__Zj5xKXgsXnI4n4hPS6nACA*) incrSeqV3((TGenericSeq*)(result), (&NTIseqLfloatT__Zj5xKXgsXnI4n4hPS6nACA_));
				T14_ = result->Sup.len++;
				result->data[T14_] = T13_;
				{
					NIM_CHAR T19_;
					if (!((NU8)((*expr).ch) == (NU8)(44))) goto LA17_;
					T19_ = (NIM_CHAR)0;
					T19_ = incPos__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_40(expr, ((NI) 1));
				}
				LA17_: ;
			} LA12: ;
		}
		{
			NIM_BOOL T22_;
			T22_ = (NIM_BOOL)0;
			T22_ = eat__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_56(expr, 41);
			if (!!(T22_)) goto LA23_;
			expectedParen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_67(expr);
		}
		LA23_: ;
	}
	goto LA1_;
	LA4_: ;
	{
		NF T26_;
		NI T27_;
		T26_ = (NF)0;
		T26_ = parseFactor__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_65(expr);
		result = (tySequence__Zj5xKXgsXnI4n4hPS6nACA*) incrSeqV3((TGenericSeq*)(result), (&NTIseqLfloatT__Zj5xKXgsXnI4n4hPS6nACA_));
		T27_ = result->Sup.len++;
		result->data[T27_] = T26_;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112)(NI expected, NI actual, NimStringDesc* funcName) {
	{
		NIM_BOOL T3_;
		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T7_;
		NimStringDesc* fmtRes;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = (expected == ((NI) -1));
		if (!(T3_)) goto LA4_;
		T3_ = (actual < ((NI) 1));
		LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_);
		(*T7_).Sup.Sup.name = "ValueError";
		fmtRes = rawNewString(((NI) 64));
		fmtRes = resizeString(fmtRes, 36);
appendString(fmtRes, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_19));
		formatValue__pureZstrformat_162((&fmtRes), funcName, ((NimStringDesc*) NIM_NIL));
		fmtRes = resizeString(fmtRes, 8);
appendString(fmtRes, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_20));
		T8_ = NIM_NIL;
		T8_ = (*T7_).Sup.Sup.message; (*T7_).Sup.Sup.message = copyStringRC1(fmtRes);
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*T7_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T7_, "ValueError", "checkArgLen", "mathexpr.nim", 188);
	}
	goto LA1_;
	LA5_: ;
	{
		NIM_BOOL T10_;
		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T14_;
		NimStringDesc* fmtRes_2;
		NimStringDesc* T15_;
		T10_ = (NIM_BOOL)0;
		T10_ = !((expected == ((NI) -1)));
		if (!(T10_)) goto LA11_;
		T10_ = !((actual == expected));
		LA11_: ;
		if (!T10_) goto LA12_;
		T14_ = NIM_NIL;
		T14_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
		(*T14_).Sup.Sup.Sup.m_type = (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_);
		(*T14_).Sup.Sup.name = "ValueError";
		fmtRes_2 = rawNewString(((NI) 90));
		fmtRes_2 = resizeString(fmtRes_2, 9);
appendString(fmtRes_2, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_21));
		formatValue__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_119((&fmtRes_2), expected, ((NimStringDesc*) NIM_NIL));
		fmtRes_2 = resizeString(fmtRes_2, 16);
appendString(fmtRes_2, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_22));
		formatValue__pureZstrformat_162((&fmtRes_2), funcName, ((NimStringDesc*) NIM_NIL));
		fmtRes_2 = resizeString(fmtRes_2, 7);
appendString(fmtRes_2, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_23));
		formatValue__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_119((&fmtRes_2), actual, ((NimStringDesc*) NIM_NIL));
		T15_ = NIM_NIL;
		T15_ = (*T14_).Sup.Sup.message; (*T14_).Sup.Sup.message = copyStringRC1(fmtRes_2);
		if (T15_) nimGCunrefNoCycle(T15_);
		asgnRef((void**) (&(*T14_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T14_, "ValueError", "checkArgLen", "mathexpr.nim", 192);
	}
	goto LA1_;
	LA12_: ;
	LA1_: ;
}
static N_INLINE(NF, abs__pureZmath_148)(NF x) {
	NF result;
	result = (NF)0;
	result = fabs(x);
	return result;
}
static N_INLINE(NF, radToDeg__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_827)(NF d) {
	NF result;
	result = (NF)0;
	result = ((NF)(d) / (NF)(0.017453292519943295));
	return result;
}
static N_INLINE(NI, sgn__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_839)(NF x) {
	NI result;
	result = (NI)0;
	result = (NI)((0.0 < x) - (x < 0.0));
	return result;
}
static N_INLINE(NF, degToRad__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_947)(NF d) {
	NF result;
	result = (NF)0;
	result = ((NF)(d) * (NF)(0.017453292519943295));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, unknownIdent__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_79)(NimStringDesc* funcName) {
	tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T1_;
	NimStringDesc* fmtRes;
	NimStringDesc* T2_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_);
	(*T1_).Sup.Sup.name = "ValueError";
	fmtRes = rawNewString(((NI) 43));
	fmtRes = resizeString(fmtRes, 7);
appendString(fmtRes, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_65));
	formatValue__pureZstrformat_162((&fmtRes), funcName, ((NimStringDesc*) NIM_NIL));
	fmtRes = resizeString(fmtRes, 16);
appendString(fmtRes, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_66));
	T2_ = NIM_NIL;
	T2_ = (*T1_).Sup.Sup.message; (*T1_).Sup.Sup.message = copyStringRC1(fmtRes);
	if (T2_) nimGCunrefNoCycle(T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "ValueError", "unknownIdent", "mathexpr.nim", 162);
}
N_LIB_PRIVATE N_NIMCALL(void, unexpectedChar__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_83)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr) {
	tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T1_;
	NimStringDesc* fmtRes;
	NimStringDesc* T2_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_);
	(*T1_).Sup.Sup.name = "ValueError";
	fmtRes = rawNewString(((NI) 42));
	fmtRes = resizeString(fmtRes, 22);
appendString(fmtRes, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_67));
	fmtRes = addChar(fmtRes, (*expr).ch);
	fmtRes = resizeString(fmtRes, 1);
appendString(fmtRes, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_15));
	T2_ = NIM_NIL;
	T2_ = (*T1_).Sup.Sup.message; (*T1_).Sup.Sup.message = copyStringRC1(fmtRes);
	if (T2_) nimGCunrefNoCycle(T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "ValueError", "unexpectedChar", "mathexpr.nim", 165);
}
N_LIB_PRIVATE N_NIMCALL(NF, parseFactor__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_65)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr) {
	NF result;
{	result = (NF)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eat__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_56(expr, 43);
		if (!T3_) goto LA4_;
		result = parsePow__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_167(expr);
		goto BeforeRet_;
	}
	goto LA1_;
	LA4_: ;
	{
		NIM_BOOL T7_;
		NF T10_;
		T7_ = (NIM_BOOL)0;
		T7_ = eat__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_56(expr, 45);
		if (!T7_) goto LA8_;
		T10_ = (NF)0;
		T10_ = parsePow__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_167(expr);
		result = -(T10_);
		goto BeforeRet_;
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = eat__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_56(expr, 40);
		if (!T13_) goto LA14_;
		result = parseExpression__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_63(expr);
		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = eat__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_56(expr, 41);
			if (!!(T18_)) goto LA19_;
			expectedParen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_67(expr);
		}
		LA19_: ;
	}
	goto LA11_;
	LA14_: ;
	{
		NimStringDesc* funcName;
		NI T24_;
		NIM_CHAR T25_;
		NI hcX60gensym16_;
		NI indexX60gensym16_;
		NIM_BOOL hasKeyX60gensym16_;
		NI hcX60gensym20_;
		NI indexX60gensym20_;
		NIM_BOOL hasKeyX60gensym20_;
		if (!(((NU8)((*expr).ch)) >= ((NU8)(97)) && ((NU8)((*expr).ch)) <= ((NU8)(122)) || ((NU8)((*expr).ch)) >= ((NU8)(65)) && ((NU8)((*expr).ch)) <= ((NU8)(90)) || ((NU8)((*expr).ch)) == ((NU8)(95)))) goto LA22_;
		funcName = NIM_NIL;
		T24_ = (NI)0;
		T24_ = parseIdent__pureZparseutils_57((*expr).input, (&funcName), (*expr).pos);
		T25_ = (NIM_CHAR)0;
		T25_ = incPos__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_40(expr, T24_);
		hcX60gensym16_ = (NI)0;
		indexX60gensym16_ = rawGet__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_183((*(*expr).eval).vars, funcName, (&hcX60gensym16_));
		hasKeyX60gensym16_ = (((NI) 0) <= indexX60gensym16_);
		{
			NF* val;
			if (!hasKeyX60gensym16_) goto LA28_;
			if (indexX60gensym16_ < 0 || indexX60gensym16_ >= ((*(*expr).eval).vars.data ? (*(*expr).eval).vars.data->Sup.len : 0)){ raiseIndexError2(indexX60gensym16_,((*(*expr).eval).vars.data ? (*(*expr).eval).vars.data->Sup.len : 0)-1); }
			val = (&(*(*expr).eval).vars.data->data[indexX60gensym16_].Field2);
			result = (*val);
			goto BeforeRet_;
		}
		LA28_: ;
		hcX60gensym20_ = (NI)0;
		indexX60gensym20_ = rawGet__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_484((*(*expr).eval).funcs, funcName, (&hcX60gensym20_));
		hasKeyX60gensym20_ = (((NI) 0) <= indexX60gensym20_);
		{
			tyObject_MathCustomFun__w1UOSBcoG3QYUCc0FBDjjA* fnc;
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args;
			NI T34_;
			if (!hasKeyX60gensym20_) goto LA32_;
			if (indexX60gensym20_ < 0 || indexX60gensym20_ >= ((*(*expr).eval).funcs.data ? (*(*expr).eval).funcs.data->Sup.len : 0)){ raiseIndexError2(indexX60gensym20_,((*(*expr).eval).funcs.data ? (*(*expr).eval).funcs.data->Sup.len : 0)-1); }
			fnc = (&(*(*expr).eval).funcs.data->data[indexX60gensym20_].Field2);
			args = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T34_ = (args ? args->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112((*fnc).argCount, T34_, funcName);
			result = (*fnc).fun.ClE_0? (*fnc).fun.ClP_0(args, (*fnc).fun.ClE_0):((TM__Am39cESEeY2Yo6CaAQQLJXg_24)((*fnc).fun.ClP_0))(args);
			goto BeforeRet_;
		}
		LA32_: ;
		switch (hashString(funcName) & 63) {
		case 1: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_36))) goto LA42_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_44))) goto LA49_;
break;
		case 2: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_30))) goto LA39_;
break;
		case 3: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_43))) goto LA48_;
break;
		case 4: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_47))) goto LA52_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_52))) goto LA56_;
break;
		case 6: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_26))) goto LA36_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_34))) goto LA41_;
break;
		case 7: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_40))) goto LA45_;
break;
		case 8: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_48))) goto LA53_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_55))) goto LA58_;
break;
		case 14: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_33))) goto LA41_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_45))) goto LA50_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_63))) goto LA65_;
break;
		case 16: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_27))) goto LA37_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_42))) goto LA47_;
break;
		case 21: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_32))) goto LA40_;
break;
		case 23: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_28))) goto LA38_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_57))) goto LA60_;
break;
		case 24: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_59))) goto LA62_;
break;
		case 27: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_35))) goto LA41_;
break;
		case 30: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_62))) goto LA64_;
break;
		case 31: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_38))) goto LA43_;
break;
		case 38: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_60))) goto LA63_;
break;
		case 41: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_39))) goto LA44_;
break;
		case 42: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_50))) goto LA54_;
break;
		case 44: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_46))) goto LA51_;
break;
		case 45: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_25))) goto LA35_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_31))) goto LA40_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_49))) goto LA54_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_61))) goto LA64_;
break;
		case 49: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_56))) goto LA59_;
break;
		case 51: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_53))) goto LA57_;
break;
		case 53: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_37))) goto LA42_;
break;
		case 54: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_29))) goto LA39_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_51))) goto LA55_;
break;
		case 56: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_58))) goto LA61_;
break;
		case 62: 
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_41))) goto LA46_;
if (eqStrings(funcName, ((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_54))) goto LA58_;
break;
		}
		goto LA66_;
		LA35_: ;
		{
			result = 3.141592653589793;
		}
		goto LA67_;
		LA36_: ;
		{
			result = 6.283185307179586;
		}
		goto LA67_;
		LA37_: ;
		{
			result = 2.718281828459045;
		}
		goto LA67_;
		LA38_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_2;
			NI T72_;
			args_2 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T72_ = (args_2 ? args_2->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T72_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_2 ? args_2->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_2 ? args_2->Sup.len : 0)-1); }
			result = abs__pureZmath_148(args_2->data[((NI) 0)]);
		}
		goto LA67_;
		LA39_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_3;
			NI T74_;
			args_3 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T74_ = (args_3 ? args_3->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T74_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_3 ? args_3->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_3 ? args_3->Sup.len : 0)-1); }
			result = acos(args_3->data[((NI) 0)]);
		}
		goto LA67_;
		LA40_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_4;
			NI T76_;
			args_4 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T76_ = (args_4 ? args_4->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T76_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_4 ? args_4->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_4 ? args_4->Sup.len : 0)-1); }
			result = asin(args_4->data[((NI) 0)]);
		}
		goto LA67_;
		LA41_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_5;
			NI T78_;
			args_5 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T78_ = (args_5 ? args_5->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T78_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_5 ? args_5->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_5 ? args_5->Sup.len : 0)-1); }
			result = atan(args_5->data[((NI) 0)]);
		}
		goto LA67_;
		LA42_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_6;
			NI T80_;
			args_6 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T80_ = (args_6 ? args_6->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 2), T80_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_6 ? args_6->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_6 ? args_6->Sup.len : 0)-1); }
			if (((NI) 1) < 0 || ((NI) 1) >= (args_6 ? args_6->Sup.len : 0)){ raiseIndexError2(((NI) 1),(args_6 ? args_6->Sup.len : 0)-1); }
			result = atan2(args_6->data[((NI) 0)], args_6->data[((NI) 1)]);
		}
		goto LA67_;
		LA43_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_7;
			NI T82_;
			args_7 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T82_ = (args_7 ? args_7->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T82_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_7 ? args_7->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_7 ? args_7->Sup.len : 0)-1); }
			result = ceil(args_7->data[((NI) 0)]);
		}
		goto LA67_;
		LA44_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_8;
			NI T84_;
			args_8 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T84_ = (args_8 ? args_8->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T84_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_8 ? args_8->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_8 ? args_8->Sup.len : 0)-1); }
			result = cos(args_8->data[((NI) 0)]);
		}
		goto LA67_;
		LA45_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_9;
			NI T86_;
			args_9 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T86_ = (args_9 ? args_9->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T86_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_9 ? args_9->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_9 ? args_9->Sup.len : 0)-1); }
			result = cosh(args_9->data[((NI) 0)]);
		}
		goto LA67_;
		LA46_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_10;
			NI T88_;
			args_10 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T88_ = (args_10 ? args_10->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T88_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_10 ? args_10->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_10 ? args_10->Sup.len : 0)-1); }
			result = radToDeg__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_827(args_10->data[((NI) 0)]);
		}
		goto LA67_;
		LA47_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_11;
			NI T90_;
			args_11 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T90_ = (args_11 ? args_11->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T90_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_11 ? args_11->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_11 ? args_11->Sup.len : 0)-1); }
			result = exp(args_11->data[((NI) 0)]);
		}
		goto LA67_;
		LA48_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_12;
			NI T92_;
			NI T93_;
			args_12 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T92_ = (args_12 ? args_12->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T92_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_12 ? args_12->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_12 ? args_12->Sup.len : 0)-1); }
			T93_ = (NI)0;
			T93_ = sgn__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_839(args_12->data[((NI) 0)]);
			result = ((NF) (T93_));
		}
		goto LA67_;
		LA49_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_13;
			NI T95_;
			args_13 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T95_ = (args_13 ? args_13->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T95_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_13 ? args_13->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_13 ? args_13->Sup.len : 0)-1); }
			result = sqrt(args_13->data[((NI) 0)]);
		}
		goto LA67_;
		LA50_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_14;
			NI T97_;
			args_14 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T97_ = (args_14 ? args_14->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) -1), T97_, funcName);
			result = sum__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_857((args_14) ? (args_14->data) : NIM_NIL, (args_14 ? args_14->Sup.len : 0));
		}
		goto LA67_;
		LA51_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_15;
			NI T99_;
			NI T100_;
			args_15 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T99_ = (args_15 ? args_15->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T99_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_15 ? args_15->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_15 ? args_15->Sup.len : 0)-1); }
			T100_ = (NI)0;
			T100_ = fac__pureZmath_41(((NI) (args_15->data[((NI) 0)])));
			result = ((NF) (T100_));
		}
		goto LA67_;
		LA52_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_16;
			NI T102_;
			args_16 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T102_ = (args_16 ? args_16->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T102_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_16 ? args_16->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_16 ? args_16->Sup.len : 0)-1); }
			result = floor(args_16->data[((NI) 0)]);
		}
		goto LA67_;
		LA53_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_17;
			NI T104_;
			args_17 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T104_ = (args_17 ? args_17->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T104_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_17 ? args_17->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_17 ? args_17->Sup.len : 0)-1); }
			result = log(args_17->data[((NI) 0)]);
		}
		goto LA67_;
		LA54_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_18;
			NI T106_;
			args_18 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T106_ = (args_18 ? args_18->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T106_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_18 ? args_18->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_18 ? args_18->Sup.len : 0)-1); }
			result = log10(args_18->data[((NI) 0)]);
		}
		goto LA67_;
		LA55_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_19;
			NI T108_;
			args_19 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T108_ = (args_19 ? args_19->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T108_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_19 ? args_19->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_19 ? args_19->Sup.len : 0)-1); }
			result = log2(args_19->data[((NI) 0)]);
		}
		goto LA67_;
		LA56_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_20;
			NI T110_;
			args_20 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T110_ = (args_20 ? args_20->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) -1), T110_, funcName);
			result = max__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_907((args_20) ? (args_20->data) : NIM_NIL, (args_20 ? args_20->Sup.len : 0));
		}
		goto LA67_;
		LA57_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_21;
			NI T112_;
			args_21 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T112_ = (args_21 ? args_21->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) -1), T112_, funcName);
			result = min__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_923((args_21) ? (args_21->data) : NIM_NIL, (args_21 ? args_21->Sup.len : 0));
		}
		goto LA67_;
		LA58_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_22;
			NI T114_;
			NI T115_;
			args_22 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T114_ = (args_22 ? args_22->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 2), T114_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_22 ? args_22->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_22 ? args_22->Sup.len : 0)-1); }
			if (((NI) 1) < 0 || ((NI) 1) >= (args_22 ? args_22->Sup.len : 0)){ raiseIndexError2(((NI) 1),(args_22 ? args_22->Sup.len : 0)-1); }
			T115_ = (NI)0;
			T115_ = binom__pureZmath_27(((NI) (args_22->data[((NI) 0)])), ((NI) (args_22->data[((NI) 1)])));
			result = ((NF) (T115_));
		}
		goto LA67_;
		LA59_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_23;
			NI T117_;
			NI T118_;
			NI T119_;
			NI TM__Am39cESEeY2Yo6CaAQQLJXg_64;
			args_23 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T117_ = (args_23 ? args_23->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 2), T117_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_23 ? args_23->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_23 ? args_23->Sup.len : 0)-1); }
			if (((NI) 1) < 0 || ((NI) 1) >= (args_23 ? args_23->Sup.len : 0)){ raiseIndexError2(((NI) 1),(args_23 ? args_23->Sup.len : 0)-1); }
			T118_ = (NI)0;
			T118_ = binom__pureZmath_27(((NI) (args_23->data[((NI) 0)])), ((NI) (args_23->data[((NI) 1)])));
			if (((NI) 1) < 0 || ((NI) 1) >= (args_23 ? args_23->Sup.len : 0)){ raiseIndexError2(((NI) 1),(args_23 ? args_23->Sup.len : 0)-1); }
			T119_ = (NI)0;
			T119_ = fac__pureZmath_41(((NI) (args_23->data[((NI) 1)])));
			if (nimMulInt(T118_, T119_, &TM__Am39cESEeY2Yo6CaAQQLJXg_64)) { raiseOverflow(); };
			result = ((NF) ((NI)(TM__Am39cESEeY2Yo6CaAQQLJXg_64)));
		}
		goto LA67_;
		LA60_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_24;
			NI T121_;
			args_24 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T121_ = (args_24 ? args_24->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T121_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_24 ? args_24->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_24 ? args_24->Sup.len : 0)-1); }
			result = degToRad__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_947(args_24->data[((NI) 0)]);
		}
		goto LA67_;
		LA61_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_25;
			NI T123_;
			args_25 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T123_ = (args_25 ? args_25->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 2), T123_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_25 ? args_25->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_25 ? args_25->Sup.len : 0)-1); }
			if (((NI) 1) < 0 || ((NI) 1) >= (args_25 ? args_25->Sup.len : 0)){ raiseIndexError2(((NI) 1),(args_25 ? args_25->Sup.len : 0)-1); }
			result = pow(args_25->data[((NI) 0)], args_25->data[((NI) 1)]);
		}
		goto LA67_;
		LA62_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_26;
			NI T125_;
			args_26 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T125_ = (args_26 ? args_26->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T125_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_26 ? args_26->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_26 ? args_26->Sup.len : 0)-1); }
			result = sin(args_26->data[((NI) 0)]);
		}
		goto LA67_;
		LA63_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_27;
			NI T127_;
			args_27 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T127_ = (args_27 ? args_27->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T127_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_27 ? args_27->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_27 ? args_27->Sup.len : 0)-1); }
			result = sinh(args_27->data[((NI) 0)]);
		}
		goto LA67_;
		LA64_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_28;
			NI T129_;
			args_28 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T129_ = (args_28 ? args_28->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T129_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_28 ? args_28->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_28 ? args_28->Sup.len : 0)-1); }
			result = tan(args_28->data[((NI) 0)]);
		}
		goto LA67_;
		LA65_: ;
		{
			tySequence__Zj5xKXgsXnI4n4hPS6nACA* args_29;
			NI T131_;
			args_29 = getArgs__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_87(expr, NIM_TRUE);
			T131_ = (args_29 ? args_29->Sup.len : 0);
			checkArgLen__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_112(((NI) 1), T131_, funcName);
			if (((NI) 0) < 0 || ((NI) 0) >= (args_29 ? args_29->Sup.len : 0)){ raiseIndexError2(((NI) 0),(args_29 ? args_29->Sup.len : 0)-1); }
			result = tanh(args_29->data[((NI) 0)]);
		}
		goto LA67_;
		LA66_: ;
		{
			unknownIdent__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_79(funcName);
			result = NAN;
		}
		LA67_: ;
	}
	goto LA11_;
	LA22_: ;
	{
		NI cnt;
		NIM_CHAR T140_;
		if (!(((NU8)((*expr).ch)) >= ((NU8)(48)) && ((NU8)((*expr).ch)) <= ((NU8)(57)) || ((NU8)((*expr).ch)) == ((NU8)(46)))) goto LA134_;
		cnt = npuParseFloat((*expr).input, (&result), (*expr).pos);
		{
			if (!(cnt == ((NI) 0))) goto LA138_;
			unexpectedChar__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_83(expr);
		}
		LA138_: ;
		T140_ = (NIM_CHAR)0;
		T140_ = incPos__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_40(expr, cnt);
	}
	goto LA11_;
	LA134_: ;
	{
		unexpectedChar__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_83(expr);
	}
	LA11_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, nextOp__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_48)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw opList) {
	NIM_CHAR result;
	NI T1_;
	NIM_CHAR T2_;
	result = (NIM_CHAR)0;
	T1_ = (NI)0;
	T1_ = skipWhitespace__pureZparseutils_105((*expr).input, (*expr).pos);
	T2_ = (NIM_CHAR)0;
	T2_ = incPos__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_40(expr, T1_);
	{
		NIM_CHAR T7_;
		if (!((opList[(NU)(((NU8)((*expr).ch)))>>3] &(1U<<((NU)(((NU8)((*expr).ch)))&7U)))!=0)) goto LA5_;
		result = (*expr).ch;
		T7_ = (NIM_CHAR)0;
		T7_ = incPos__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_40(expr, ((NI) 1));
	}
	goto LA3_;
	LA5_: ;
	{
		result = 0;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, parsePow__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_167)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr) {
	NF result;
	result = (NF)0;
	result = parseFactor__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_65(expr);
	{
		while (1) {
			NIM_BOOL T3_;
			NIM_CHAR T4_;
			T3_ = (NIM_BOOL)0;
			T3_ = atEnd__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_37(expr);
			if (!!(T3_)) goto LA2;
			T4_ = (NIM_CHAR)0;
			T4_ = nextOp__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_48(expr, TM__Am39cESEeY2Yo6CaAQQLJXg_68);
			switch (((NU8)(T4_))) {
			case 94:
			{
				NF T6_;
				T6_ = (NF)0;
				T6_ = parseFactor__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_65(expr);
				result = pow(result, T6_);
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		} LA2: ;
	} LA1: ;
	return result;
}
static N_INLINE(void, stareq___pureZstrutils_2156)(NF* x, NF y) {
	(*x) = ((NF)((*x)) * (NF)(y));
}
static N_INLINE(void, slasheq___system_7440)(NF* x, NF y) {
	(*x) = ((NF)((*x)) / (NF)(y));
}
N_LIB_PRIVATE N_NIMCALL(NF, parseTerm__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_999)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr) {
	NF result;
	result = (NF)0;
	result = parsePow__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_167(expr);
	{
		while (1) {
			NIM_BOOL T3_;
			NIM_CHAR T4_;
			T3_ = (NIM_BOOL)0;
			T3_ = atEnd__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_37(expr);
			if (!!(T3_)) goto LA2;
			T4_ = (NIM_CHAR)0;
			T4_ = nextOp__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_48(expr, TM__Am39cESEeY2Yo6CaAQQLJXg_69);
			switch (((NU8)(T4_))) {
			case 42:
			{
				NF T6_;
				T6_ = (NF)0;
				T6_ = parsePow__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_167(expr);
				stareq___pureZstrutils_2156((&result), T6_);
			}
			break;
			case 47:
			{
				NF T8_;
				T8_ = (NF)0;
				T8_ = parsePow__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_167(expr);
				slasheq___system_7440((&result), T8_);
			}
			break;
			case 37:
			{
				NF T10_;
				T10_ = (NF)0;
				T10_ = parsePow__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_167(expr);
				result = fmod(result, T10_);
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		} LA2: ;
	} LA1: ;
	return result;
}
static N_INLINE(void, pluseq___pureZstrutils_2160)(NF* x, NF y) {
	(*x) = ((NF)((*x)) + (NF)(y));
}
static N_INLINE(void, minuseq___OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1013)(NF* x, NF y) {
	(*x) = ((NF)((*x)) - (NF)(y));
}
N_LIB_PRIVATE N_NIMCALL(NF, parseAddition__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1006)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr) {
	NF result;
	result = (NF)0;
	result = parseTerm__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_999(expr);
	{
		while (1) {
			NIM_BOOL T3_;
			NIM_CHAR T4_;
			T3_ = (NIM_BOOL)0;
			T3_ = atEnd__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_37(expr);
			if (!!(T3_)) goto LA2;
			T4_ = (NIM_CHAR)0;
			T4_ = nextOp__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_48(expr, TM__Am39cESEeY2Yo6CaAQQLJXg_70);
			switch (((NU8)(T4_))) {
			case 43:
			{
				NF T6_;
				T6_ = (NF)0;
				T6_ = parseTerm__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_999(expr);
				pluseq___pureZstrutils_2160((&result), T6_);
			}
			break;
			case 45:
			{
				NF T8_;
				T8_ = (NF)0;
				T8_ = parseTerm__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_999(expr);
				minuseq___OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1013((&result), T8_);
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		} LA2: ;
	} LA1: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, parseRelative__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1017)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr) {
	NF result;
	result = (NF)0;
	result = parseAddition__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1006(expr);
	{
		while (1) {
			NIM_BOOL T3_;
			NIM_CHAR op;
			T3_ = (NIM_BOOL)0;
			T3_ = atEnd__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_37(expr);
			if (!!(T3_)) goto LA2;
			op = nextOp__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_48(expr, TM__Am39cESEeY2Yo6CaAQQLJXg_71);
			switch (((NU8)(op))) {
			case 60:
			case 62:
			{
				{
					NIM_BOOL T7_;
					T7_ = (NIM_BOOL)0;
					T7_ = eat__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_56(expr, 61);
					if (!T7_) goto LA8_;
					switch (((NU8)(op))) {
					case 60:
					{
						{
							NF T13_;
							T13_ = (NF)0;
							T13_ = parseAddition__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1006(expr);
							if (!(result <= T13_)) goto LA14_;
							result = 1.0;
						}
						goto LA11_;
						LA14_: ;
						{
							result = 0.0;
						}
						LA11_: ;
					}
					break;
					case 62:
					{
						{
							NF T20_;
							T20_ = (NF)0;
							T20_ = parseAddition__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1006(expr);
							if (!(T20_ <= result)) goto LA21_;
							result = 1.0;
						}
						goto LA18_;
						LA21_: ;
						{
							result = 0.0;
						}
						LA18_: ;
					}
					break;
					default:
					{
						result = NAN;
					}
					break;
					}
				}
				goto LA5_;
				LA8_: ;
				{
					switch (((NU8)(op))) {
					case 60:
					{
						{
							NF T29_;
							T29_ = (NF)0;
							T29_ = parseAddition__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1006(expr);
							if (!(result < T29_)) goto LA30_;
							result = 1.0;
						}
						goto LA27_;
						LA30_: ;
						{
							result = 0.0;
						}
						LA27_: ;
					}
					break;
					case 62:
					{
						{
							NF T36_;
							T36_ = (NF)0;
							T36_ = parseAddition__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1006(expr);
							if (!(T36_ < result)) goto LA37_;
							result = 1.0;
						}
						goto LA34_;
						LA37_: ;
						{
							result = 0.0;
						}
						LA34_: ;
					}
					break;
					default:
					{
						result = NAN;
					}
					break;
					}
				}
				LA5_: ;
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		} LA2: ;
	} LA1: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, tildeeq___OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1021)(NF a, NF b) {
	NIM_BOOL result;
	NF T1_;
	result = (NIM_BOOL)0;
	T1_ = (NF)0;
	T1_ = abs__pureZmath_148(((NF)(a) - (NF)(b)));
	result = (T1_ < 0.0001);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, parseExpression__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_63)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr) {
	NF result;
	result = (NF)0;
	result = parseRelative__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1017(expr);
	{
		while (1) {
			NIM_BOOL T3_;
			NIM_CHAR op;
			T3_ = (NIM_BOOL)0;
			T3_ = atEnd__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_37(expr);
			if (!!(T3_)) goto LA2;
			op = nextOp__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_48(expr, TM__Am39cESEeY2Yo6CaAQQLJXg_72);
			switch (((NU8)(op))) {
			case 61:
			case 33:
			{
				{
					NIM_BOOL T7_;
					T7_ = (NIM_BOOL)0;
					T7_ = eat__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_56(expr, 61);
					if (!!(T7_)) goto LA8_;
					unexpectedChar__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_83(expr);
				}
				LA8_: ;
				switch (((NU8)(op))) {
				case 61:
				{
					{
						NF T13_;
						NIM_BOOL T14_;
						T13_ = (NF)0;
						T13_ = parseExpression__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_63(expr);
						T14_ = (NIM_BOOL)0;
						T14_ = tildeeq___OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1021(result, T13_);
						if (!T14_) goto LA15_;
						result = 1.0;
					}
					goto LA11_;
					LA15_: ;
					{
						result = 0.0;
					}
					LA11_: ;
				}
				break;
				case 33:
				{
					{
						NF T21_;
						NIM_BOOL T22_;
						T21_ = (NF)0;
						T21_ = parseExpression__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_63(expr);
						T22_ = (NIM_BOOL)0;
						T22_ = tildeeq___OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1021(result, T21_);
						if (!!(T22_)) goto LA23_;
						result = 1.0;
					}
					goto LA19_;
					LA23_: ;
					{
						result = 0.0;
					}
					LA19_: ;
				}
				break;
				default:
				{
					result = NAN;
				}
				break;
				}
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		} LA2: ;
	} LA1: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, parse__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1032)(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg* expr) {
	NF result;
	result = (NF)0;
	result = parseExpression__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_63(expr);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = atEnd__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_37(expr);
		if (!!(T3_)) goto LA4_;
		unexpectedChar__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_83(expr);
	}
	LA4_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, eval__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_4385)(tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA* e, NimStringDesc* input) {
	NF result;
	tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg expr;
	result = (NF)0;
	{
		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T5_;
		NimStringDesc* T6_;
		if (!((input ? input->Sup.len : 0) == ((NI) 0))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
		(*T5_).Sup.Sup.Sup.m_type = (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_);
		(*T5_).Sup.Sup.name = "ValueError";
		T6_ = NIM_NIL;
		T6_ = (*T5_).Sup.Sup.message; (*T5_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__Am39cESEeY2Yo6CaAQQLJXg_9));
		if (T6_) nimGCunrefNoCycle(T6_);
		asgnRef((void**) (&(*T5_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T5_, "ValueError", "eval", "mathexpr.nim", 429);
	}
	LA3_: ;
	nimZeroMem((void*)(&expr), sizeof(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg));
	nimZeroMem((void*)(&expr), sizeof(tyObject_MathExpression__6CoUhGksbRjS543MoYKiKg));
	expr.eval = e;
	expr.len = (input ? input->Sup.len : 0);
	if (((NI) 0) < 0 || ((NI) 0) >= (input ? input->Sup.len : 0)){ raiseIndexError2(((NI) 0),(input ? input->Sup.len : 0)-1); }
	expr.ch = input->data[((NI) 0)];
	expr.input = copyString(input);
	expr.pos = ((NI) 0);
	result = parse__OOZOOZOOZOOZOnimbleZpkgsZmathexpr4549O51O50Zmathexpr_1032((&expr));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsmathexprminus1dot3dot2atsmathexprdotnim_DatInit000)(void) {
static TNimNode* TM__Am39cESEeY2Yo6CaAQQLJXg_2_2[2];
static TNimNode* TM__Am39cESEeY2Yo6CaAQQLJXg_3_2[2];
static TNimNode* TM__Am39cESEeY2Yo6CaAQQLJXg_4_3[3];
static TNimNode* TM__Am39cESEeY2Yo6CaAQQLJXg_5_2[2];
static TNimNode* TM__Am39cESEeY2Yo6CaAQQLJXg_6_2[2];
static TNimNode* TM__Am39cESEeY2Yo6CaAQQLJXg_7_2[2];
static TNimNode* TM__Am39cESEeY2Yo6CaAQQLJXg_8_3[3];
static TNimNode TM__Am39cESEeY2Yo6CaAQQLJXg_0[23];
NTIevaluator58objecttype__bDt7DiS4ttz1qz9cDLb2ogA_.size = sizeof(tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA);
NTIevaluator58objecttype__bDt7DiS4ttz1qz9cDLb2ogA_.align = NIM_ALIGNOF(tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA);
NTIevaluator58objecttype__bDt7DiS4ttz1qz9cDLb2ogA_.kind = 18;
NTIevaluator58objecttype__bDt7DiS4ttz1qz9cDLb2ogA_.base = 0;
TM__Am39cESEeY2Yo6CaAQQLJXg_2_2[0] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[1];
NTItable__XXJncbsdsiyd9bMMxnjd9bLQ_.size = sizeof(tyObject_Table__XXJncbsdsiyd9bMMxnjd9bLQ);
NTItable__XXJncbsdsiyd9bMMxnjd9bLQ_.align = NIM_ALIGNOF(tyObject_Table__XXJncbsdsiyd9bMMxnjd9bLQ);
NTItable__XXJncbsdsiyd9bMMxnjd9bLQ_.kind = 18;
NTItable__XXJncbsdsiyd9bMMxnjd9bLQ_.base = 0;
TM__Am39cESEeY2Yo6CaAQQLJXg_3_2[0] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[3];
NTIkeyvaluepair__FPQKOEgl1j9bR6yoK9cLiDOg_.size = sizeof(tyTuple__FPQKOEgl1j9bR6yoK9cLiDOg);
NTIkeyvaluepair__FPQKOEgl1j9bR6yoK9cLiDOg_.align = NIM_ALIGNOF(tyTuple__FPQKOEgl1j9bR6yoK9cLiDOg);
NTIkeyvaluepair__FPQKOEgl1j9bR6yoK9cLiDOg_.kind = 18;
NTIkeyvaluepair__FPQKOEgl1j9bR6yoK9cLiDOg_.base = 0;
TM__Am39cESEeY2Yo6CaAQQLJXg_4_3[0] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[5];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[5].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[5].offset = offsetof(tyTuple__FPQKOEgl1j9bR6yoK9cLiDOg, Field0);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[5].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[5].name = "Field0";
TM__Am39cESEeY2Yo6CaAQQLJXg_4_3[1] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[6];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[6].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[6].offset = offsetof(tyTuple__FPQKOEgl1j9bR6yoK9cLiDOg, Field1);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[6].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[6].name = "Field1";
TM__Am39cESEeY2Yo6CaAQQLJXg_4_3[2] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[7];
NTImathcustomfun__w1UOSBcoG3QYUCc0FBDjjA_.size = sizeof(tyObject_MathCustomFun__w1UOSBcoG3QYUCc0FBDjjA);
NTImathcustomfun__w1UOSBcoG3QYUCc0FBDjjA_.align = NIM_ALIGNOF(tyObject_MathCustomFun__w1UOSBcoG3QYUCc0FBDjjA);
NTImathcustomfun__w1UOSBcoG3QYUCc0FBDjjA_.kind = 18;
NTImathcustomfun__w1UOSBcoG3QYUCc0FBDjjA_.base = 0;
TM__Am39cESEeY2Yo6CaAQQLJXg_5_2[0] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[9];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[9].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[9].offset = offsetof(tyObject_MathCustomFun__w1UOSBcoG3QYUCc0FBDjjA, argCount);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[9].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[9].name = "argCount";
TM__Am39cESEeY2Yo6CaAQQLJXg_5_2[1] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[10];
NTImathfunction__MUgIlUB9cCKG2vJ1LwWGGzg_.size = sizeof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A);
NTImathfunction__MUgIlUB9cCKG2vJ1LwWGGzg_.align = NIM_ALIGNOF(tyTuple__JfHvHzMrhKkWAUvQKe0i1A);
NTImathfunction__MUgIlUB9cCKG2vJ1LwWGGzg_.kind = 18;
NTImathfunction__MUgIlUB9cCKG2vJ1LwWGGzg_.base = 0;
TM__Am39cESEeY2Yo6CaAQQLJXg_6_2[0] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[12];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[12].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[12].offset = offsetof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A, Field0);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[12].typ = (&NTIpointer__vr5DoT1jILTGdRlYv1OYpw_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[12].name = "Field0";
TM__Am39cESEeY2Yo6CaAQQLJXg_6_2[1] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[13];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[13].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[13].offset = offsetof(tyTuple__JfHvHzMrhKkWAUvQKe0i1A, Field1);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[13].typ = (&NTIrefobject__HsJiUUcO9cHBdUCi0HwkSTA_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[13].name = "Field1";
TM__Am39cESEeY2Yo6CaAQQLJXg_0[11].len = 2; TM__Am39cESEeY2Yo6CaAQQLJXg_0[11].kind = 2; TM__Am39cESEeY2Yo6CaAQQLJXg_0[11].sons = &TM__Am39cESEeY2Yo6CaAQQLJXg_6_2[0];
NTImathfunction__MUgIlUB9cCKG2vJ1LwWGGzg_.node = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[11];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[10].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[10].offset = offsetof(tyObject_MathCustomFun__w1UOSBcoG3QYUCc0FBDjjA, fun);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[10].typ = (&NTImathfunction__MUgIlUB9cCKG2vJ1LwWGGzg_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[10].name = "fun";
TM__Am39cESEeY2Yo6CaAQQLJXg_0[8].len = 2; TM__Am39cESEeY2Yo6CaAQQLJXg_0[8].kind = 2; TM__Am39cESEeY2Yo6CaAQQLJXg_0[8].sons = &TM__Am39cESEeY2Yo6CaAQQLJXg_5_2[0];
NTImathcustomfun__w1UOSBcoG3QYUCc0FBDjjA_.node = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[8];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[7].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[7].offset = offsetof(tyTuple__FPQKOEgl1j9bR6yoK9cLiDOg, Field2);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[7].typ = (&NTImathcustomfun__w1UOSBcoG3QYUCc0FBDjjA_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[7].name = "Field2";
TM__Am39cESEeY2Yo6CaAQQLJXg_0[4].len = 3; TM__Am39cESEeY2Yo6CaAQQLJXg_0[4].kind = 2; TM__Am39cESEeY2Yo6CaAQQLJXg_0[4].sons = &TM__Am39cESEeY2Yo6CaAQQLJXg_4_3[0];
NTIkeyvaluepair__FPQKOEgl1j9bR6yoK9cLiDOg_.node = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[4];
NTIkeyvaluepairseq__V8S0OuZvBGWe7eu6xfSNnA_.size = sizeof(tySequence__V8S0OuZvBGWe7eu6xfSNnA*);
NTIkeyvaluepairseq__V8S0OuZvBGWe7eu6xfSNnA_.align = NIM_ALIGNOF(tySequence__V8S0OuZvBGWe7eu6xfSNnA*);
NTIkeyvaluepairseq__V8S0OuZvBGWe7eu6xfSNnA_.kind = 24;
NTIkeyvaluepairseq__V8S0OuZvBGWe7eu6xfSNnA_.base = (&NTIkeyvaluepair__FPQKOEgl1j9bR6yoK9cLiDOg_);
NTIkeyvaluepairseq__V8S0OuZvBGWe7eu6xfSNnA_.marker = Marker_tySequence__V8S0OuZvBGWe7eu6xfSNnA;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[3].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[3].offset = offsetof(tyObject_Table__XXJncbsdsiyd9bMMxnjd9bLQ, data);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[3].typ = (&NTIkeyvaluepairseq__V8S0OuZvBGWe7eu6xfSNnA_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[3].name = "data";
TM__Am39cESEeY2Yo6CaAQQLJXg_3_2[1] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[14];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[14].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[14].offset = offsetof(tyObject_Table__XXJncbsdsiyd9bMMxnjd9bLQ, counter);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[14].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[14].name = "counter";
TM__Am39cESEeY2Yo6CaAQQLJXg_0[2].len = 2; TM__Am39cESEeY2Yo6CaAQQLJXg_0[2].kind = 2; TM__Am39cESEeY2Yo6CaAQQLJXg_0[2].sons = &TM__Am39cESEeY2Yo6CaAQQLJXg_3_2[0];
NTItable__XXJncbsdsiyd9bMMxnjd9bLQ_.node = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[2];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[1].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[1].offset = offsetof(tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA, funcs);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[1].typ = (&NTItable__XXJncbsdsiyd9bMMxnjd9bLQ_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[1].name = "funcs";
TM__Am39cESEeY2Yo6CaAQQLJXg_2_2[1] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[15];
NTItable__ZCml3pTinBhuzdz9cpDAlEQ_.size = sizeof(tyObject_Table__ZCml3pTinBhuzdz9cpDAlEQ);
NTItable__ZCml3pTinBhuzdz9cpDAlEQ_.align = NIM_ALIGNOF(tyObject_Table__ZCml3pTinBhuzdz9cpDAlEQ);
NTItable__ZCml3pTinBhuzdz9cpDAlEQ_.kind = 18;
NTItable__ZCml3pTinBhuzdz9cpDAlEQ_.base = 0;
TM__Am39cESEeY2Yo6CaAQQLJXg_7_2[0] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[17];
NTIkeyvaluepair__wytEHNBmW9b2ZZbxWUcxlyQ_.size = sizeof(tyTuple__wytEHNBmW9b2ZZbxWUcxlyQ);
NTIkeyvaluepair__wytEHNBmW9b2ZZbxWUcxlyQ_.align = NIM_ALIGNOF(tyTuple__wytEHNBmW9b2ZZbxWUcxlyQ);
NTIkeyvaluepair__wytEHNBmW9b2ZZbxWUcxlyQ_.kind = 18;
NTIkeyvaluepair__wytEHNBmW9b2ZZbxWUcxlyQ_.base = 0;
TM__Am39cESEeY2Yo6CaAQQLJXg_8_3[0] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[19];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[19].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[19].offset = offsetof(tyTuple__wytEHNBmW9b2ZZbxWUcxlyQ, Field0);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[19].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[19].name = "Field0";
TM__Am39cESEeY2Yo6CaAQQLJXg_8_3[1] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[20];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[20].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[20].offset = offsetof(tyTuple__wytEHNBmW9b2ZZbxWUcxlyQ, Field1);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[20].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[20].name = "Field1";
TM__Am39cESEeY2Yo6CaAQQLJXg_8_3[2] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[21];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[21].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[21].offset = offsetof(tyTuple__wytEHNBmW9b2ZZbxWUcxlyQ, Field2);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[21].typ = (&NTIfloat__w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[21].name = "Field2";
TM__Am39cESEeY2Yo6CaAQQLJXg_0[18].len = 3; TM__Am39cESEeY2Yo6CaAQQLJXg_0[18].kind = 2; TM__Am39cESEeY2Yo6CaAQQLJXg_0[18].sons = &TM__Am39cESEeY2Yo6CaAQQLJXg_8_3[0];
NTIkeyvaluepair__wytEHNBmW9b2ZZbxWUcxlyQ_.node = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[18];
NTIkeyvaluepairseq__F5atQpvvwSviKdnmy3vGJQ_.size = sizeof(tySequence__F5atQpvvwSviKdnmy3vGJQ*);
NTIkeyvaluepairseq__F5atQpvvwSviKdnmy3vGJQ_.align = NIM_ALIGNOF(tySequence__F5atQpvvwSviKdnmy3vGJQ*);
NTIkeyvaluepairseq__F5atQpvvwSviKdnmy3vGJQ_.kind = 24;
NTIkeyvaluepairseq__F5atQpvvwSviKdnmy3vGJQ_.base = (&NTIkeyvaluepair__wytEHNBmW9b2ZZbxWUcxlyQ_);
NTIkeyvaluepairseq__F5atQpvvwSviKdnmy3vGJQ_.marker = Marker_tySequence__F5atQpvvwSviKdnmy3vGJQ;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[17].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[17].offset = offsetof(tyObject_Table__ZCml3pTinBhuzdz9cpDAlEQ, data);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[17].typ = (&NTIkeyvaluepairseq__F5atQpvvwSviKdnmy3vGJQ_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[17].name = "data";
TM__Am39cESEeY2Yo6CaAQQLJXg_7_2[1] = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[22];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[22].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[22].offset = offsetof(tyObject_Table__ZCml3pTinBhuzdz9cpDAlEQ, counter);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[22].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[22].name = "counter";
TM__Am39cESEeY2Yo6CaAQQLJXg_0[16].len = 2; TM__Am39cESEeY2Yo6CaAQQLJXg_0[16].kind = 2; TM__Am39cESEeY2Yo6CaAQQLJXg_0[16].sons = &TM__Am39cESEeY2Yo6CaAQQLJXg_7_2[0];
NTItable__ZCml3pTinBhuzdz9cpDAlEQ_.node = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[16];
TM__Am39cESEeY2Yo6CaAQQLJXg_0[15].kind = 1;
TM__Am39cESEeY2Yo6CaAQQLJXg_0[15].offset = offsetof(tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA, vars);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[15].typ = (&NTItable__ZCml3pTinBhuzdz9cpDAlEQ_);
TM__Am39cESEeY2Yo6CaAQQLJXg_0[15].name = "vars";
TM__Am39cESEeY2Yo6CaAQQLJXg_0[0].len = 2; TM__Am39cESEeY2Yo6CaAQQLJXg_0[0].kind = 2; TM__Am39cESEeY2Yo6CaAQQLJXg_0[0].sons = &TM__Am39cESEeY2Yo6CaAQQLJXg_2_2[0];
NTIevaluator58objecttype__bDt7DiS4ttz1qz9cDLb2ogA_.node = &TM__Am39cESEeY2Yo6CaAQQLJXg_0[0];
NTIevaluator__asXiMHDDHRpDV2IgI9c6obg_.size = sizeof(tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA*);
NTIevaluator__asXiMHDDHRpDV2IgI9c6obg_.align = NIM_ALIGNOF(tyObject_EvaluatorcolonObjectType___bDt7DiS4ttz1qz9cDLb2ogA*);
NTIevaluator__asXiMHDDHRpDV2IgI9c6obg_.kind = 22;
NTIevaluator__asXiMHDDHRpDV2IgI9c6obg_.base = (&NTIevaluator58objecttype__bDt7DiS4ttz1qz9cDLb2ogA_);
NTIevaluator__asXiMHDDHRpDV2IgI9c6obg_.marker = Marker_tyRef__asXiMHDDHRpDV2IgI9c6obg;
NTIseqLfloatT__Zj5xKXgsXnI4n4hPS6nACA_.size = sizeof(tySequence__Zj5xKXgsXnI4n4hPS6nACA*);
NTIseqLfloatT__Zj5xKXgsXnI4n4hPS6nACA_.align = NIM_ALIGNOF(tySequence__Zj5xKXgsXnI4n4hPS6nACA*);
NTIseqLfloatT__Zj5xKXgsXnI4n4hPS6nACA_.kind = 24;
NTIseqLfloatT__Zj5xKXgsXnI4n4hPS6nACA_.base = (&NTIfloat__w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTIseqLfloatT__Zj5xKXgsXnI4n4hPS6nACA_.marker = Marker_tySequence__Zj5xKXgsXnI4n4hPS6nACA;
}

