/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence__gnF6htrEU3VdsCZBgj9c9bSw tySequence__gnF6htrEU3VdsCZBgj9c9bSw;
typedef struct tyTuple__9bqdOjrj0ApToMEQZXAj3SQ tyTuple__9bqdOjrj0ApToMEQZXAj3SQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TokenKind__4d5vOmx35i20DLXtrILcpw;
struct tyTuple__9bqdOjrj0ApToMEQZXAj3SQ {
tyEnum_TokenKind__4d5vOmx35i20DLXtrILcpw Field0;
NimStringDesc* Field1;
NI Field2;
NI Field3;
NI Field4;
NI Field5;
};
struct tySequence__gnF6htrEU3VdsCZBgj9c9bSw {
  TGenericSeq Sup;
  tyTuple__9bqdOjrj0ApToMEQZXAj3SQ data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_167)(NimStringDesc** result, NI64 x);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_189)(NimStringDesc** result, NI x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, collectionToString__main_2829)(tySequence__gnF6htrEU3VdsCZBgj9c9bSw* x, NimStringDesc* prefix, NimStringDesc* separator, NimStringDesc* suffix);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__main_2844)(NimStringDesc** s, tyTuple__9bqdOjrj0ApToMEQZXAj3SQ x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__main_2873)(NimStringDesc** s, tyEnum_TokenKind__4d5vOmx35i20DLXtrILcpw x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__pureZos_538)(NimStringDesc** s, NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__pureZstrutils_1275)(NimStringDesc** s, NI x);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__systemZassertions_56)(NimStringDesc* msg);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2, "(", 1);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_3, ", ", 2);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_4, "kind", 4);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_5, ": ", 2);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_6, "value", 5);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_7, "wsno", 4);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_8, "line", 4);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_9, "col", 3);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_10, "pos", 3);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_11, ")", 1);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_12, "iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it", 90);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_13, "@[", 2);
STRING_LITERAL(TM__n49a9aYp5BrbXv9a6OCpJYm0g_14, "]", 1);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_6)(NI64 x) {
	NimStringDesc* result;
	result = NIM_NIL;
	addInt__stdZprivateZdigitsutils_167((&result), x);
	return result;
}
static N_INLINE(void, addInt__stdZprivateZdigitsutils_189)(NimStringDesc** result, NI x) {
	addInt__stdZprivateZdigitsutils_167(result, ((NI64) (x)));
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_3)(NI x) {
	NimStringDesc* result;
	result = NIM_NIL;
	addInt__stdZprivateZdigitsutils_189((&result), x);
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___main_2850)(tyTuple__9bqdOjrj0ApToMEQZXAj3SQ x) {
	NimStringDesc* result;
	NI count;
	result = NIM_NIL;
	result = copyString(((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_2));
	count = ((NI) 0);
	{
		if (!(((NI) 0) < count)) goto LA3_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_3));
	}
	LA3_: ;
	result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_4));
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_5));
	count += ((NI) 1);
	addQuoted__main_2873((&result), x.Field0);
	{
		if (!(((NI) 0) < count)) goto LA7_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_3));
	}
	LA7_: ;
	result = resizeString(result, 5);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_6));
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_5));
	count += ((NI) 1);
	addQuoted__pureZos_538((&result), x.Field1);
	{
		if (!(((NI) 0) < count)) goto LA11_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_3));
	}
	LA11_: ;
	result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_7));
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_5));
	count += ((NI) 1);
	addQuoted__pureZstrutils_1275((&result), x.Field2);
	{
		if (!(((NI) 0) < count)) goto LA15_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_3));
	}
	LA15_: ;
	result = resizeString(result, 4);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_8));
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_5));
	count += ((NI) 1);
	addQuoted__pureZstrutils_1275((&result), x.Field3);
	{
		if (!(((NI) 0) < count)) goto LA19_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_3));
	}
	LA19_: ;
	result = resizeString(result, 3);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_9));
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_5));
	count += ((NI) 1);
	addQuoted__pureZstrutils_1275((&result), x.Field4);
	{
		if (!(((NI) 0) < count)) goto LA23_;
		result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_3));
	}
	LA23_: ;
	result = resizeString(result, 3);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_10));
	result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_5));
	count += ((NI) 1);
	addQuoted__pureZstrutils_1275((&result), x.Field5);
	result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_11));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, collectionToString__main_2829)(tySequence__gnF6htrEU3VdsCZBgj9c9bSw* x, NimStringDesc* prefix, NimStringDesc* separator, NimStringDesc* suffix) {
	NimStringDesc* result;
	NIM_BOOL firstElement;
	result = NIM_NIL;
	result = copyString(prefix);
	firstElement = NIM_TRUE;
	{
		tyTuple__9bqdOjrj0ApToMEQZXAj3SQ* value;
		NI i;
		NI L;
		NI T2_;
		value = (tyTuple__9bqdOjrj0ApToMEQZXAj3SQ*)0;
		i = ((NI) 0);
		T2_ = (x ? x->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				if (!(i < L)) goto LA4;
				value = (&x->data[i]);
				{
					if (!firstElement) goto LA7_;
					firstElement = NIM_FALSE;
				}
				goto LA5_;
				LA7_: ;
				{
					result = resizeString(result, (separator ? separator->Sup.len : 0) + 0);
appendString(result, separator);
				}
				LA5_: ;
				addQuoted__main_2844((&result), (*value));
				i += ((NI) 1);
				{
					NI T12_;
					T12_ = (x ? x->Sup.len : 0);
					if (!!((T12_ == L))) goto LA13_;
					failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_12));
				}
				LA13_: ;
			} LA4: ;
		}
	}
	result = resizeString(result, (suffix ? suffix->Sup.len : 0) + 0);
appendString(result, suffix);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___main_2825)(tySequence__gnF6htrEU3VdsCZBgj9c9bSw* x) {
	NimStringDesc* result;
	result = NIM_NIL;
	result = collectionToString__main_2829(x, ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_13), ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_3), ((NimStringDesc*) &TM__n49a9aYp5BrbXv9a6OCpJYm0g_14));
	return result;
}
