/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg;
typedef struct tySequence__MlAD6nAPq9bHKla9cWiIZP0g tySequence__MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct tySequence__oLpBKXzW3hF9aCVMo5EymfQ tySequence__oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ;
typedef struct tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ;
typedef struct tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__Ih0V9cYug0VPJyBBGvgEH7Q tySequence__Ih0V9cYug0VPJyBBGvgEH7Q;
typedef struct Exception Exception;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyTuple__awOivLjlO76sGdHY7nQUjQ tyTuple__awOivLjlO76sGdHY7nQUjQ;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StringStreamObj__Olau5FPRehZBBEB77FHnfw tyObject_StringStreamObj__Olau5FPRehZBBEB77FHnfw;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
typedef struct tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg;
struct tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg {
tySequence__MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
struct tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q {
NIM_BOOL isUnquoted;
tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} _kind_1;
struct {NI64 num;
} _kind_2;
struct {NF fnum;
} _kind_3;
struct {NIM_BOOL bval;
} _kind_4;
struct {tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg fields;
} _kind_6;
struct {tySequence__oLpBKXzW3hF9aCVMo5EymfQ* elems;
} _kind_7;
};
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg {
  RootObj Sup;
NI bufpos;
NimStringDesc* buf;
tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
NI offsetBase;
tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw;
typedef NU8 tyEnum_JsonEventKind__0zjE9c54eTrq224F5wMcaFA;
typedef NU8 tyEnum_JsonError__G9cw5MrJXJrcpID5JXaplew;
struct tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ {
  tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg Sup;
NimStringDesc* a;
tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw tok;
tyEnum_JsonEventKind__0zjE9c54eTrq224F5wMcaFA kind;
tyEnum_JsonError__G9cw5MrJXJrcpID5JXaplew err;
tySequence__Ih0V9cYug0VPJyBBGvgEH7Q* state;
NimStringDesc* filename;
NIM_BOOL rawStringLiterals;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
};
struct tyTuple__awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_NIMCALL_PTR(void, tyProc__JQrsH08b4uPTH9cyFPlVOZg) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9bmhFrLahRsL2hltfRDVtlQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(void, tyProc__3svSoGIUJIsHkaBL7q4DAQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc__xflqkf2D1uVClg70czEDHA) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NI, tyProc__c9c0f59ak4YGQ6neEym8LPKw) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringDesc** buffer, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA slice);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__7jFfqMk9ajToCz6Hv9atCA4A) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringDesc** line);
typedef N_NIMCALL_PTR(NI, tyProc__2VVzVL9bOnKhj1eZKkf9cEuA) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ {
  RootObj Sup;
tyProc__JQrsH08b4uPTH9cyFPlVOZg closeImpl;
tyProc__9bmhFrLahRsL2hltfRDVtlQ atEndImpl;
tyProc__3svSoGIUJIsHkaBL7q4DAQ setPositionImpl;
tyProc__xflqkf2D1uVClg70czEDHA getPositionImpl;
tyProc__c9c0f59ak4YGQ6neEym8LPKw readDataStrImpl;
tyProc__7jFfqMk9ajToCz6Hv9atCA4A readLineImpl;
tyProc__2VVzVL9bOnKhj1eZKkf9cEuA readDataImpl;
tyProc__2VVzVL9bOnKhj1eZKkf9cEuA peekDataImpl;
tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ writeDataImpl;
tyProc__JQrsH08b4uPTH9cyFPlVOZg flushImpl;
};
struct tyObject_StringStreamObj__Olau5FPRehZBBEB77FHnfw {
  tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ Sup;
NimStringDesc* data;
NI pos;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag {
  tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw Sup;
};
typedef NU8 tyEnum_ParserState__Na0rM2Zdr3RpxeNeXbvLrQ;
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};
struct tySequence__MlAD6nAPq9bHKla9cWiIZP0g {
  TGenericSeq Sup;
  tyTuple__awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
struct tySequence__oLpBKXzW3hF9aCVMo5EymfQ {
  TGenericSeq Sup;
  tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
struct tySequence__Ih0V9cYug0VPJyBBGvgEH7Q {
  TGenericSeq Sup;
  tyEnum_ParserState__Na0rM2Zdr3RpxeNeXbvLrQ data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, parseJson__pureZjson_5307)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringDesc* filename, NIM_BOOL rawIntegers, NIM_BOOL rawFloats);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, open__pureZparsejson_97)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input, NimStringDesc* filename, NIM_BOOL rawStringLiterals);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw, getTok__pureZparsejson_442)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, parseJson__pureZjson_5269)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* p, NIM_BOOL rawIntegers, NIM_BOOL rawFloats, NI depth);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJStringMove__pureZjson_88)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence__MlAD6nAPq9bHKla9cWiIZP0g)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__oLpBKXzW3hF9aCVMo5EymfQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__zfzzuQ8txrdZAYK0WGWpHg)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError2)(NimStringDesc* f, NimStringDesc* discVal);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprDiscriminant)(NI e, TNimType* typ);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5311)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5305)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJRawNumber__pureZjson_85)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJInt__pureZjson_91)(NI64 n);
N_LIB_PRIVATE N_NIMCALL(NI64, nsuParseBiggestInt)(NimStringDesc* s);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJFloat__pureZjson_94)(NF n);
N_LIB_PRIVATE N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJBool__pureZjson_97)(NIM_BOOL b);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJNull__pureZjson_100)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseParseErr__pureZparsejson_597)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* p, NimStringDesc* msg) __attribute__((noreturn));
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJObject__pureZjson_102)(void);
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZjson_104)(NI initialSize, tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, eat__pureZparsejson_619)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* p, tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw tok);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, X5BX5Deq___pureZjson_1939)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* obj, NimStringDesc* key, tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* val);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__systemZassertions_56)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZjson_301)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg* t, NimStringDesc* key, tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* val);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJArray__pureZjson_133)(void);
static N_INLINE(void, nimGCunrefRC1)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_232)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* father, tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* child);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
static N_INLINE(void, close__pureZparsejson_151)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZlexbase_14)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L);
N_LIB_PRIVATE N_NIMCALL(void, nimLeaveFinally)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringStreamObj__Olau5FPRehZBBEB77FHnfw*, newStringStream__pureZstreams_710)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_LIB_PRIVATE N_NIMCALL(NI, len__pureZjson_3028)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n);
static N_INLINE(NI, len__pureZjson_2160)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg t);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, toUgly__pureZjson_4437)(NimStringDesc** result, tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* node);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_31)(NI hcode);
N_LIB_PRIVATE N_NIMCALL(void, escapeJson__pureZjson_4427)(NimStringDesc* s, NimStringDesc** result);
N_LIB_PRIVATE N_NIMCALL(void, escapeJsonUnquoted__pureZjson_4406)(NimStringDesc* s, NimStringDesc** result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_3)(NI x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toHex__pureZstrutils_1849)(NI x, NI len);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_167)(NimStringDesc** result, NI64 x);
static N_INLINE(void, addFloat__system_3124)(NimStringDesc** result, NF x);
N_LIB_PRIVATE N_NIMCALL(void, addFloatSprintf__systemZformatfloat_99)(NimStringDesc** result, NF x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZjson_2584)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, del__pureZjson_3742)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg* t, NimStringDesc* key);
extern TNimType NTIjsonparser__KWIQnzXEOUqdWsnCUL9atyQ_;
N_LIB_PRIVATE TNimType NTIjsonnodeobj__df9bshXB7C9cTiWPIOtX3j1Q_;
extern TNimType NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_;
N_LIB_PRIVATE TNimType NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_;
TNimNode* NimDT___df9bshXB7C9cTiWPIOtX3j1Q_kind[8];
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTIbiggestint__Aav8dQoMlCFnZRxA0IhTHQ_;
extern TNimType NTIfloat__w9bl9a1ul9ctRJWiMl9cNnIMvg_;
N_LIB_PRIVATE TNimType NTIorderedtable__ZZvSdVkA2s2sIyifu4cpkg_;
N_LIB_PRIVATE TNimType NTIorderedkeyvaluepair__awOivLjlO76sGdHY7nQUjQ_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIorderedkeyvaluepairseq__MlAD6nAPq9bHKla9cWiIZP0g_;
N_LIB_PRIVATE TNimType NTIseqLjsonnodeT__oLpBKXzW3hF9aCVMo5EymfQ_;
N_LIB_PRIVATE TNimType NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_;
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_9, "field \'str\' is not accessible for type \'JsonNodeObj\' using \'kind = ", 67);
extern TNimType NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_;
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_12, "}", 1);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_13, "string literal as key", 21);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_15, "json.nim(391, 9) `obj.kind == JObject` ", 39);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_16, "field \'fields\' is not accessible for type \'JsonNodeObj\' using \'kind = ", 70);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_17, "]", 1);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_18, "json.nim(302, 10) `father.kind == JArray` ", 42);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_19, "field \'elems\' is not accessible for type \'JsonNodeObj\' using \'kind = ", 69);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_21, "{", 1);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_22, "input", 5);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_23, "[", 1);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_24, ",", 1);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_26, "iterators.nim(240, 11) `len(a) == L` the length of the seq changed while iterating over it", 90);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_27, "\"", 1);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_28, "\\n", 2);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_29, "\\b", 2);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_30, "\\f", 2);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_31, "\\t", 2);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_32, "\\u000b", 6);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_33, "\\r", 2);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_34, "\\\"", 2);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_35, "\\u000", 5);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_36, "\\u00", 4);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_37, "\\\\", 2);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_39, "iterators.nim(258, 11) `len(a) == L` the length of the string changed while iterating over it", 93);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_40, ":", 1);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_41, "tables.nim(1720, 11) `len(t) == L` the length of the table changed while iterating over it", 90);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_42, "field \'num\' is not accessible for type \'JsonNodeObj\' using \'kind = ", 67);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_43, "field \'fnum\' is not accessible for type \'JsonNodeObj\' using \'kind = ", 68);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_44, "field \'bval\' is not accessible for type \'JsonNodeObj\' using \'kind = ", 68);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_45, "true", 4);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_46, "false", 5);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_47, "null", 4);
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_48, "json.nim(624, 9) `obj.kind == JObject` ", 39);
extern TNimType NTIrefkeyerror__8SzoIAgLw9ci2v0yafHj9b6Q_;
extern TNimType NTIkeyerror__t7nhKLvXTQS9cS8ByJU9bIag_;
STRING_LITERAL(TM__9b9bytt1stv9cZ8uqII7HFgew_49, "key not in object", 17);
extern TSafePoint* excHandler__system_2567;
extern TSafePoint* excHandler__system_2567;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5258;
extern TSafePoint* excHandler__system_2567;
extern TSafePoint* excHandler__system_2567;
extern Exception* currException__system_2568;
extern Exception* currException__system_2568;
extern Exception* currException__system_2568;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).prev = excHandler__system_2567;
	excHandler__system_2567 = s;
}
static N_NIMCALL(void, Marker_tySequence__MlAD6nAPq9bHKla9cWiIZP0g)(void* p, NI op) {
	tySequence__MlAD6nAPq9bHKla9cWiIZP0g* a;
	NI T1_;
	a = (tySequence__MlAD6nAPq9bHKla9cWiIZP0g*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].Field2, op);
	nimGCvisit((void*)a->data[T1_].Field3, op);
	}
}
static N_NIMCALL(void, Marker_tySequence__oLpBKXzW3hF9aCVMo5EymfQ)(void* p, NI op) {
	tySequence__oLpBKXzW3hF9aCVMo5EymfQ* a;
	NI T1_;
	a = (tySequence__oLpBKXzW3hF9aCVMo5EymfQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tyRef__zfzzuQ8txrdZAYK0WGWpHg)(void* p, NI op) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* a;
	a = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*)p;
	switch ((*a).kind) {
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 4):
	nimGCvisit((void*)(*a)._kind_1.str, op);
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 2):
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 3):
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 1):
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 0):
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 5):
	nimGCvisit((void*)(*a)._kind_6.fields.data, op);
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 6):
	nimGCvisit((void*)(*a)._kind_7.elems, op);
	break;
	} 
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5311)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 8));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU32)(((NU) (x))) < (NU32)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5305((&gch__system_5258.zct), c);
}
static N_INLINE(void, decRef__system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5354(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5311(src);
		incRef__system_5349(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5311((*dest));
		decRef__system_5356(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJStringMove__pureZjson_88)(NimStringDesc* s) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q));
	(*T1_).kind = ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 4);
	result = T1_;
	if (!(((16 &((NU8)1<<((NU)((*result).kind)&7U)))!=0))) 	{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_9), reprDiscriminant(((NI)(*result).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
	asgnRef((void**) (&(*result)._kind_1.str), s);
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5311(p);
	decRef__system_5356(T1_);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJRawNumber__pureZjson_85)(NimStringDesc* s) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	NimStringDesc* T2_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q));
	(*T1_).kind = ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 4);
	T2_ = NIM_NIL;
	T2_ = (*T1_)._kind_1.str; (*T1_)._kind_1.str = copyStringRC1(s);
	if (T2_) nimGCunrefNoCycle(T2_);
	(*T1_).isUnquoted = NIM_TRUE;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJInt__pureZjson_91)(NI64 n) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q));
	(*T1_).kind = ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 2);
	(*T1_)._kind_2.num = n;
	result = T1_;
	return result;
}
static N_INLINE(void, popSafePoint)(void) {
	excHandler__system_2567 = (*excHandler__system_2567).prev;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = NIM_NIL;
	result = currException__system_2568;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currException__system_2568), (*currException__system_2568).up);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJFloat__pureZjson_94)(NF n) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q));
	(*T1_).kind = ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 3);
	(*T1_)._kind_3.fnum = n;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJBool__pureZjson_97)(NIM_BOOL b) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q));
	(*T1_).kind = ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 1);
	(*T1_)._kind_4.bval = b;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJNull__pureZjson_100)(void) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q));
	(*T1_).kind = ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 0);
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJObject__pureZjson_102)(void) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q));
	(*T1_).kind = ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 5);
	initOrderedTable__pureZjson_104(((NI) 2), (&(*T1_)._kind_6.fields));
	result = T1_;
	return result;
}
static N_INLINE(void, X5BX5Deq___pureZjson_1939)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* obj, NimStringDesc* key, tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* val) {
	{
		if (!!(((*obj).kind == ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 5)))) goto LA3_;
		failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_15));
	}
	LA3_: ;
	if (!(((32 &((NU8)1<<((NU)((*obj).kind)&7U)))!=0))) 	{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_16), reprDiscriminant(((NI)(*obj).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
	X5BX5Deq___pureZjson_301((&(*obj)._kind_6.fields), key, val);
}
static N_INLINE(void, nimGCunrefRC1)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5311(p);
	decRef__system_5356(T1_);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, newJArray__pureZjson_133)(void) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q));
	(*T1_).kind = ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 6);
	if ((*T1_)._kind_7.elems) { nimGCunrefRC1((*T1_)._kind_7.elems); (*T1_)._kind_7.elems = NIM_NIL; }
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_232)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* father, tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* child) {
	NI T5_;
	{
		if (!!(((*father).kind == ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 6)))) goto LA3_;
		failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_18));
	}
	LA3_: ;
	if (!(((64 &((NU8)1<<((NU)((*father).kind)&7U)))!=0))) 	{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_19), reprDiscriminant(((NI)(*father).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
	asgnRef((void**) (&(*father)._kind_7.elems), (tySequence__oLpBKXzW3hF9aCVMo5EymfQ*) incrSeqV3((TGenericSeq*)((*father)._kind_7.elems), (&NTIseqLjsonnodeT__oLpBKXzW3hF9aCVMo5EymfQ_)));
	T5_ = (*father)._kind_7.elems->Sup.len++;
	asgnRef((void**) (&(*father)._kind_7.elems->data[T5_]), child);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, parseJson__pureZjson_5269)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* p, NIM_BOOL rawIntegers, NIM_BOOL rawFloats, NI depth) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* volatile result;
	result = NIM_NIL;
	switch ((*p).tok) {
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 2):
	{
		tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T2_;
		result = newJStringMove__pureZjson_88((*p).a);
		unsureAsgnRef((void**) (&(*p).a), ((NimStringDesc*) NIM_NIL));
		T2_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
		T2_ = getTok__pureZparsejson_442(p);
		(void)(T2_);
	}
	break;
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 3):
	{
		tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T12_;
		{
			if (!rawIntegers) goto LA6_;
			result = newJRawNumber__pureZjson_85((*p).a);
		}
		goto LA4_;
		LA6_: ;
		{
			TSafePoint TM__9b9bytt1stv9cZ8uqII7HFgew_10;
			NI64 T9_;
			pushSafePoint(&TM__9b9bytt1stv9cZ8uqII7HFgew_10);
			TM__9b9bytt1stv9cZ8uqII7HFgew_10.status = setjmp(TM__9b9bytt1stv9cZ8uqII7HFgew_10.context);
			if (TM__9b9bytt1stv9cZ8uqII7HFgew_10.status == 0) {
			T9_ = (NI64)0;
			T9_ = nsuParseBiggestInt((*p).a);
			result = newJInt__pureZjson_91(T9_);
			popSafePoint();
			}
			else {
				popSafePoint();
				if (isObj(nimBorrowCurrentException()->Sup.m_type, (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_))) {
					TM__9b9bytt1stv9cZ8uqII7HFgew_10.status = 0;
					result = newJRawNumber__pureZjson_85((*p).a);
					popCurrentException();
				}
			}
			if (TM__9b9bytt1stv9cZ8uqII7HFgew_10.status != 0) reraiseException();
		}
		LA4_: ;
		T12_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
		T12_ = getTok__pureZparsejson_442(p);
		(void)(T12_);
	}
	break;
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 4):
	{
		tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T22_;
		{
			if (!rawFloats) goto LA16_;
			result = newJRawNumber__pureZjson_85((*p).a);
		}
		goto LA14_;
		LA16_: ;
		{
			TSafePoint TM__9b9bytt1stv9cZ8uqII7HFgew_11;
			NF T19_;
			pushSafePoint(&TM__9b9bytt1stv9cZ8uqII7HFgew_11);
			TM__9b9bytt1stv9cZ8uqII7HFgew_11.status = setjmp(TM__9b9bytt1stv9cZ8uqII7HFgew_11.context);
			if (TM__9b9bytt1stv9cZ8uqII7HFgew_11.status == 0) {
			T19_ = (NF)0;
			T19_ = nsuParseFloat((*p).a);
			result = newJFloat__pureZjson_94(T19_);
			popSafePoint();
			}
			else {
				popSafePoint();
				if (isObj(nimBorrowCurrentException()->Sup.m_type, (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_))) {
					TM__9b9bytt1stv9cZ8uqII7HFgew_11.status = 0;
					result = newJRawNumber__pureZjson_85((*p).a);
					popCurrentException();
				}
			}
			if (TM__9b9bytt1stv9cZ8uqII7HFgew_11.status != 0) reraiseException();
		}
		LA14_: ;
		T22_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
		T22_ = getTok__pureZparsejson_442(p);
		(void)(T22_);
	}
	break;
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 5):
	{
		tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T24_;
		result = newJBool__pureZjson_97(NIM_TRUE);
		T24_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
		T24_ = getTok__pureZparsejson_442(p);
		(void)(T24_);
	}
	break;
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 6):
	{
		tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T26_;
		result = newJBool__pureZjson_97(NIM_FALSE);
		T26_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
		T26_ = getTok__pureZparsejson_442(p);
		(void)(T26_);
	}
	break;
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 7):
	{
		tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T28_;
		result = newJNull__pureZjson_100();
		T28_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
		T28_ = getTok__pureZparsejson_442(p);
		(void)(T28_);
	}
	break;
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 8):
	{
		tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T34_;
		{
			if (!(((NI) 1000) < depth)) goto LA32_;
			raiseParseErr__pureZparsejson_597((&(*p)), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_12));
		}
		LA32_: ;
		result = newJObject__pureZjson_102();
		T34_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
		T34_ = getTok__pureZparsejson_442(p);
		(void)(T34_);
		{
			while (1) {
				NimStringDesc* key;
				tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T41_;
				tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* val;
				NI TM__9b9bytt1stv9cZ8uqII7HFgew_14;
				tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T46_;
				if (!!(((*p).tok == ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 9)))) goto LA36;
				{
					if (!!(((*p).tok == ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 2)))) goto LA39_;
					raiseParseErr__pureZparsejson_597((&(*p)), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_13));
				}
				LA39_: ;
				key = copyString((*p).a);
				T41_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
				T41_ = getTok__pureZparsejson_442(p);
				(void)(T41_);
				eat__pureZparsejson_619(p, ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 12));
				if (nimAddInt(depth, ((NI) 1), &TM__9b9bytt1stv9cZ8uqII7HFgew_14)) { raiseOverflow(); };
				val = parseJson__pureZjson_5269(p, rawIntegers, rawFloats, (NI)(TM__9b9bytt1stv9cZ8uqII7HFgew_14));
				X5BX5Deq___pureZjson_1939(result, key, val);
				{
					if (!!(((*p).tok == ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 13)))) goto LA44_;
					goto LA35;
				}
				LA44_: ;
				T46_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
				T46_ = getTok__pureZparsejson_442(p);
				(void)(T46_);
			} LA36: ;
		} LA35: ;
		eat__pureZparsejson_619(p, ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 9));
	}
	break;
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 10):
	{
		tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T52_;
		{
			if (!(((NI) 1000) < depth)) goto LA50_;
			raiseParseErr__pureZparsejson_597((&(*p)), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_17));
		}
		LA50_: ;
		result = newJArray__pureZjson_133();
		T52_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
		T52_ = getTok__pureZparsejson_442(p);
		(void)(T52_);
		{
			while (1) {
				NI TM__9b9bytt1stv9cZ8uqII7HFgew_20;
				tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T55_;
				tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T60_;
				if (!!(((*p).tok == ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 11)))) goto LA54;
				if (nimAddInt(depth, ((NI) 1), &TM__9b9bytt1stv9cZ8uqII7HFgew_20)) { raiseOverflow(); };
				T55_ = NIM_NIL;
				T55_ = parseJson__pureZjson_5269(p, rawIntegers, rawFloats, (NI)(TM__9b9bytt1stv9cZ8uqII7HFgew_20));
				add__pureZjson_232(result, T55_);
				{
					if (!!(((*p).tok == ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 13)))) goto LA58_;
					goto LA53;
				}
				LA58_: ;
				T60_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
				T60_ = getTok__pureZparsejson_442(p);
				(void)(T60_);
			} LA54: ;
		} LA53: ;
		eat__pureZparsejson_619(p, ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 11));
	}
	break;
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 0):
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 9):
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 11):
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 12):
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 13):
	case ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 1):
	{
		raiseParseErr__pureZparsejson_597((&(*p)), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_21));
	}
	break;
	}
	return result;
}
static N_INLINE(void, close__pureZparsejson_151)(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ* my) {
	close__pureZlexbase_14(&my->Sup);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, parseJson__pureZjson_5307)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringDesc* filename, NIM_BOOL rawIntegers, NIM_BOOL rawFloats) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* volatile result;
	tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ p;
	TSafePoint TM__9b9bytt1stv9cZ8uqII7HFgew_2;
	tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw T1_;
	result = NIM_NIL;
	nimZeroMem((void*)(&p), sizeof(tyObject_JsonParser__KWIQnzXEOUqdWsnCUL9atyQ));
	p.Sup.Sup.m_type = (&NTIjsonparser__KWIQnzXEOUqdWsnCUL9atyQ_);
	open__pureZparsejson_97((&p), s, filename, NIM_FALSE);
	pushSafePoint(&TM__9b9bytt1stv9cZ8uqII7HFgew_2);
	TM__9b9bytt1stv9cZ8uqII7HFgew_2.status = setjmp(TM__9b9bytt1stv9cZ8uqII7HFgew_2.context);
	if (TM__9b9bytt1stv9cZ8uqII7HFgew_2.status == 0) {
	T1_ = (tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw)0;
	T1_ = getTok__pureZparsejson_442((&p));
	(void)(T1_);
	result = parseJson__pureZjson_5269((&p), rawIntegers, rawFloats, ((NI) 0));
	eat__pureZparsejson_619((&p), ((tyEnum_TokKind__Q9c4KaNqJU4PbXaGht0C7iw) 1));
	popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		close__pureZparsejson_151((&p));
		if (TM__9b9bytt1stv9cZ8uqII7HFgew_2.status != 0) nimLeaveFinally();
	}
	if (TM__9b9bytt1stv9cZ8uqII7HFgew_2.status != 0) reraiseException();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, parseJson__pureZjson_5314)(NimStringDesc* buffer, NIM_BOOL rawIntegers, NIM_BOOL rawFloats) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_StringStreamObj__Olau5FPRehZBBEB77FHnfw* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = newStringStream__pureZstreams_710(buffer);
	result = parseJson__pureZjson_5307(&T1_->Sup, ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_22), rawIntegers, rawFloats);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStr__pureZjson_148)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n, NimStringDesc* default_0) {
	NimStringDesc* result;
{	result = NIM_NIL;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (n == 0);
		if (T3_) goto LA4_;
		T3_ = !(((*n).kind == ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 4)));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = copyString(default_0);
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		if (!(((16 &((NU8)1<<((NU)((*n).kind)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_9), reprDiscriminant(((NI)(*n).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
		result = copyString((*n)._kind_1.str);
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*, percent___pureZjson_1806)(NimStringDesc* s) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	NimStringDesc* T2_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q));
	(*T1_).kind = ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 4);
	T2_ = NIM_NIL;
	T2_ = (*T1_)._kind_1.str; (*T1_)._kind_1.str = copyStringRC1(s);
	if (T2_) nimGCunrefNoCycle(T2_);
	result = T1_;
	return result;
}
static N_INLINE(NI, len__pureZjson_2160)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg t) {
	NI result;
	result = (NI)0;
	result = t.counter;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, len__pureZjson_3028)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* n) {
	NI result;
	result = (NI)0;
	switch ((*n).kind) {
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 6):
	{
		NI T2_;
		if (!(((64 &((NU8)1<<((NU)((*n).kind)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_19), reprDiscriminant(((NI)(*n).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
		T2_ = ((*n)._kind_7.elems ? (*n)._kind_7.elems->Sup.len : 0);
		result = T2_;
	}
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 5):
	{
		if (!(((32 &((NU8)1<<((NU)((*n).kind)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_16), reprDiscriminant(((NI)(*n).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
		result = len__pureZjson_2160((*n)._kind_6.fields);
	}
	break;
	default:
	{
	}
	break;
	}
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_31)(NI hcode) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((hcode == ((NI) 0)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, escapeJsonUnquoted__pureZjson_4406)(NimStringDesc* s, NimStringDesc** result) {
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		i = ((NI) 0);
		L = (s ? s->Sup.len : 0);
		{
			while (1) {
				NI TM__9b9bytt1stv9cZ8uqII7HFgew_38;
				if (!(i < L)) goto LA3;
				if (i < 0 || i >= (s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
				c = s->data[i];
				switch (((NU8)(c))) {
				case 10:
				{
					unsureAsgnRef((void**) (&(*result)), resizeString((*result), 2));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_28));
				}
				break;
				case 8:
				{
					unsureAsgnRef((void**) (&(*result)), resizeString((*result), 2));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_29));
				}
				break;
				case 12:
				{
					unsureAsgnRef((void**) (&(*result)), resizeString((*result), 2));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_30));
				}
				break;
				case 9:
				{
					unsureAsgnRef((void**) (&(*result)), resizeString((*result), 2));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_31));
				}
				break;
				case 11:
				{
					unsureAsgnRef((void**) (&(*result)), resizeString((*result), 6));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_32));
				}
				break;
				case 13:
				{
					unsureAsgnRef((void**) (&(*result)), resizeString((*result), 2));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_33));
				}
				break;
				case 34:
				{
					unsureAsgnRef((void**) (&(*result)), resizeString((*result), 2));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_34));
				}
				break;
				case 0 ... 7:
				{
					NimStringDesc* T12_;
					NimStringDesc* T13_;
					T12_ = NIM_NIL;
					T13_ = NIM_NIL;
					T13_ = dollar___systemZdollars_3(((NU8)(c)));
					T12_ = rawNewString((T13_ ? T13_->Sup.len : 0) + 5);
appendString(T12_, ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_35));
appendString(T12_, T13_);
					unsureAsgnRef((void**) (&(*result)), resizeString((*result), (T12_ ? T12_->Sup.len : 0) + 0));
appendString((*result), T12_);
				}
				break;
				case 14 ... 31:
				{
					NimStringDesc* T15_;
					NimStringDesc* T16_;
					T15_ = NIM_NIL;
					T16_ = NIM_NIL;
					T16_ = toHex__pureZstrutils_1849(((NU8)(c)), ((NI) 2));
					T15_ = rawNewString((T16_ ? T16_->Sup.len : 0) + 4);
appendString(T15_, ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_36));
appendString(T15_, T16_);
					unsureAsgnRef((void**) (&(*result)), resizeString((*result), (T15_ ? T15_->Sup.len : 0) + 0));
appendString((*result), T15_);
				}
				break;
				case 92:
				{
					unsureAsgnRef((void**) (&(*result)), resizeString((*result), 2));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_37));
				}
				break;
				default:
				{
					unsureAsgnRef((void**) (&(*result)), addChar((*result), c));
				}
				break;
				}
				if (nimAddInt(i, ((NI) 1), &TM__9b9bytt1stv9cZ8uqII7HFgew_38)) { raiseOverflow(); };
				i = (NI)(TM__9b9bytt1stv9cZ8uqII7HFgew_38);
				{
					if (!!(((s ? s->Sup.len : 0) == L))) goto LA21_;
					failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_39));
				}
				LA21_: ;
			} LA3: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(void, escapeJson__pureZjson_4427)(NimStringDesc* s, NimStringDesc** result) {
	unsureAsgnRef((void**) (&(*result)), resizeString((*result), 1));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_27));
	escapeJsonUnquoted__pureZjson_4406(s, result);
	unsureAsgnRef((void**) (&(*result)), resizeString((*result), 1));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_27));
}
static N_INLINE(void, addFloat__system_3124)(NimStringDesc** result, NF x) {
	addFloatSprintf__systemZformatfloat_99(result, x);
}
N_LIB_PRIVATE N_NIMCALL(void, toUgly__pureZjson_4437)(NimStringDesc** result, tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* node) {
	NIM_BOOL comma;
	comma = NIM_FALSE;
	switch ((*node).kind) {
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 6):
	{
		unsureAsgnRef((void**) (&(*result)), resizeString((*result), 1));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_23));
		{
			tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q** child;
			tySequence__oLpBKXzW3hF9aCVMo5EymfQ* colontmp_;
			NI i;
			NI L;
			NI T3_;
			child = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q**)0;
			colontmp_ = NIM_NIL;
			if (!(((64 &((NU8)1<<((NU)((*node).kind)&7U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_19), reprDiscriminant(((NI)(*node).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
			colontmp_ = (*node)._kind_7.elems;
			i = ((NI) 0);
			T3_ = (colontmp_ ? colontmp_->Sup.len : 0);
			L = T3_;
			{
				while (1) {
					NI TM__9b9bytt1stv9cZ8uqII7HFgew_25;
					if (!(i < L)) goto LA5;
					if (i < 0 || i >= (colontmp_ ? colontmp_->Sup.len : 0)){ raiseIndexError2(i,(colontmp_ ? colontmp_->Sup.len : 0)-1); }
					child = &colontmp_->data[i];
					{
						if (!comma) goto LA8_;
						unsureAsgnRef((void**) (&(*result)), resizeString((*result), 1));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_24));
					}
					goto LA6_;
					LA8_: ;
					{
						comma = NIM_TRUE;
					}
					LA6_: ;
					toUgly__pureZjson_4437(result, (*child));
					if (nimAddInt(i, ((NI) 1), &TM__9b9bytt1stv9cZ8uqII7HFgew_25)) { raiseOverflow(); };
					i = (NI)(TM__9b9bytt1stv9cZ8uqII7HFgew_25);
					{
						NI T13_;
						T13_ = (colontmp_ ? colontmp_->Sup.len : 0);
						if (!!((T13_ == L))) goto LA14_;
						failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_26));
					}
					LA14_: ;
				} LA5: ;
			}
		}
		unsureAsgnRef((void**) (&(*result)), resizeString((*result), 1));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_17));
	}
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 5):
	{
		unsureAsgnRef((void**) (&(*result)), resizeString((*result), 1));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_21));
		{
			NimStringDesc* key;
			tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* value;
			tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg colontmp__2;
			NI L_2;
			key = NIM_NIL;
			value = NIM_NIL;
			nimZeroMem((void*)(&colontmp__2), sizeof(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg));
			if (!(((32 &((NU8)1<<((NU)((*node).kind)&7U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_16), reprDiscriminant(((NI)(*node).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
			colontmp__2.data = (*node)._kind_6.fields.data;
			colontmp__2.counter = (*node)._kind_6.fields.counter;
			colontmp__2.first = (*node)._kind_6.fields.first;
			colontmp__2.last = (*node)._kind_6.fields.last;
			L_2 = len__pureZjson_2160(colontmp__2);
			{
				NI h;
				if (!(((NI) 0) < colontmp__2.counter)) goto LA20_;
				h = colontmp__2.first;
				{
					while (1) {
						NI nxt;
						if (!(((NI) 0) <= h)) goto LA23;
						if (h < 0 || h >= (colontmp__2.data ? colontmp__2.data->Sup.len : 0)){ raiseIndexError2(h,(colontmp__2.data ? colontmp__2.data->Sup.len : 0)-1); }
						nxt = colontmp__2.data->data[h].Field1;
						{
							NIM_BOOL T26_;
							if (h < 0 || h >= (colontmp__2.data ? colontmp__2.data->Sup.len : 0)){ raiseIndexError2(h,(colontmp__2.data ? colontmp__2.data->Sup.len : 0)-1); }
							T26_ = (NIM_BOOL)0;
							T26_ = isFilled__pureZcollectionsZtables_31(colontmp__2.data->data[h].Field0);
							if (!T26_) goto LA27_;
							if (h < 0 || h >= (colontmp__2.data ? colontmp__2.data->Sup.len : 0)){ raiseIndexError2(h,(colontmp__2.data ? colontmp__2.data->Sup.len : 0)-1); }
							key = colontmp__2.data->data[h].Field2;
							if (h < 0 || h >= (colontmp__2.data ? colontmp__2.data->Sup.len : 0)){ raiseIndexError2(h,(colontmp__2.data ? colontmp__2.data->Sup.len : 0)-1); }
							value = colontmp__2.data->data[h].Field3;
							{
								if (!comma) goto LA31_;
								unsureAsgnRef((void**) (&(*result)), resizeString((*result), 1));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_24));
							}
							goto LA29_;
							LA31_: ;
							{
								comma = NIM_TRUE;
							}
							LA29_: ;
							escapeJson__pureZjson_4427(key, result);
							unsureAsgnRef((void**) (&(*result)), resizeString((*result), 1));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_40));
							toUgly__pureZjson_4437(result, value);
							{
								NI T36_;
								T36_ = (NI)0;
								T36_ = len__pureZjson_2160(colontmp__2);
								if (!!((T36_ == L_2))) goto LA37_;
								failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_41));
							}
							LA37_: ;
						}
						LA27_: ;
						h = nxt;
					} LA23: ;
				}
			}
			LA20_: ;
		}
		unsureAsgnRef((void**) (&(*result)), resizeString((*result), 1));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_12));
	}
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 4):
	{
		{
			if (!(*node).isUnquoted) goto LA42_;
			if (!(((16 &((NU8)1<<((NU)((*node).kind)&7U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_9), reprDiscriminant(((NI)(*node).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
			unsureAsgnRef((void**) (&(*result)), resizeString((*result), ((*node)._kind_1.str ? (*node)._kind_1.str->Sup.len : 0) + 0));
appendString((*result), (*node)._kind_1.str);
		}
		goto LA40_;
		LA42_: ;
		{
			if (!(((16 &((NU8)1<<((NU)((*node).kind)&7U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_9), reprDiscriminant(((NI)(*node).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
			escapeJson__pureZjson_4427((*node)._kind_1.str, result);
		}
		LA40_: ;
	}
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 2):
	{
		if (!(((4 &((NU8)1<<((NU)((*node).kind)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_42), reprDiscriminant(((NI)(*node).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
		addInt__stdZprivateZdigitsutils_167(result, (*node)._kind_2.num);
	}
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 3):
	{
		if (!(((8 &((NU8)1<<((NU)((*node).kind)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_43), reprDiscriminant(((NI)(*node).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
		addFloat__system_3124(result, (*node)._kind_3.fnum);
	}
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 1):
	{
		NimStringDesc* T48_;
		T48_ = NIM_NIL;
		{
			if (!(((2 &((NU8)1<<((NU)((*node).kind)&7U)))!=0))) 			{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_44), reprDiscriminant(((NI)(*node).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
			if (!(*node)._kind_4.bval) goto LA51_;
			T48_ = copyString(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_45));
		}
		goto LA49_;
		LA51_: ;
		{
			T48_ = copyString(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_46));
		}
		LA49_: ;
		unsureAsgnRef((void**) (&(*result)), resizeString((*result), (T48_ ? T48_->Sup.len : 0) + 0));
appendString((*result), T48_);
	}
	break;
	case ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 0):
	{
		unsureAsgnRef((void**) (&(*result)), resizeString((*result), 4));
appendString((*result), ((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_47));
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___pureZjson_4540)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* node) {
	NimStringDesc* result;
	NI T1_;
	result = NIM_NIL;
	T1_ = (NI)0;
	T1_ = len__pureZjson_3028(node);
	if (((NI)((NU32)(T1_) << (NU32)(((NI) 1)))) < ((NI) 0) || ((NI)((NU32)(T1_) << (NU32)(((NI) 1)))) > ((NI) 2147483647)){ raiseRangeErrorI((NI)((NU32)(T1_) << (NU32)(((NI) 1))), ((NI) 0), ((NI) 2147483647)); }
	result = rawNewString(((NI) ((NI)((NU32)(T1_) << (NU32)(((NI) 1))))));
	toUgly__pureZjson_4437((&result), node);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, delete__pureZjson_3644)(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* obj, NimStringDesc* key) {
	{
		if (!!(((*obj).kind == ((tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg) 5)))) goto LA3_;
		failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_48));
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* T10_;
		NimStringDesc* T11_;
		if (!(((32 &((NU8)1<<((NU)((*obj).kind)&7U)))!=0))) 		{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_16), reprDiscriminant(((NI)(*obj).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
		T7_ = (NIM_BOOL)0;
		T7_ = hasKey__pureZjson_2584((*obj)._kind_6.fields, key);
		if (!!(T7_)) goto LA8_;
		T10_ = NIM_NIL;
		T10_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*) newObj((&NTIrefkeyerror__8SzoIAgLw9ci2v0yafHj9b6Q_), sizeof(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag));
		(*T10_).Sup.Sup.Sup.Sup.m_type = (&NTIkeyerror__t7nhKLvXTQS9cS8ByJU9bIag_);
		(*T10_).Sup.Sup.Sup.name = "KeyError";
		T11_ = NIM_NIL;
		T11_ = (*T10_).Sup.Sup.Sup.message; (*T10_).Sup.Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_49));
		if (T11_) nimGCunrefNoCycle(T11_);
		asgnRef((void**) (&(*T10_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T10_, "KeyError", "delete", "json.nim", 626);
	}
	LA8_: ;
	if (!(((32 &((NU8)1<<((NU)((*obj).kind)&7U)))!=0))) 	{ raiseFieldError2(((NimStringDesc*) &TM__9b9bytt1stv9cZ8uqII7HFgew_16), reprDiscriminant(((NI)(*obj).kind) + (NI)IL64(0), (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_))); } 
	del__pureZjson_3742((&(*obj)._kind_6.fields), key);
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsNimminusREatsnimminus1dot6dot10atslibatspureatsjsondotnim_DatInit000)(void) {
static TNimNode* TM__9b9bytt1stv9cZ8uqII7HFgew_3_2[2];
static TNimNode* TM__9b9bytt1stv9cZ8uqII7HFgew_4_7[7];
NI TM__9b9bytt1stv9cZ8uqII7HFgew_6;
static char* NIM_CONST TM__9b9bytt1stv9cZ8uqII7HFgew_5[7] = {
"JNull", 
"JBool", 
"JInt", 
"JFloat", 
"JString", 
"JObject", 
"JArray"};
static TNimNode* TM__9b9bytt1stv9cZ8uqII7HFgew_7_4[4];
static TNimNode* TM__9b9bytt1stv9cZ8uqII7HFgew_8_4[4];
static TNimNode TM__9b9bytt1stv9cZ8uqII7HFgew_0[28];
NTIjsonnodeobj__df9bshXB7C9cTiWPIOtX3j1Q_.size = sizeof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q);
NTIjsonnodeobj__df9bshXB7C9cTiWPIOtX3j1Q_.align = NIM_ALIGNOF(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q);
NTIjsonnodeobj__df9bshXB7C9cTiWPIOtX3j1Q_.kind = 18;
NTIjsonnodeobj__df9bshXB7C9cTiWPIOtX3j1Q_.base = 0;
NTIjsonnodeobj__df9bshXB7C9cTiWPIOtX3j1Q_.flags = 2;
TM__9b9bytt1stv9cZ8uqII7HFgew_3_2[0] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[1];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[1].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[1].offset = offsetof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q, isUnquoted);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[1].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[1].name = "isUnquoted";
TM__9b9bytt1stv9cZ8uqII7HFgew_3_2[1] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[2];
NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_.size = sizeof(tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg);
NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_.align = NIM_ALIGNOF(tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg);
NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_.kind = 14;
NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_.base = 0;
NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_.flags = 3;
for (TM__9b9bytt1stv9cZ8uqII7HFgew_6 = 0; TM__9b9bytt1stv9cZ8uqII7HFgew_6 < 7; TM__9b9bytt1stv9cZ8uqII7HFgew_6++) {
TM__9b9bytt1stv9cZ8uqII7HFgew_0[TM__9b9bytt1stv9cZ8uqII7HFgew_6+3].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[TM__9b9bytt1stv9cZ8uqII7HFgew_6+3].offset = TM__9b9bytt1stv9cZ8uqII7HFgew_6;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[TM__9b9bytt1stv9cZ8uqII7HFgew_6+3].name = TM__9b9bytt1stv9cZ8uqII7HFgew_5[TM__9b9bytt1stv9cZ8uqII7HFgew_6];
TM__9b9bytt1stv9cZ8uqII7HFgew_4_7[TM__9b9bytt1stv9cZ8uqII7HFgew_6] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[TM__9b9bytt1stv9cZ8uqII7HFgew_6+3];
}
TM__9b9bytt1stv9cZ8uqII7HFgew_0[10].len = 7; TM__9b9bytt1stv9cZ8uqII7HFgew_0[10].kind = 2; TM__9b9bytt1stv9cZ8uqII7HFgew_0[10].sons = &TM__9b9bytt1stv9cZ8uqII7HFgew_4_7[0];
NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_.node = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[10];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[2].kind = 3;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[2].offset = offsetof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q, kind);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[2].typ = (&NTIjsonnodekind__RUngo7nCHe6O8aBGIcrhtg_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[2].name = "kind";
TM__9b9bytt1stv9cZ8uqII7HFgew_0[2].sons = &NimDT___df9bshXB7C9cTiWPIOtX3j1Q_kind[0];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[2].len = 7;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[11].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[11].offset = offsetof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q, _kind_1.str);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[11].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[11].name = "str";
NimDT___df9bshXB7C9cTiWPIOtX3j1Q_kind[4] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[11];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[12].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[12].offset = offsetof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q, _kind_2.num);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[12].typ = (&NTIbiggestint__Aav8dQoMlCFnZRxA0IhTHQ_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[12].name = "num";
NimDT___df9bshXB7C9cTiWPIOtX3j1Q_kind[2] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[12];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[13].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[13].offset = offsetof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q, _kind_3.fnum);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[13].typ = (&NTIfloat__w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[13].name = "fnum";
NimDT___df9bshXB7C9cTiWPIOtX3j1Q_kind[3] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[13];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[14].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[14].offset = offsetof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q, _kind_4.bval);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[14].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[14].name = "bval";
NimDT___df9bshXB7C9cTiWPIOtX3j1Q_kind[1] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[14];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[15].len = 0; TM__9b9bytt1stv9cZ8uqII7HFgew_0[15].kind = 2;
NimDT___df9bshXB7C9cTiWPIOtX3j1Q_kind[0] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[15];
NTIorderedtable__ZZvSdVkA2s2sIyifu4cpkg_.size = sizeof(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg);
NTIorderedtable__ZZvSdVkA2s2sIyifu4cpkg_.align = NIM_ALIGNOF(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg);
NTIorderedtable__ZZvSdVkA2s2sIyifu4cpkg_.kind = 18;
NTIorderedtable__ZZvSdVkA2s2sIyifu4cpkg_.base = 0;
TM__9b9bytt1stv9cZ8uqII7HFgew_7_4[0] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[18];
NTIorderedkeyvaluepair__awOivLjlO76sGdHY7nQUjQ_.size = sizeof(tyTuple__awOivLjlO76sGdHY7nQUjQ);
NTIorderedkeyvaluepair__awOivLjlO76sGdHY7nQUjQ_.align = NIM_ALIGNOF(tyTuple__awOivLjlO76sGdHY7nQUjQ);
NTIorderedkeyvaluepair__awOivLjlO76sGdHY7nQUjQ_.kind = 18;
NTIorderedkeyvaluepair__awOivLjlO76sGdHY7nQUjQ_.base = 0;
TM__9b9bytt1stv9cZ8uqII7HFgew_8_4[0] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[20];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[20].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[20].offset = offsetof(tyTuple__awOivLjlO76sGdHY7nQUjQ, Field0);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[20].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[20].name = "Field0";
TM__9b9bytt1stv9cZ8uqII7HFgew_8_4[1] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[21];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[21].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[21].offset = offsetof(tyTuple__awOivLjlO76sGdHY7nQUjQ, Field1);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[21].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[21].name = "Field1";
TM__9b9bytt1stv9cZ8uqII7HFgew_8_4[2] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[22];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[22].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[22].offset = offsetof(tyTuple__awOivLjlO76sGdHY7nQUjQ, Field2);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[22].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[22].name = "Field2";
TM__9b9bytt1stv9cZ8uqII7HFgew_8_4[3] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[23];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[23].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[23].offset = offsetof(tyTuple__awOivLjlO76sGdHY7nQUjQ, Field3);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[23].typ = (&NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[23].name = "Field3";
TM__9b9bytt1stv9cZ8uqII7HFgew_0[19].len = 4; TM__9b9bytt1stv9cZ8uqII7HFgew_0[19].kind = 2; TM__9b9bytt1stv9cZ8uqII7HFgew_0[19].sons = &TM__9b9bytt1stv9cZ8uqII7HFgew_8_4[0];
NTIorderedkeyvaluepair__awOivLjlO76sGdHY7nQUjQ_.node = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[19];
NTIorderedkeyvaluepairseq__MlAD6nAPq9bHKla9cWiIZP0g_.size = sizeof(tySequence__MlAD6nAPq9bHKla9cWiIZP0g*);
NTIorderedkeyvaluepairseq__MlAD6nAPq9bHKla9cWiIZP0g_.align = NIM_ALIGNOF(tySequence__MlAD6nAPq9bHKla9cWiIZP0g*);
NTIorderedkeyvaluepairseq__MlAD6nAPq9bHKla9cWiIZP0g_.kind = 24;
NTIorderedkeyvaluepairseq__MlAD6nAPq9bHKla9cWiIZP0g_.base = (&NTIorderedkeyvaluepair__awOivLjlO76sGdHY7nQUjQ_);
NTIorderedkeyvaluepairseq__MlAD6nAPq9bHKla9cWiIZP0g_.marker = Marker_tySequence__MlAD6nAPq9bHKla9cWiIZP0g;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[18].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[18].offset = offsetof(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg, data);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[18].typ = (&NTIorderedkeyvaluepairseq__MlAD6nAPq9bHKla9cWiIZP0g_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[18].name = "data";
TM__9b9bytt1stv9cZ8uqII7HFgew_7_4[1] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[24];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[24].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[24].offset = offsetof(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg, counter);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[24].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[24].name = "counter";
TM__9b9bytt1stv9cZ8uqII7HFgew_7_4[2] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[25];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[25].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[25].offset = offsetof(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg, first);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[25].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[25].name = "first";
TM__9b9bytt1stv9cZ8uqII7HFgew_7_4[3] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[26];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[26].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[26].offset = offsetof(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg, last);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[26].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[26].name = "last";
TM__9b9bytt1stv9cZ8uqII7HFgew_0[17].len = 4; TM__9b9bytt1stv9cZ8uqII7HFgew_0[17].kind = 2; TM__9b9bytt1stv9cZ8uqII7HFgew_0[17].sons = &TM__9b9bytt1stv9cZ8uqII7HFgew_7_4[0];
NTIorderedtable__ZZvSdVkA2s2sIyifu4cpkg_.node = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[17];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[16].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[16].offset = offsetof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q, _kind_6.fields);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[16].typ = (&NTIorderedtable__ZZvSdVkA2s2sIyifu4cpkg_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[16].name = "fields";
NimDT___df9bshXB7C9cTiWPIOtX3j1Q_kind[5] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[16];
NTIseqLjsonnodeT__oLpBKXzW3hF9aCVMo5EymfQ_.size = sizeof(tySequence__oLpBKXzW3hF9aCVMo5EymfQ*);
NTIseqLjsonnodeT__oLpBKXzW3hF9aCVMo5EymfQ_.align = NIM_ALIGNOF(tySequence__oLpBKXzW3hF9aCVMo5EymfQ*);
NTIseqLjsonnodeT__oLpBKXzW3hF9aCVMo5EymfQ_.kind = 24;
NTIseqLjsonnodeT__oLpBKXzW3hF9aCVMo5EymfQ_.base = (&NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_);
NTIseqLjsonnodeT__oLpBKXzW3hF9aCVMo5EymfQ_.marker = Marker_tySequence__oLpBKXzW3hF9aCVMo5EymfQ;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[27].kind = 1;
TM__9b9bytt1stv9cZ8uqII7HFgew_0[27].offset = offsetof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q, _kind_7.elems);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[27].typ = (&NTIseqLjsonnodeT__oLpBKXzW3hF9aCVMo5EymfQ_);
TM__9b9bytt1stv9cZ8uqII7HFgew_0[27].name = "elems";
NimDT___df9bshXB7C9cTiWPIOtX3j1Q_kind[6] = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[27];
TM__9b9bytt1stv9cZ8uqII7HFgew_0[0].len = 2; TM__9b9bytt1stv9cZ8uqII7HFgew_0[0].kind = 2; TM__9b9bytt1stv9cZ8uqII7HFgew_0[0].sons = &TM__9b9bytt1stv9cZ8uqII7HFgew_3_2[0];
NTIjsonnodeobj__df9bshXB7C9cTiWPIOtX3j1Q_.node = &TM__9b9bytt1stv9cZ8uqII7HFgew_0[0];
NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_.size = sizeof(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*);
NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_.align = NIM_ALIGNOF(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q*);
NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_.kind = 22;
NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_.base = (&NTIjsonnodeobj__df9bshXB7C9cTiWPIOtX3j1Q_);
NTIjsonnode__zfzzuQ8txrdZAYK0WGWpHg_.marker = Marker_tyRef__zfzzuQ8txrdZAYK0WGWpHg;
}

