/* Generated by Nim Compiler v1.6.10 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__systemZassertions_56)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, substrEq__pureZstrutils_229)(NimStringDesc* s, NI pos, NimStringDesc* substr);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, substr__system_7770)(NimStringDesc* s, NI first, NI last);
N_LIB_PRIVATE N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, decRef__system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5305)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5311)(void* usr);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_2190)(void);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_2178)(NimStringDesc* x, NimStringDesc** inArray, NI inArrayLen_0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_1)(NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindCharSet)(NimStringDesc* s, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars, NI start, NI last);
N_LIB_PRIVATE N_NIMCALL(NI, npuParseBiggestInt)(NimStringDesc* s, NI64* number, NI start);
N_LIB_PRIVATE N_NIMCALL(NI, npuParseFloat)(NimStringDesc* s, NF* number, NI start);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toHexImpl__pureZstrutils_717)(NU64 x, NI len, NIM_BOOL handleNegative);
STRING_LITERAL(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2, "strutils.nim(739, 11) `sep.len > 0` ", 36);
extern TNimType NTIseqLstringT__sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_;
extern TNimType NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_;
STRING_LITERAL(TM__JGc9b9bh2D3nTdUR7TGyq8aA_13, "invalid format string", 21);
STRING_LITERAL(TM__JGc9b9bh2D3nTdUR7TGyq8aA_46, "invalid integer: ", 17);
STRING_LITERAL(TM__JGc9b9bh2D3nTdUR7TGyq8aA_47, "invalid float: ", 15);
STRING_LITERAL(TM__JGc9b9bh2D3nTdUR7TGyq8aA_51, "0123456789ABCDEF", 16);
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5258;
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, substrEq__pureZstrutils_229)(NimStringDesc* s, NI pos, NimStringDesc* substr) {
	NIM_BOOL result;
	NI i;
	NI length;
{	result = (NIM_BOOL)0;
	i = ((NI) 0);
	length = (substr ? substr->Sup.len : 0);
	{
		while (1) {
			NIM_BOOL T3_;
			NIM_BOOL T4_;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_3;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_4;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_5;
			T3_ = (NIM_BOOL)0;
			T4_ = (NIM_BOOL)0;
			T4_ = (i < length);
			if (!(T4_)) goto LA5_;
			if (nimAddInt(pos, i, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_3)) { raiseOverflow(); };
			T4_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_3) < (s ? s->Sup.len : 0));
			LA5_: ;
			T3_ = T4_;
			if (!(T3_)) goto LA6_;
			if (nimAddInt(pos, i, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)) { raiseOverflow(); };
			if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4) >= (s ? s->Sup.len : 0)){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4),(s ? s->Sup.len : 0)-1); }
			if (i < 0 || i >= (substr ? substr->Sup.len : 0)){ raiseIndexError2(i,(substr ? substr->Sup.len : 0)-1); }
			T3_ = ((NU8)(s->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_4)]) == (NU8)(substr->data[i]));
			LA6_: ;
			if (!T3_) goto LA2;
			if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) { raiseOverflow(); };
			i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5);
		} LA2: ;
	}
	result = (i == length);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU32)(((NU) (x))) < (NU32)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5354)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5305((&gch__system_5258.zct), c);
}
static N_INLINE(void, decRef__system_5356)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5354(c);
	}
	LA4_: ;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5311)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 8));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5311(p);
	decRef__system_5356(T1_);
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep, NI maxsplit) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ* result;
	result = NIM_NIL;
	{
		if (!!((((NI) 0) < (sep ? sep->Sup.len : 0)))) goto LA3_;
		failedAssertImpl__systemZassertions_56(((NimStringDesc*) &TM__JGc9b9bh2D3nTdUR7TGyq8aA_2));
	}
	LA3_: ;
	result = NIM_NIL;
	{
		NimStringDesc* xX60gensym72_;
		NI lastX60gensym41_;
		NI splitsX60gensym41_;
		xX60gensym72_ = NIM_NIL;
		lastX60gensym41_ = ((NI) 0);
		splitsX60gensym41_ = maxsplit;
		{
			while (1) {
				NI firstX60gensym41_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_7;
				NI T17_;
				NimStringDesc* T18_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_8;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_9;
				if (!(lastX60gensym41_ <= (s ? s->Sup.len : 0))) goto LA7;
				firstX60gensym41_ = lastX60gensym41_;
				{
					while (1) {
						NIM_BOOL T10_;
						NIM_BOOL T12_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_6;
						T10_ = (NIM_BOOL)0;
						T10_ = (lastX60gensym41_ < (s ? s->Sup.len : 0));
						if (!(T10_)) goto LA11_;
						T12_ = (NIM_BOOL)0;
						T12_ = substrEq__pureZstrutils_229(s, lastX60gensym41_, sep);
						T10_ = !(T12_);
						LA11_: ;
						if (!T10_) goto LA9;
						if (nimAddInt(lastX60gensym41_, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)) { raiseOverflow(); };
						lastX60gensym41_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6);
					} LA9: ;
				}
				{
					if (!(splitsX60gensym41_ == ((NI) 0))) goto LA15_;
					lastX60gensym41_ = (s ? s->Sup.len : 0);
				}
				LA15_: ;
				if (nimSubInt(lastX60gensym41_, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_7)) { raiseOverflow(); };
				xX60gensym72_ = substr__system_7770(s, firstX60gensym41_, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_7));
				result = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV3((TGenericSeq*)(result), (&NTIseqLstringT__sM4lkSb7zS6F7OVMvW9cffQ_));
				T17_ = result->Sup.len++;
				T18_ = NIM_NIL;
				T18_ = result->data[T17_]; result->data[T17_] = copyStringRC1(xX60gensym72_);
				if (T18_) nimGCunrefNoCycle(T18_);
				{
					if (!(splitsX60gensym41_ == ((NI) 0))) goto LA21_;
					goto LA6;
				}
				LA21_: ;
				if (nimSubInt(splitsX60gensym41_, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_8)) { raiseOverflow(); };
				splitsX60gensym41_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8);
				if (nimAddInt(lastX60gensym41_, (sep ? sep->Sup.len : 0), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_9)) { raiseOverflow(); };
				lastX60gensym41_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_9);
			} LA7: ;
		} LA6: ;
	}
	return result;
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5349)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5311(src);
		incRef__system_5349(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5311((*dest));
		decRef__system_5356(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_2190)(void) {
	tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T1_;
	NimStringDesc* T2_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_);
	(*T1_).Sup.Sup.name = "ValueError";
	T2_ = NIM_NIL;
	T2_ = (*T1_).Sup.Sup.message; (*T1_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__JGc9b9bh2D3nTdUR7TGyq8aA_13));
	if (T2_) nimGCunrefNoCycle(T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "ValueError", "invalidFormatString", "strutils.nim", 2649);
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_1)(NIM_CHAR c) {
	NIM_CHAR result;
	result = (NIM_CHAR)0;
	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_33;
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3_;
		if (nimAddInt(((NU8)(c)), ((NI) 32), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_33)) { raiseOverflow(); };
		if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_33)) < ((NI) 0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_33)) > ((NI) 255)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_33), ((NI) 0), ((NI) 255)); }
		result = ((NIM_CHAR) (((NI) ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_33)))));
	}
	goto LA1_;
	LA3_: ;
	{
		result = c;
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringDesc* a, NimStringDesc* b) {
	NI result;
	NI aLenX60gensym25_;
	NI bLenX60gensym25_;
	NI iX60gensym25_;
	NI jX60gensym25_;
{	result = (NI)0;
	aLenX60gensym25_ = (a ? a->Sup.len : 0);
	bLenX60gensym25_ = (b ? b->Sup.len : 0);
	iX60gensym25_ = ((NI) 0);
	jX60gensym25_ = ((NI) 0);
	{
		while (1) {
			NIM_CHAR aaX60gensym25_;
			NIM_CHAR bbX60gensym25_;
			{
				while (1) {
					NIM_BOOL T5_;
					T5_ = (NIM_BOOL)0;
					T5_ = (iX60gensym25_ < aLenX60gensym25_);
					if (!(T5_)) goto LA6_;
					T5_ = ((NU8)(a->data[iX60gensym25_]) == (NU8)(95));
					LA6_: ;
					if (!T5_) goto LA4;
					iX60gensym25_ += ((NI) 1);
				} LA4: ;
			}
			{
				while (1) {
					NIM_BOOL T9_;
					T9_ = (NIM_BOOL)0;
					T9_ = (jX60gensym25_ < bLenX60gensym25_);
					if (!(T9_)) goto LA10_;
					T9_ = ((NU8)(b->data[jX60gensym25_]) == (NU8)(95));
					LA10_: ;
					if (!T9_) goto LA8;
					jX60gensym25_ += ((NI) 1);
				} LA8: ;
			}
			{
				if (!(iX60gensym25_ < aLenX60gensym25_)) goto LA13_;
				aaX60gensym25_ = toLowerAscii__stdZprivateZstrimpl_1(a->data[iX60gensym25_]);
			}
			goto LA11_;
			LA13_: ;
			{
				aaX60gensym25_ = 0;
			}
			LA11_: ;
			{
				if (!(jX60gensym25_ < bLenX60gensym25_)) goto LA18_;
				bbX60gensym25_ = toLowerAscii__stdZprivateZstrimpl_1(b->data[jX60gensym25_]);
			}
			goto LA16_;
			LA18_: ;
			{
				bbX60gensym25_ = 0;
			}
			LA16_: ;
			result = (NI)(((NU8)(aaX60gensym25_)) - ((NU8)(bbX60gensym25_)));
			{
				if (!!((result == ((NI) 0)))) goto LA23_;
				goto BeforeRet_;
			}
			LA23_: ;
			{
				if (!(aLenX60gensym25_ <= iX60gensym25_)) goto LA27_;
				{
					if (!(bLenX60gensym25_ <= jX60gensym25_)) goto LA31_;
					result = ((NI) 0);
					goto BeforeRet_;
				}
				LA31_: ;
				result = ((NI) -1);
				goto BeforeRet_;
			}
			goto LA25_;
			LA27_: ;
			{
				if (!(bLenX60gensym25_ <= jX60gensym25_)) goto LA34_;
				result = ((NI) 1);
				goto BeforeRet_;
			}
			goto LA25_;
			LA34_: ;
			LA25_: ;
			iX60gensym25_ += ((NI) 1);
			jX60gensym25_ += ((NI) 1);
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_2178)(NimStringDesc* x, NimStringDesc** inArray, NI inArrayLen_0) {
	NI result;
	NI i;
{	result = (NI)0;
	i = ((NI) 0);
	{
		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_34;
			if (!(i < (inArrayLen_0-1))) goto LA2;
			{
				NI T5_;
				if (i < 0 || i >= inArrayLen_0){ raiseIndexError2(i,inArrayLen_0-1); }
				T5_ = (NI)0;
				T5_ = nsuCmpIgnoreStyle(x, inArray[i]);
				if (!(T5_ == ((NI) 0))) goto LA6_;
				result = i;
				goto BeforeRet_;
			}
			LA6_: ;
			if (nimAddInt(i, ((NI) 2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)) { raiseOverflow(); };
			i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34);
		} LA2: ;
	}
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringDesc** s, NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0) {
	NI i;
	NI num;
	i = ((NI) 0);
	num = ((NI) 0);
	{
		while (1) {
			if (!(i < (formatstr ? formatstr->Sup.len : 0))) goto LA2;
			{
				NIM_BOOL T5_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_11;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_12;
				T5_ = (NIM_BOOL)0;
				if (i < 0 || i >= (formatstr ? formatstr->Sup.len : 0)){ raiseIndexError2(i,(formatstr ? formatstr->Sup.len : 0)-1); }
				T5_ = ((NU8)(formatstr->data[i]) == (NU8)(36));
				if (!(T5_)) goto LA6_;
				if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)) { raiseOverflow(); };
				T5_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11) < (formatstr ? formatstr->Sup.len : 0));
				LA6_: ;
				if (!T5_) goto LA7_;
				if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_12)) { raiseOverflow(); };
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12) >= (formatstr ? formatstr->Sup.len : 0)){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12),(formatstr ? formatstr->Sup.len : 0)-1); }
				switch (((NU8)(formatstr->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12)]))) {
				case 35:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_14;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_15;
					{
						if (!((aLen_0-1) < num)) goto LA12_;
						invalidFormatString__pureZstrutils_2190();
					}
					LA12_: ;
					if (num < 0 || num >= aLen_0){ raiseIndexError2(num,aLen_0-1); }
					unsureAsgnRef((void**) (&(*s)), resizeString((*s), (a[num] ? a[num]->Sup.len : 0) + 0));
appendString((*s), a[num]);
					if (nimAddInt(i, ((NI) 2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_14)) { raiseOverflow(); };
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_14);
					if (nimAddInt(num, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_15)) { raiseOverflow(); };
					num = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_15);
				}
				break;
				case 36:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_16;
					unsureAsgnRef((void**) (&(*s)), addChar((*s), 36));
					if (nimAddInt(i, ((NI) 2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_16)) { raiseOverflow(); };
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_16);
				}
				break;
				case 49 ... 57:
				case 45:
				{
					NI j;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_17;
					NIM_BOOL negative;
					NI idx;
					j = ((NI) 0);
					if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_17)) { raiseOverflow(); };
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_17);
					if (i < 0 || i >= (formatstr ? formatstr->Sup.len : 0)){ raiseIndexError2(i,(formatstr ? formatstr->Sup.len : 0)-1); }
					negative = ((NU8)(formatstr->data[i]) == (NU8)(45));
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_18;
						if (!negative) goto LA18_;
						if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_18)) { raiseOverflow(); };
						i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_18);
					}
					LA18_: ;
					{
						while (1) {
							NIM_BOOL T22_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_19;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_20;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_21;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_22;
							T22_ = (NIM_BOOL)0;
							T22_ = (i < (formatstr ? formatstr->Sup.len : 0));
							if (!(T22_)) goto LA23_;
							if (i < 0 || i >= (formatstr ? formatstr->Sup.len : 0)){ raiseIndexError2(i,(formatstr ? formatstr->Sup.len : 0)-1); }
							T22_ = (((NU8)(formatstr->data[i])) >= ((NU8)(48)) && ((NU8)(formatstr->data[i])) <= ((NU8)(57)));
							LA23_: ;
							if (!T22_) goto LA21;
							if (nimMulInt(j, ((NI) 10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_19)) { raiseOverflow(); };
							if (i < 0 || i >= (formatstr ? formatstr->Sup.len : 0)){ raiseIndexError2(i,(formatstr ? formatstr->Sup.len : 0)-1); }
							if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_19), ((NU8)(formatstr->data[i])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_20)) { raiseOverflow(); };
							if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_20), ((NI) 48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_21)) { raiseOverflow(); };
							j = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_21);
							if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_22)) { raiseOverflow(); };
							i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_22);
						} LA21: ;
					}
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_23;
						if (!!(negative)) goto LA26_;
						if (nimSubInt(j, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_23)) { raiseOverflow(); };
						idx = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_23);
					}
					goto LA24_;
					LA26_: ;
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_24;
						if (nimSubInt(aLen_0, j, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_24)) { raiseOverflow(); };
						idx = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_24);
					}
					LA24_: ;
					{
						NIM_BOOL T31_;
						T31_ = (NIM_BOOL)0;
						T31_ = (idx < ((NI) 0));
						if (T31_) goto LA32_;
						T31_ = ((aLen_0-1) < idx);
						LA32_: ;
						if (!T31_) goto LA33_;
						invalidFormatString__pureZstrutils_2190();
					}
					LA33_: ;
					if (idx < 0 || idx >= aLen_0){ raiseIndexError2(idx,aLen_0-1); }
					unsureAsgnRef((void**) (&(*s)), resizeString((*s), (a[idx] ? a[idx]->Sup.len : 0) + 0));
appendString((*s), a[idx]);
				}
				break;
				case 123:
				{
					NI j_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_25;
					NI k;
					NIM_BOOL negative_2;
					NI isNumber;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_38;
					if (nimAddInt(i, ((NI) 2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_25)) { raiseOverflow(); };
					j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_25);
					k = ((NI) 0);
					if (j_2 < 0 || j_2 >= (formatstr ? formatstr->Sup.len : 0)){ raiseIndexError2(j_2,(formatstr ? formatstr->Sup.len : 0)-1); }
					negative_2 = ((NU8)(formatstr->data[j_2]) == (NU8)(45));
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_26;
						if (!negative_2) goto LA38_;
						if (nimAddInt(j_2, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_26)) { raiseOverflow(); };
						j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_26);
					}
					LA38_: ;
					isNumber = ((NI) 0);
					{
						while (1) {
							NIM_BOOL T42_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_30;
							T42_ = (NIM_BOOL)0;
							T42_ = (j_2 < (formatstr ? formatstr->Sup.len : 0));
							if (!(T42_)) goto LA43_;
							if (j_2 < 0 || j_2 >= (formatstr ? formatstr->Sup.len : 0)){ raiseIndexError2(j_2,(formatstr ? formatstr->Sup.len : 0)-1); }
							T42_ = !((((NU8)(formatstr->data[j_2])) == ((NU8)(0)) || ((NU8)(formatstr->data[j_2])) == ((NU8)(125))));
							LA43_: ;
							if (!T42_) goto LA41;
							{
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_27;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_28;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_29;
								if (j_2 < 0 || j_2 >= (formatstr ? formatstr->Sup.len : 0)){ raiseIndexError2(j_2,(formatstr ? formatstr->Sup.len : 0)-1); }
								if (!(((NU8)(formatstr->data[j_2])) >= ((NU8)(48)) && ((NU8)(formatstr->data[j_2])) <= ((NU8)(57)))) goto LA46_;
								if (nimMulInt(k, ((NI) 10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_27)) { raiseOverflow(); };
								if (j_2 < 0 || j_2 >= (formatstr ? formatstr->Sup.len : 0)){ raiseIndexError2(j_2,(formatstr ? formatstr->Sup.len : 0)-1); }
								if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_27), ((NU8)(formatstr->data[j_2])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)) { raiseOverflow(); };
								if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28), ((NI) 48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_29)) { raiseOverflow(); };
								k = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_29);
								{
									if (!(isNumber == ((NI) 0))) goto LA50_;
									isNumber = ((NI) 1);
								}
								LA50_: ;
							}
							goto LA44_;
							LA46_: ;
							{
								isNumber = ((NI) -1);
							}
							LA44_: ;
							if (nimAddInt(j_2, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_30)) { raiseOverflow(); };
							j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_30);
						} LA41: ;
					}
					{
						NI idx_2;
						if (!(isNumber == ((NI) 1))) goto LA55_;
						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_31;
							if (!!(negative_2)) goto LA59_;
							if (nimSubInt(k, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_31)) { raiseOverflow(); };
							idx_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_31);
						}
						goto LA57_;
						LA59_: ;
						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_32;
							if (nimSubInt(aLen_0, k, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)) { raiseOverflow(); };
							idx_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32);
						}
						LA57_: ;
						{
							NIM_BOOL T64_;
							T64_ = (NIM_BOOL)0;
							T64_ = (idx_2 < ((NI) 0));
							if (T64_) goto LA65_;
							T64_ = ((aLen_0-1) < idx_2);
							LA65_: ;
							if (!T64_) goto LA66_;
							invalidFormatString__pureZstrutils_2190();
						}
						LA66_: ;
						if (idx_2 < 0 || idx_2 >= aLen_0){ raiseIndexError2(idx_2,aLen_0-1); }
						unsureAsgnRef((void**) (&(*s)), resizeString((*s), (a[idx_2] ? a[idx_2]->Sup.len : 0) + 0));
appendString((*s), a[idx_2]);
					}
					goto LA53_;
					LA55_: ;
					{
						NI x;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_35;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_36;
						NimStringDesc* T69_;
						if (nimAddInt(i, ((NI) 2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_35)) { raiseOverflow(); };
						if (nimSubInt(j_2, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_36)) { raiseOverflow(); };
						T69_ = NIM_NIL;
						T69_ = substr__system_7770(formatstr, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_35), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_36));
						x = findNormalized__pureZstrutils_2178(T69_, a, aLen_0);
						{
							NIM_BOOL T72_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_37;
							T72_ = (NIM_BOOL)0;
							T72_ = (((NI) 0) <= x);
							if (!(T72_)) goto LA73_;
							T72_ = (x < (aLen_0-1));
							LA73_: ;
							if (!T72_) goto LA74_;
							if (nimAddInt(x, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_37)) { raiseOverflow(); };
							if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_37) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_37) >= aLen_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_37),aLen_0-1); }
							unsureAsgnRef((void**) (&(*s)), resizeString((*s), (a[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_37)] ? a[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_37)]->Sup.len : 0) + 0));
appendString((*s), a[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_37)]);
						}
						goto LA70_;
						LA74_: ;
						{
							invalidFormatString__pureZstrutils_2190();
						}
						LA70_: ;
					}
					LA53_: ;
					if (nimAddInt(j_2, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_38)) { raiseOverflow(); };
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NI j_3;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_39;
					NI x_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_41;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_42;
					NimStringDesc* T82_;
					if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_39)) { raiseOverflow(); };
					j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_39);
					{
						while (1) {
							NIM_BOOL T80_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_40;
							T80_ = (NIM_BOOL)0;
							T80_ = (j_3 < (formatstr ? formatstr->Sup.len : 0));
							if (!(T80_)) goto LA81_;
							if (j_3 < 0 || j_3 >= (formatstr ? formatstr->Sup.len : 0)){ raiseIndexError2(j_3,(formatstr ? formatstr->Sup.len : 0)-1); }
							T80_ = (((NU8)(formatstr->data[j_3])) >= ((NU8)(97)) && ((NU8)(formatstr->data[j_3])) <= ((NU8)(122)) || ((NU8)(formatstr->data[j_3])) >= ((NU8)(65)) && ((NU8)(formatstr->data[j_3])) <= ((NU8)(90)) || ((NU8)(formatstr->data[j_3])) >= ((NU8)(48)) && ((NU8)(formatstr->data[j_3])) <= ((NU8)(57)) || ((NU8)(formatstr->data[j_3])) >= ((NU8)(128)) && ((NU8)(formatstr->data[j_3])) <= ((NU8)(255)) || ((NU8)(formatstr->data[j_3])) == ((NU8)(95)));
							LA81_: ;
							if (!T80_) goto LA79;
							if (nimAddInt(j_3, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_40)) { raiseOverflow(); };
							j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_40);
						} LA79: ;
					}
					if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_41)) { raiseOverflow(); };
					if (nimSubInt(j_3, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_42)) { raiseOverflow(); };
					T82_ = NIM_NIL;
					T82_ = substr__system_7770(formatstr, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_41), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_42));
					x_2 = findNormalized__pureZstrutils_2178(T82_, a, aLen_0);
					{
						NIM_BOOL T85_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_43;
						T85_ = (NIM_BOOL)0;
						T85_ = (((NI) 0) <= x_2);
						if (!(T85_)) goto LA86_;
						T85_ = (x_2 < (aLen_0-1));
						LA86_: ;
						if (!T85_) goto LA87_;
						if (nimAddInt(x_2, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_43)) { raiseOverflow(); };
						if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_43) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_43) >= aLen_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_43),aLen_0-1); }
						unsureAsgnRef((void**) (&(*s)), resizeString((*s), (a[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_43)] ? a[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_43)]->Sup.len : 0) + 0));
appendString((*s), a[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_43)]);
					}
					goto LA83_;
					LA87_: ;
					{
						invalidFormatString__pureZstrutils_2190();
					}
					LA83_: ;
					i = j_3;
				}
				break;
				default:
				{
					invalidFormatString__pureZstrutils_2190();
				}
				break;
				}
			}
			goto LA3_;
			LA7_: ;
			{
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_44;
				if (i < 0 || i >= (formatstr ? formatstr->Sup.len : 0)){ raiseIndexError2(i,(formatstr ? formatstr->Sup.len : 0)-1); }
				unsureAsgnRef((void**) (&(*s)), addChar((*s), formatstr->data[i]));
				if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_44)) { raiseOverflow(); };
				i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_44);
			}
			LA3_: ;
		} LA2: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0) {
	NimStringDesc* result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_10;
	result = NIM_NIL;
	if (nimAddInt((formatstr ? formatstr->Sup.len : 0), (NI)((NU32)(aLen_0) << (NU32)(((NI) 4))), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_10)) { raiseOverflow(); };
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10)) < ((NI) 0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10), ((NI) 0), ((NI) 2147483647)); }
	result = rawNewString(((NI) ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_10))));
	nsuAddf((&result), formatstr, a, aLen_0);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindCharSet)(NimStringDesc* s, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars, NI start, NI last) {
	NI result;
	NI last_2;
{	result = (NI)0;
	{
		if (!(last == ((NI) 0))) goto LA3_;
		last_2 = ((s ? s->Sup.len : 0)-1);
	}
	goto LA1_;
	LA3_: ;
	{
		last_2 = last;
	}
	LA1_: ;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = ((NI) (start));
		res = colontmp_;
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_45;
				if (!(res <= last_2)) goto LA8;
				i = res;
				{
					if (i < 0 || i >= (s ? s->Sup.len : 0)){ raiseIndexError2(i,(s ? s->Sup.len : 0)-1); }
					if (!((chars[(NU)(((NU8)(s->data[i])))>>3] &(1U<<((NU)(((NU8)(s->data[i])))&7U)))!=0)) goto LA11_;
					result = i;
					goto BeforeRet_;
				}
				LA11_: ;
				if (nimAddInt(res, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_45)) { raiseOverflow(); };
				res = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_45);
			} LA8: ;
		}
	}
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_1692)(NimStringDesc* s, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars) {
	NIM_BOOL result;
	NI T1_;
{	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = nsuFindCharSet(s, chars, ((NI) 0), ((NI) 0));
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI64, nsuParseBiggestInt)(NimStringDesc* s) {
	NI64 result;
	NI L;
	result = (NI64)0;
	result = IL64(0);
	L = npuParseBiggestInt(s, (&result), ((NI) 0));
	{
		NIM_BOOL T3_;
		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T7_;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L == (s ? s->Sup.len : 0)));
		if (T3_) goto LA4_;
		T3_ = (L == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_);
		(*T7_).Sup.Sup.name = "ValueError";
		T8_ = NIM_NIL;
		T8_ = rawNewString((s ? s->Sup.len : 0) + 17);
appendString(T8_, ((NimStringDesc*) &TM__JGc9b9bh2D3nTdUR7TGyq8aA_46));
appendString(T8_, s);
		asgnRef((void**) (&(*T7_).Sup.Sup.message), T8_);
		asgnRef((void**) (&(*T7_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseBiggestInt", "strutils.nim", 1082);
	}
	LA5_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s) {
	NF result;
	NI L;
	result = (NF)0;
	result = 0.0;
	L = npuParseFloat(s, (&result), ((NI) 0));
	{
		NIM_BOOL T3_;
		tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T7_;
		NimStringDesc* T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L == (s ? s->Sup.len : 0)));
		if (T3_) goto LA4_;
		T3_ = (L == ((NI) 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) newObj((&NTIrefvalueerror__Ie1m0dv1ZHg72IgPRr1cDw_), sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIvalueerror__yoNlBGx0D2tRizIdhQuENw_);
		(*T7_).Sup.Sup.name = "ValueError";
		T8_ = NIM_NIL;
		T8_ = rawNewString((s ? s->Sup.len : 0) + 15);
appendString(T8_, ((NimStringDesc*) &TM__JGc9b9bh2D3nTdUR7TGyq8aA_47));
appendString(T8_, s);
		asgnRef((void**) (&(*T7_).Sup.Sup.message), T8_);
		asgnRef((void**) (&(*T7_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseFloat", "strutils.nim", 1114);
	}
	LA5_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count) {
	NimStringDesc* result;
	result = NIM_NIL;
	result = mnewString(count);
	{
		NI i;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_48;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		if (nimSubInt(((NI) (count)), ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_48)) { raiseOverflow(); };
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_48);
		res = ((NI) 0);
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_49;
				if (!(res <= colontmp_)) goto LA3;
				i = res;
				if (i < 0 || i >= (result ? result->Sup.len : 0)){ raiseIndexError2(i,(result ? result->Sup.len : 0)-1); }
				result->data[i] = c;
				if (nimAddInt(res, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_49)) { raiseOverflow(); };
				res = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_49);
			} LA3: ;
		}
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toHexImpl__pureZstrutils_717)(NU64 x, NI len, NIM_BOOL handleNegative) {
	NimStringDesc* result;
	NU64 n;
	result = NIM_NIL;
	n = x;
	result = mnewString(((NI) (len)));
	{
		NI j;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_50;
		NI res;
		j = (NI)0;
		colontmp_ = (NI)0;
		if (nimSubInt(((NI) (len)), ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_50)) { raiseOverflow(); };
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_50);
		res = colontmp_;
		{
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_52;
				if (!(((NI) 0) <= res)) goto LA3;
				j = res;
				if (j < 0 || j >= (result ? result->Sup.len : 0)){ raiseIndexError2(j,(result ? result->Sup.len : 0)-1); }
				if ((NU64)(n & 15ULL) < 0 || (NU64)(n & 15ULL) >= (((NimStringDesc*) &TM__JGc9b9bh2D3nTdUR7TGyq8aA_51) ? ((NimStringDesc*) &TM__JGc9b9bh2D3nTdUR7TGyq8aA_51)->Sup.len : 0)){ raiseIndexError2((NU64)(n & 15ULL),(((NimStringDesc*) &TM__JGc9b9bh2D3nTdUR7TGyq8aA_51) ? ((NimStringDesc*) &TM__JGc9b9bh2D3nTdUR7TGyq8aA_51)->Sup.len : 0)-1); }
				result->data[j] = ((NimStringDesc*) &TM__JGc9b9bh2D3nTdUR7TGyq8aA_51)->data[(NU64)(n & 15ULL)];
				n = (NU64)((NU64)(n) >> (NU64)(((NI) 4)));
				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = (n == 0ULL);
					if (!(T6_)) goto LA7_;
					T6_ = handleNegative;
					LA7_: ;
					if (!T6_) goto LA8_;
					n = 18446744073709551615ULL;
				}
				LA8_: ;
				if (nimSubInt(res, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_52)) { raiseOverflow(); };
				res = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_52);
			} LA3: ;
		}
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toHex__pureZstrutils_1849)(NI x, NI len) {
	NimStringDesc* result;
	result = NIM_NIL;
	result = toHexImpl__pureZstrutils_717(((NU64) (x)), len, (x < ((NI) 0)));
	return result;
}
